set define off;
@person/ddl_person_feed.sql
@person/dml_person_feed.sql
@person/fn_inactive_users_pfeed.sql
--@sap/ddl_sap_feed.sql
--@sap/dml_sap_feed.sql
@sap/upd_sap_feed_log_error.sql
@sap/fn_spool_batch.sql
@sap/fn_generate_rolodex_feed.sql
@sap/fn_generate_sponsor_feed.sql
@sap/kc_sap_feed_pkg.sql
@sap/fn_generate_sap_feed.sql
@sap/fn_sap_resend_batch.sql
@sap/fn_spool_awd_budget_batch.sql
@sap/fn_generate_sap_budget_feed.sql
@sap/fn_generate_master_sap_feed.sql
commit
/
EXIT
/
