select ' Started BUDGET_MODULAR_IDC ' from dual
/
DECLARE
li_budget_period_number NUMBER(12,0);
li_budget NUMBER(12,0);
li_count NUMBER;

CURSOR c_modular IS
SELECT bm.PROPOSAL_NUMBER,bm.VERSION_NUMBER,t3.BUDGET_ID,bp.BUDGET_PERIOD_NUMBER,bm.BUDGET_PERIOD,bm.RATE_NUMBER,bm.DESCRIPTION,bm.IDC_RATE,bm.IDC_BASE,bm.FUNDS_REQUESTED,bm.UPDATE_TIMESTAMP,bm.UPDATE_USER FROM OSP$BUDGET_MODULAR_IDC@coeus.kuali bm
INNER JOIN TEMP_TAB_TO_SYNC_BUDGET t2 on bm.PROPOSAL_NUMBER = t2.PROPOSAL_NUMBER and bm.VERSION_NUMBER = t2.VERSION_NUMBER
INNER JOIN TEMP_BUDGET_MAIN t3 on bm.PROPOSAL_NUMBER=t3.PROPOSAL_NUM and bm.VERSION_NUMBER=t3.BUDGET_VER_NUM
INNER JOIN BUDGET_PERIODS bp on t3.BUDGET_ID=bp.BUDGET_ID and bm.BUDGET_PERIOD=bp.BUDGET_PERIOD 
ORDER BY t3.BUDGET_ID,bm.BUDGET_PERIOD;
r_modular c_modular%ROWTYPE;

BEGIN

IF c_modular%ISOPEN THEN
CLOSE c_modular;
END IF;
OPEN c_modular;
LOOP
FETCH c_modular INTO r_modular;
EXIT WHEN c_modular%NOTFOUND;


  
  select count(*) into li_count from BUDGET_MODULAR_IDC
  where BUDGET_PERIOD_NUMBER=r_modular.BUDGET_PERIOD_NUMBER 
  and BUDGET_PERIOD=r_modular.BUDGET_PERIOD
  and RATE_NUMBER = r_modular.RATE_NUMBER;
  
  IF li_count=0 THEN
  
  INSERT INTO BUDGET_MODULAR_IDC(BUDGET_PERIOD_NUMBER,RATE_NUMBER,BUDGET_ID,BUDGET_PERIOD,DESCRIPTION,IDC_RATE,IDC_BASE,FUNDS_REQUESTED,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
  VALUES(r_modular.BUDGET_PERIOD_NUMBER,r_modular.RATE_NUMBER,r_modular.BUDGET_ID,r_modular.BUDGET_PERIOD,r_modular.DESCRIPTION,r_modular.IDC_RATE,r_modular.IDC_BASE,r_modular.FUNDS_REQUESTED,r_modular.UPDATE_TIMESTAMP,r_modular.UPDATE_USER,1,SYS_GUID());
  
  ELSE
  
  UPDATE BUDGET_MODULAR_IDC SET 
    DESCRIPTION = r_modular.DESCRIPTION,
	IDC_RATE = r_modular.IDC_RATE,
	IDC_BASE = r_modular.IDC_BASE,
	FUNDS_REQUESTED = r_modular.FUNDS_REQUESTED,
	UPDATE_TIMESTAMP = r_modular.UPDATE_TIMESTAMP,
	UPDATE_USER  = r_modular.UPDATE_USER
  where BUDGET_PERIOD_NUMBER = r_modular.BUDGET_PERIOD_NUMBER 
  and BUDGET_PERIOD = r_modular.BUDGET_PERIOD
  and RATE_NUMBER = r_modular.RATE_NUMBER;

  END IF;
  
END LOOP;
CLOSE c_modular;
END;
/
select ' Ended BUDGET_MODULAR_IDC ' from dual
/