/*
declare
li_count number;
begin
select count(*) into li_count from user_tables where table_name='TEMP_ATTACHMENT_FILE';
if li_count=0 then
execute immediate('CREATE TABLE TEMP_ATTACHMENT_FILE AS SELECT * FROM OSP$AWARD_DOCUMENTS@coeus.kuali');
else
execute immediate('drop table TEMP_ATTACHMENT_FILE');
execute immediate('CREATE TABLE TEMP_ATTACHMENT_FILE AS SELECT * FROM OSP$AWARD_DOCUMENTS@coeus.kuali');
end if;
end;
/
*/
DROP TABLE TEMP_ATTACHMENT_FILE
/
CREATE TABLE "TEMP_ATTACHMENT_FILE" 
   (	"MIT_AWARD_NUMBER" CHAR(10 BYTE) NOT NULL ENABLE, 
	"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL ENABLE, 
	"DOCUMENT_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"DOCUMENT_TYPE_CODE" NUMBER(3,0) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"FILE_NAME" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"DOCUMENT" BLOB, 
	"DOCUMENT_STATUS_CODE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE, 
	"UPDATE_USER" VARCHAR2(8 BYTE), 
	"MIME_TYPE" VARCHAR2(100 BYTE)
	);
	commit;
	insert into TEMP_ATTACHMENT_FILE(MIT_AWARD_NUMBER,SEQUENCE_NUMBER,DOCUMENT_ID,DOCUMENT_TYPE_CODE,DESCRIPTION,FILE_NAME,DOCUMENT,DOCUMENT_STATUS_CODE,UPDATE_TIMESTAMP,UPDATE_USER,MIME_TYPE)
	select aat.MIT_AWARD_NUMBER,aat.SEQUENCE_NUMBER,aat.DOCUMENT_ID,aat.DOCUMENT_TYPE_CODE,aat.DESCRIPTION,aat.FILE_NAME,aat.DOCUMENT,aat.DOCUMENT_STATUS_CODE,aat.UPDATE_TIMESTAMP,aat.UPDATE_USER,aat.MIME_TYPE from OSP$AWARD_DOCUMENTS@coeus.kuali aat inner join 
	TEMP_TAB_TO_SYNC_AWARD ts on aat.MIT_AWARD_NUMBER=ts.MIT_AWARD_NUMBER and aat.SEQUENCE_NUMBER=ts.SEQUENCE_NUMBER
	where ts.FEED_TYPE='N';
    commit
	/	
ALTER TABLE	TEMP_ATTACHMENT_FILE NOLOGGING ;
/