select ' Started PROPOSAL_ADMIN_DETAILS ' from dual
/

DECLARE
li_prop_admin_detail_id NUMBER(12,0);
CURSOR c_prop IS
SELECT to_number(pa.DEV_PROPOSAL_NUMBER) PROPOSAL_NUMBER,p.proposal_id,pa.DATE_SUBMITTED_BY_DEPT,pa.DATE_RETURNED_TO_DEPT,
pa.DATE_APPROVED_BY_OSP,pa.DATE_SUBMITTED_TO_AGENCY,pa.INST_PROP_CREATE_DATE,pa.INST_PROP_CREATE_USER,pa.SIGNED_BY,pa.SUBMISSION_TYPE,
p.update_timestamp,p.update_user,1,SYS_GUID()
FROM OSP$PROPOSAL_ADMIN_DETAILS@coeus.kuali pa,PROPOSAL p,temp_tab_to_sync_ip temp 
where pa.INST_PROPOSAL_NUMBER = p.proposal_number
AND pa.INST_PROP_SEQUENCE_NUMBER = p.sequence_number
AND temp.proposal_number = p.proposal_number
AND temp.sequence_number = p.sequence_number
AND temp.FEED_TYPE='N';
r_prop c_prop%ROWTYPE;

BEGIN
IF c_prop%ISOPEN THEN
CLOSE c_prop;
END IF;
OPEN c_prop;
LOOP
FETCH c_prop INTO r_prop;
EXIT WHEN c_prop%NOTFOUND;

SELECT SEQ_PROPOSAL_ADMIN_DETAILS_ID.NEXTVAL into li_prop_admin_detail_id FROM DUAL;
BEGIN
INSERT INTO PROPOSAL_ADMIN_DETAILS(PROPOSAL_ADMIN_DETAIL_ID,DEV_PROPOSAL_NUMBER,INST_PROPOSAL_ID,DATE_SUBMITTED_BY_DEPT,DATE_RETURNED_TO_DEPT,DATE_APPROVED_BY_OSP,DATE_SUBMITTED_TO_AGENCY,INST_PROP_CREATE_DATE,INST_PROP_CREATE_USER,SIGNED_BY,SUBMISSION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
VALUES(li_prop_admin_detail_id,r_prop.PROPOSAL_NUMBER,r_prop.proposal_id,r_prop.DATE_SUBMITTED_BY_DEPT,r_prop.DATE_RETURNED_TO_DEPT,r_prop.DATE_APPROVED_BY_OSP,r_prop.DATE_SUBMITTED_TO_AGENCY,r_prop.INST_PROP_CREATE_DATE,r_prop.INST_PROP_CREATE_USER,r_prop.SIGNED_BY,r_prop.SUBMISSION_TYPE,r_prop.UPDATE_TIMESTAMP,r_prop.UPDATE_USER,1,SYS_GUID());
EXCEPTION
WHEN OTHERS THEN
dbms_output.put_line('DEV_PROPOSAL_NUMBER: '||r_prop.PROPOSAL_NUMBER||' not present in EPS_PROPOSAL table');
END;

END LOOP;
CLOSE c_prop;
END;
/
select ' Ended PROPOSAL_ADMIN_DETAILS ' from dual
/