select ' Started AWARD_APPROVED_SUBAWARDS ' from dual
/
DECLARE
li_cust_id NUMBER(12,0);
li_award_pers_unit_id NUMBER(12,0);
ls_award_number VARCHAR2(40);

CURSOR c_award_comment IS
SELECT a.AWARD_NUMBER,a.SEQUENCE_NUMBER  Kuali_sequence_number,a.AWARD_ID,ac.MIT_AWARD_NUMBER,ac.SEQUENCE_NUMBER,ac.SUBCONTRACTOR_NAME,o.ORGANIZATION_ID,ac.AMOUNT,ac.UPDATE_TIMESTAMP,ac.UPDATE_USER
FROM AWARD a 
INNER JOIN TEMP_TAB_TO_SYNC_AWARD t ON a.AWARD_NUMBER=replace(t.MIT_AWARD_NUMBER,'-','-00') AND a.SEQUENCE_NUMBER=t.SEQUENCE_NUMBER
LEFT OUTER JOIN OSP$AWARD_APPROVED_SUBCONTRACT@coeus.kuali ac ON t.MIT_AWARD_NUMBER=ac.MIT_AWARD_NUMBER and t.SEQUENCE_NUMBER=ac.SEQUENCE_NUMBER
left outer join ORGANIZATION o on ac.SUBCONTRACTOR_NAME=o.ORGANIZATION_NAME 
WHERE t.FEED_TYPE='N'
ORDER BY a.AWARD_NUMBER,a.SEQUENCE_NUMBER;
r_award_comment c_award_comment%ROWTYPE;

BEGIN
IF c_award_comment%ISOPEN THEN
CLOSE c_award_comment;
END IF;
OPEN c_award_comment;
LOOP
FETCH c_award_comment INTO r_award_comment;
EXIT WHEN c_award_comment%NOTFOUND;

begin

    IF r_award_comment.MIT_AWARD_NUMBER IS NULL THEN
	
	   IF ls_award_number is null THEN
	
	          	   INSERT INTO AWARD_APPROVED_SUBAWARDS( AWARD_APPROVED_SUBAWARD_ID,AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,ORGANIZATION_NAME,AMOUNT,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,ORGANIZATION_ID,OBJ_ID)
	               SELECT SEQ_AWARD_APPROVED_SUBAWARD_ID.NEXTVAL,r_award_comment.AWARD_ID,r_award_comment.AWARD_NUMBER,r_award_comment.Kuali_sequence_number,ORGANIZATION_NAME,AMOUNT,UPDATE_TIMESTAMP,UPDATE_USER,1,ORGANIZATION_ID,SYS_GUID() FROM AWARD_APPROVED_SUBAWARDS
                   WHERE AWARD_NUMBER=r_award_comment.AWARD_NUMBER AND SEQUENCE_NUMBER=(SELECT MAX(aw.SEQUENCE_NUMBER) FROM AWARD_APPROVED_SUBAWARDS aw WHERE aw.AWARD_NUMBER=r_award_comment.AWARD_NUMBER AND SEQUENCE_NUMBER<r_award_comment.Kuali_sequence_number);
    
    
                   ls_award_number:=r_award_comment.AWARD_NUMBER||r_award_comment.Kuali_sequence_number;
		   
		ELSIF ls_award_number<>r_award_comment.AWARD_NUMBER||r_award_comment.Kuali_sequence_number THEN
		
              	   INSERT INTO AWARD_APPROVED_SUBAWARDS( AWARD_APPROVED_SUBAWARD_ID,AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,ORGANIZATION_NAME,AMOUNT,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,ORGANIZATION_ID,OBJ_ID)
	               SELECT SEQ_AWARD_APPROVED_SUBAWARD_ID.NEXTVAL,r_award_comment.AWARD_ID,r_award_comment.AWARD_NUMBER,r_award_comment.Kuali_sequence_number,ORGANIZATION_NAME,AMOUNT,UPDATE_TIMESTAMP,UPDATE_USER,1,ORGANIZATION_ID,SYS_GUID() FROM AWARD_APPROVED_SUBAWARDS
                   WHERE AWARD_NUMBER=r_award_comment.AWARD_NUMBER AND SEQUENCE_NUMBER=(SELECT MAX(aw.SEQUENCE_NUMBER) FROM AWARD_APPROVED_SUBAWARDS aw WHERE aw.AWARD_NUMBER=r_award_comment.AWARD_NUMBER AND SEQUENCE_NUMBER<r_award_comment.Kuali_sequence_number);
    
                   ls_award_number:=r_award_comment.AWARD_NUMBER||r_award_comment.Kuali_sequence_number;
			
		END IF;
	
    ELSE
	

       INSERT INTO AWARD_APPROVED_SUBAWARDS( AWARD_APPROVED_SUBAWARD_ID,AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,ORGANIZATION_NAME,AMOUNT,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,ORGANIZATION_ID,OBJ_ID)
	   VALUES(SEQ_AWARD_APPROVED_SUBAWARD_ID.NEXTVAL,r_award_comment.AWARD_ID,r_award_comment.AWARD_NUMBER,r_award_comment.Kuali_sequence_number,r_award_comment.SUBCONTRACTOR_NAME,r_award_comment.AMOUNT,r_award_comment.UPDATE_TIMESTAMP,r_award_comment.UPDATE_USER,1,r_award_comment.ORGANIZATION_ID,SYS_GUID());
    
	END IF;	

exception
when others then
	dbms_output.put_line('ERROR IN AWARD_APPROVED_SUBAWARDS. AWARD_NUMBER,SEQUENCE_NUMBER'||r_award_comment.AWARD_NUMBER||','||r_award_comment.Kuali_sequence_number||'-'||sqlerrm);
end;	
	
END LOOP;
CLOSE c_award_comment;
END;

/
select ' Ended AWARD_APPROVED_SUBAWARDS ' from dual
/