select ' Started AWARD_UNIT_CONTACTS ' from dual
/
DECLARE
li_cust_id NUMBER(12,0);
ls_award_number VARCHAR2(40);

CURSOR c_award_comment IS
SELECT a.AWARD_NUMBER,a.SEQUENCE_NUMBER  Kuali_sequence_number,a.AWARD_ID,ac.MIT_AWARD_NUMBER,ac.SEQUENCE_NUMBER,p.FULL_NAME,ua.UNIT_NUMBER,ac.UNIT_ADMINISTRATOR_TYPE_CODE,ac.ADMINISTRATOR,ac.UPDATE_TIMESTAMP,ac.UPDATE_USER FROM AWARD a 
INNER JOIN TEMP_TAB_TO_SYNC_AWARD t ON a.AWARD_NUMBER=replace(t.MIT_AWARD_NUMBER,'-','-00') AND a.SEQUENCE_NUMBER=t.SEQUENCE_NUMBER
INNER  JOIN OSP$AWARD_UNIT_ADMINISTRATORS@coeus.kuali ac ON t.MIT_AWARD_NUMBER=ac.MIT_AWARD_NUMBER and t.SEQUENCE_NUMBER=ac.SEQUENCE_NUMBER
left outer join OSP$UNIT_ADMINISTRATORS@coeus.kuali ua on ua.ADMINISTRATOR=ac.ADMINISTRATOR and ua.UNIT_ADMINISTRATOR_TYPE_CODE=ac.UNIT_ADMINISTRATOR_TYPE_CODE 
left outer join OSP$PERSON@coeus.kuali p on p.PERSON_ID=ac.ADMINISTRATOR
WHERE t.FEED_TYPE='N'
ORDER BY a.AWARD_NUMBER,a.SEQUENCE_NUMBER;
r_award_comment c_award_comment%ROWTYPE;

BEGIN
IF c_award_comment%ISOPEN THEN
CLOSE c_award_comment;
END IF;
OPEN c_award_comment;
LOOP
FETCH c_award_comment INTO r_award_comment;
EXIT WHEN c_award_comment%NOTFOUND;


       INSERT INTO AWARD_UNIT_CONTACTS(AWARD_UNIT_CONTACT_ID,AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,PERSON_ID,FULL_NAME,UNIT_ADMINISTRATOR_TYPE_CODE,UNIT_CONTACT_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,UNIT_ADMINISTRATOR_UNIT_NUMBER)
	    VALUES(SEQUENCE_AWARD_ID.NEXTVAL,r_award_comment.AWARD_ID,r_award_comment.AWARD_NUMBER,r_award_comment.SEQUENCE_NUMBER,r_award_comment.ADMINISTRATOR,r_award_comment.FULL_NAME,r_award_comment.UNIT_ADMINISTRATOR_TYPE_CODE,'CONTACT',r_award_comment.UPDATE_TIMESTAMP,r_award_comment.UPDATE_USER,1,SYS_GUID(),r_award_comment.UNIT_NUMBER);

	
END LOOP;
CLOSE c_award_comment;
END;
/
select ' Ended AWARD_UNIT_CONTACTS ' from dual
/