 DROP TABLE TEMP_BUD_SUB_AWD
 /
  DROP TABLE TEMP_BUD_SUB_AWD_ATT
 /
 CREATE TABLE "TEMP_BUD_SUB_AWD" 
   (	"PROPOSAL_NUMBER" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"VERSION_NUMBER" NUMBER(3,0) NOT NULL ENABLE, 
	"SUB_AWARD_NUMBER" NUMBER(3,0) NOT NULL ENABLE, 
	"ORGANIZATION_NAME" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"SUB_AWARD_STATUS_CODE" NUMBER(3,0) NOT NULL ENABLE, 
	"SUB_AWARD_XFD_FILE" BLOB DEFAULT EMPTY_BLOB(), 
	"SUB_AWARD_XFD_FILE_NAME" VARCHAR2(256 BYTE), 
	"COMMENTS" VARCHAR2(2000 BYTE), 
	"XFD_UPDATE_USER" VARCHAR2(8 BYTE), 
	"XFD_UPDATE_TIMESTAMP" DATE, 
	"SUB_AWARD_XML_FILE" CLOB DEFAULT EMPTY_CLOB(), 
	"TRANSLATION_COMMENTS" VARCHAR2(2000 BYTE), 
	"XML_UPDATE_USER" VARCHAR2(8 BYTE), 
	"XML_UPDATE_TIMESTAMP" DATE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"NAMESPACE" VARCHAR2(200 BYTE), 
	"FORM_NAME" VARCHAR2(100 BYTE));
	commit;
	insert into TEMP_BUD_SUB_AWD(PROPOSAL_NUMBER, VERSION_NUMBER, SUB_AWARD_NUMBER,ORGANIZATION_NAME, SUB_AWARD_STATUS_CODE, COMMENTS, XFD_UPDATE_USER, XFD_UPDATE_TIMESTAMP,  TRANSLATION_COMMENTS, XML_UPDATE_USER, XML_UPDATE_TIMESTAMP,UPDATE_TIMESTAMP, UPDATE_USER, NAMESPACE, FORM_NAME, SUB_AWARD_XFD_FILE_NAME, SUB_AWARD_XFD_FILE,SUB_AWARD_XML_FILE)
	SELECT PROPOSAL_NUMBER, VERSION_NUMBER, SUB_AWARD_NUMBER,ORGANIZATION_NAME, SUB_AWARD_STATUS_CODE, COMMENTS, XFD_UPDATE_USER, XFD_UPDATE_TIMESTAMP,  TRANSLATION_COMMENTS, XML_UPDATE_USER, XML_UPDATE_TIMESTAMP,UPDATE_TIMESTAMP, UPDATE_USER, NAMESPACE, FORM_NAME, SUB_AWARD_XFD_FILE_NAME, SUB_AWARD_XFD_FILE,SUB_AWARD_XML_FILE FROM OSP$BUDGET_SUB_AWARDS@coeus.kuali;
	commit;
	CREATE TABLE "TEMP_BUD_SUB_AWD_ATT" 
   ("PROPOSAL_NUMBER" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"VERSION_NUMBER" NUMBER(3,0) NOT NULL ENABLE, 
	"SUB_AWARD_NUMBER" NUMBER(3,0) NOT NULL ENABLE, 
	"CONTENT_ID" VARCHAR2(350 BYTE) NOT NULL ENABLE, 
	"CONTENT_TYPE" VARCHAR2(30 BYTE), 
	"ATTACHMENT" BLOB DEFAULT EMPTY_BLOB(), 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(8 BYTE) NOT NULL ENABLE);
	commit;
	insert into TEMP_BUD_SUB_AWD_ATT(PROPOSAL_NUMBER,VERSION_NUMBER,SUB_AWARD_NUMBER,CONTENT_ID,CONTENT_TYPE,ATTACHMENT,UPDATE_TIMESTAMP,UPDATE_USER)
	SELECT  PROPOSAL_NUMBER,VERSION_NUMBER,SUB_AWARD_NUMBER,CONTENT_ID,CONTENT_TYPE,ATTACHMENT,UPDATE_TIMESTAMP,UPDATE_USER  FROM OSP$BUDGET_SUB_AWARD_ATT@coeus.kuali;
	commit
	/
	DECLARE
li_count number;
BEGIN
   select count(*) into li_count  from user_tables where table_name='ORGANIZATION_MAPPING';
   IF li_count=0 THEN
     execute immediate('CREATE TABLE ORGANIZATION_MAPPING(
							ORGANIZATION_ID	VARCHAR2(8),
							ORGANIZATION_NAME	VARCHAR2(60),
							SUBAWARD_ORGANIZATION_NAME VARCHAR2(60)
							)');
    END IF;
END;
/
DECLARE
li_count number;
BEGIN
  select count(*) into li_count from ORGANIZATION_MAPPING;
  IF li_count=0 THEN
     INSERT INTO ORGANIZATION_MAPPING(ORGANIZATION_ID,ORGANIZATION_NAME,SUBAWARD_ORGANIZATION_NAME)
     SELECT distinct o.ORGANIZATION_ID,o.ORGANIZATION_NAME,t.ORGANIZATION_NAME FROM ORGANIZATION o,TEMP_BUD_SUB_AWD t
     WHERE o.ORGANIZATION_NAME like '%'||t.ORGANIZATION_NAME||'%';
   END IF;
END;
/


/*
declare
li_count number;
begin
select count(*) into li_count from user_tables where table_name='TEMP_BUD_SUB_AWD';
if li_count=0 then
execute immediate('create table TEMP_BUD_SUB_AWD as SELECT PROPOSAL_NUMBER, VERSION_NUMBER, SUB_AWARD_NUMBER,ORGANIZATION_NAME, SUB_AWARD_STATUS_CODE, COMMENTS, XFD_UPDATE_USER, XFD_UPDATE_TIMESTAMP,  TRANSLATION_COMMENTS, XML_UPDATE_USER, XML_UPDATE_TIMESTAMP,UPDATE_TIMESTAMP, UPDATE_USER, NAMESPACE, FORM_NAME, SUB_AWARD_XFD_FILE_NAME, SUB_AWARD_XFD_FILE,SUB_AWARD_XML_FILE FROM OSP$BUDGET_SUB_AWARDS@coeus.kuali');
else
execute immediate('drop table TEMP_BUD_SUB_AWD');
execute immediate('create table TEMP_BUD_SUB_AWD as SELECT PROPOSAL_NUMBER, VERSION_NUMBER, SUB_AWARD_NUMBER,ORGANIZATION_NAME, SUB_AWARD_STATUS_CODE, COMMENTS, XFD_UPDATE_USER, XFD_UPDATE_TIMESTAMP,  TRANSLATION_COMMENTS, XML_UPDATE_USER, XML_UPDATE_TIMESTAMP,UPDATE_TIMESTAMP, UPDATE_USER, NAMESPACE, FORM_NAME, SUB_AWARD_XFD_FILE_NAME, SUB_AWARD_XFD_FILE,SUB_AWARD_XML_FILE FROM OSP$BUDGET_SUB_AWARDS@coeus.kuali');
end if;

select count(*) into li_count from user_tables where table_name='TEMP_BUD_SUB_AWD_ATT';
if li_count=0 then
execute immediate('create table TEMP_BUD_SUB_AWD_ATT as SELECT  PROPOSAL_NUMBER,VERSION_NUMBER,SUB_AWARD_NUMBER,CONTENT_ID,CONTENT_TYPE,ATTACHMENT,UPDATE_TIMESTAMP,UPDATE_USER  FROM OSP$BUDGET_SUB_AWARD_ATT@coeus.kuali');
else
execute immediate('drop table TEMP_BUD_SUB_AWD_ATT');
execute immediate('create table TEMP_BUD_SUB_AWD_ATT as SELECT  PROPOSAL_NUMBER,VERSION_NUMBER,SUB_AWARD_NUMBER,CONTENT_ID,CONTENT_TYPE,ATTACHMENT,UPDATE_TIMESTAMP,UPDATE_USER  FROM OSP$BUDGET_SUB_AWARD_ATT@coeus.kuali');
end if;
end;
/
*/