select ' Started UPDATE_AWARD_UNIT_CONTACTS ' from dual
/
DECLARE

ls_award_number VARCHAR2(20);

CURSOR c_unit IS 
SELECT a.AWARD_ID,replace(u.MIT_AWARD_NUMBER,'-','-00') AWARD_NUMBER,u.SEQUENCE_NUMBER,u.ADMINISTRATOR,p.FULL_NAME,u.UNIT_ADMINISTRATOR_TYPE_CODE,'CONTACT' as UNIT_CONTACT_TYPE,u.UPDATE_TIMESTAMP,u.UPDATE_USER,ua.UNIT_NUMBER FROM OSP$AWARD_UNIT_ADMINISTRATORS@coeus.kuali u
inner join TEMP_TAB_TO_SYNC_AWARD ts on u.MIT_AWARD_NUMBER=ts.MIT_AWARD_NUMBER and u.SEQUENCE_NUMBER=ts.SEQUENCE_NUMBER 
left outer join OSP$UNIT_ADMINISTRATORS@coeus.kuali ua on ua.ADMINISTRATOR=u.ADMINISTRATOR and ua.UNIT_ADMINISTRATOR_TYPE_CODE=u.UNIT_ADMINISTRATOR_TYPE_CODE 
inner join AWARD a on replace(u.MIT_AWARD_NUMBER,'-','-00')=a.AWARD_NUMBER and fn_get_kuali_seq(u.MIT_AWARD_NUMBER,u.SEQUENCE_NUMBER)=a.SEQUENCE_NUMBER 
left outer join OSP$PERSON@coeus.kuali p on p.PERSON_ID=u.ADMINISTRATOR
where ts.FEED_TYPE='C';
r_unit c_unit%ROWTYPE;

BEGIN

IF c_unit%ISOPEN THEN 
CLOSE c_unit;
END IF;
OPEN c_unit;
LOOP
FETCH c_unit INTO r_unit;
exit when c_unit%notfound;

begin

	IF ls_award_number IS NULL THEN

	   DELETE FROM AWARD_UNIT_CONTACTS WHERE AWARD_NUMBER=r_unit.AWARD_NUMBER AND SEQUENCE_NUMBER=r_unit.SEQUENCE_NUMBER;
	   ls_award_number:=r_unit.AWARD_NUMBER||r_unit.SEQUENCE_NUMBER;

	ELSIF ls_award_number<>r_unit.AWARD_NUMBER||r_unit.SEQUENCE_NUMBER THEN
	  
		DELETE FROM AWARD_UNIT_CONTACTS WHERE AWARD_NUMBER=r_unit.AWARD_NUMBER AND SEQUENCE_NUMBER=r_unit.SEQUENCE_NUMBER;
		ls_award_number:=r_unit.AWARD_NUMBER||r_unit.SEQUENCE_NUMBER;

	END IF;

	INSERT INTO AWARD_UNIT_CONTACTS(AWARD_UNIT_CONTACT_ID,AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,PERSON_ID,FULL_NAME,UNIT_ADMINISTRATOR_TYPE_CODE,UNIT_CONTACT_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,UNIT_ADMINISTRATOR_UNIT_NUMBER)
	VALUES(SEQUENCE_AWARD_ID.NEXTVAL,r_unit.AWARD_ID,r_unit.AWARD_NUMBER,r_unit.SEQUENCE_NUMBER,r_unit.ADMINISTRATOR,r_unit.FULL_NAME,r_unit.UNIT_ADMINISTRATOR_TYPE_CODE,r_unit.UNIT_CONTACT_TYPE,r_unit.UPDATE_TIMESTAMP,r_unit.UPDATE_USER,1,SYS_GUID(),r_unit.UNIT_NUMBER);

exception
when others then
	dbms_output.put_line('Error in update of AWARD_UNIT_CONTACTS. AWARD_NUMBER,SEQUENCE_NUMBER'||r_unit.AWARD_NUMBER||','||r_unit.SEQUENCE_NUMBER||'-'||sqlerrm);
end;	
	
END LOOP;
CLOSE c_unit;
END;
/
select ' Ended UPDATE_AWARD_UNIT_CONTACTS ' from dual
/