select ' Stared UPDATE_AWARD  ' from dual
/
DECLARE
li_ver_nbr NUMBER(8):=1;
li_award_id NUMBER(22);
as_award_id NUMBER(22);
ll_closeout_date DATE;
ls_archive_location VARCHAR2(50 );
ls_transaction_type_cd  VARCHAR2(3 );
ll_notice_date DATE;
ls_cfda_number VARCHAR2(7);
li_loop number;
ls_doc_nbr VARCHAR2(40);
li_cfda_lenght PLS_INTEGER;
ls_hierarchy_sync_child varchar2(2):='N';
ls_award_number VARCHAR2(12);
li_new_seq NUMBER(4,0):=0;
li_change_occured pls_integer;
li_orig_seq NUMBER(4,0);
ls_award_sequence_status VARCHAR2(10):='PENDING';
ls_error_page VARCHAR2(20);
li_commit_count number:=0;
ls_lead_unit_num  VARCHAR2(8);
li_krew_rnt_brch NUMBER(19,0);
li_krew_rnt_node NUMBER(19,0);
li_krew_rne_node_instn NUMBER(19,0);
ls_awd_number VARCHAR2(20);
ls_proto VARCHAR2(20);
li_seq NUMBER(4);

Cursor c_awd_upd IS
SELECT t.feed_id, awh.ACTIVITY_TYPE_CODE ACTIVITY_TYPE_CODE,awh.AWARD_TYPE_CODE AWARD_TYPE_CODE,awh.PRIME_SPONSOR_CODE PRIME_SPONSOR_CODE,awh.CFDA_NUMBER CFDA_NUMBER,
awh.METHOD_OF_PAYMENT_CODE METHOD_OF_PAYMENT_CODE,awh.DFAFS_NUMBER DFAFS_NUMBER,awh.PRE_AWARD_AUTHORIZED_AMOUNT PRE_AWARD_AUTHORIZED_AMOUNT,
awh.PRE_AWARD_EFFECTIVE_DATE PRE_AWARD_EFFECTIVE_DATE,awh.PROCUREMENT_PRIORITY_CODE PROCUREMENT_PRIORITY_CODE,awh.PROPOSAL_NUMBER PROPOSAL_NUMBER,
awh.SPECIAL_EB_RATE_OFF_CAMPUS SPECIAL_EB_RATE_OFF_CAMPUS,awh.SPECIAL_EB_RATE_ON_CAMPUS SPECIAL_EB_RATE_ON_CAMPUS,awh.SUB_PLAN_FLAG SUB_PLAN_FLAG,
awh.BASIS_OF_PAYMENT_CODE BASIS_OF_PAYMENT_CODE,awh.ACCOUNT_TYPE_CODE ACCOUNT_TYPE_CODE,aw.MIT_AWARD_NUMBER MIT_AWARD_NUMBER,aw.SEQUENCE_NUMBER SEQUENCE_NUMBER,
aw.SPONSOR_CODE SPONSOR_CODE,aw.STATUS_CODE STATUS_CODE,aw.TEMPLATE_CODE TEMPLATE_CODE,aw.ACCOUNT_NUMBER ACCOUNT_NUMBER,
aw.APPRVD_EQUIPMENT_INDICATOR APPRVD_EQUIPMENT_INDICATOR,aw.APPRVD_FOREIGN_TRIP_INDICATOR APPRVD_FOREIGN_TRIP_INDICATOR,
aw.APPRVD_SUBCONTRACT_INDICATOR APPRVD_SUBCONTRACT_INDICATOR,aw.AWARD_EFFECTIVE_DATE AWARD_EFFECTIVE_DATE,aw.KEY_PERSON_INDICATOR,
aw.AWARD_EXECUTION_DATE AWARD_EXECUTION_DATE,aw.BEGIN_DATE BEGIN_DATE,aw.COST_SHARING_INDICATOR COST_SHARING_INDICATOR,aw.IDC_INDICATOR IDC_INDICATOR,
aw.MODIFICATION_NUMBER MODIFICATION_NUMBER,aw.NSF_CODE NSF_CODE,aw.PAYMENT_SCHEDULE_INDICATOR PAYMENT_SCHEDULE_INDICATOR,aw.SCIENCE_CODE_INDICATOR SCIENCE_CODE_INDICATOR,
aw.SPECIAL_REVIEW_INDICATOR SPECIAL_REVIEW_INDICATOR,aw.SPONSOR_AWARD_NUMBER SPONSOR_AWARD_NUMBER,aw.TRANSFER_SPONSOR_INDICATOR TRANSFER_SPONSOR_INDICATOR,
aw.UPDATE_TIMESTAMP UPDATE_TIMESTAMP,awh.TITLE,aw.UPDATE_USER UPDATE_USER FROM OSP$AWARD@coeus.kuali aw LEFT OUTER JOIN  OSP$AWARD_HEADER@coeus.kuali awh ON awh.MIT_AWARD_NUMBER=aw.MIT_AWARD_NUMBER AND awh.SEQUENCE_NUMBER=aw.SEQUENCE_NUMBER INNER JOIN TEMP_TAB_TO_SYNC_AWARD t ON aw.MIT_AWARD_NUMBER=t.MIT_AWARD_NUMBER and aw.SEQUENCE_NUMBER=t.SEQUENCE_NUMBER 
where t.FEED_TYPE='C'
order by aw.MIT_AWARD_NUMBER,aw.SEQUENCE_NUMBER;
r_awd_upd c_awd_upd%ROWTYPE;

BEGIN
IF c_awd_upd%ISOPEN THEN
CLOSE c_awd_upd;
END IF;
OPEN c_awd_upd;
LOOP
FETCH c_awd_upd INTO r_awd_upd;
EXIT WHEN c_awd_upd%NOTFOUND;


li_change_occured:=0;

SELECT replace(r_awd_upd.MIT_AWARD_NUMBER,'-','-00') INTO ls_award_number FROM DUAL;

begin
SELECT CLOSEOUT_DATE,ARCHIVE_LOCATION INTO ll_closeout_date,ls_archive_location FROM OSP$AWARD_CLOSEOUT WHERE MIT_AWARD_NUMBER=r_awd_upd.MIT_AWARD_NUMBER AND SEQUENCE_NUMBER=r_awd_upd.SEQUENCE_NUMBER;
exception
when no_data_found then
ll_closeout_date:=null;
ls_archive_location:=null;
WHEN TOO_MANY_ROWS THEN    --UMB added next four lines
    ll_closeout_date:=null;
    ls_archive_location:=null;
    dbms_output.put_line('Closeout Too many rows: MIT_AWARD_NUMBER ' || r_awd_upd.MIT_AWARD_NUMBER || ', Seq: ' || r_awd_upd.SEQUENCE_NUMBER);
end;
begin
--SELECT TRANSACTION_TYPE_CODE,NOTICE_DATE INTO ls_transaction_type_cd,ll_notice_date FROM OSP$AWARD_AMOUNT_TRANSACTION WHERE AWARD_NUMBER=r_award.MIT_AWARD_NUMBER;
SELECT TRANSACTION_TYPE_CODE,NOTICE_DATE INTO ls_transaction_type_cd,ll_notice_date FROM OSP$AWARD_AMOUNT_TRANSACTION WHERE mit_award_number=r_awd_upd.MIT_AWARD_NUMBER and TRANSACTION_ID=(
select aai.TRANSACTION_ID from OSP$AWARD_AMOUNT_INFO aai where aai.mit_award_number=r_awd_upd.MIT_AWARD_NUMBER and aai.sequence_number= r_awd_upd.SEQUENCE_NUMBER
and aai.AMOUNT_SEQUENCE_NUMBER=(select max(aa.AMOUNT_SEQUENCE_NUMBER) from OSP$AWARD_AMOUNT_INFO aa where aa.mit_award_number=aai.mit_award_number and aa.sequence_number=aai.sequence_number ));

exception
WHEN TOO_MANY_ROWS THEN   --UMB added next four lines
       ls_transaction_type_cd:=null;
       ll_notice_date:=null;
       dbms_output.put_line('Award Too many rows: MIT_AWARD_NUMBER ' || r_awd_upd.MIT_AWARD_NUMBER || ', Seq: ' || r_awd_upd.SEQUENCE_NUMBER);
when others then
ls_transaction_type_cd:=null;
ll_notice_date:=null;
end;
ls_cfda_number:=r_awd_upd.CFDA_NUMBER;
SELECT LENGTH(TRIM(ls_cfda_number)) INTO li_cfda_lenght  FROM DUAL;
IF ls_cfda_number IS NOT NULL AND li_cfda_lenght >0 THEN
SELECT SUBSTR(trim(ls_cfda_number),1,2)||'.'||SUBSTR(trim(ls_cfda_number),3)INTO ls_cfda_number FROM DUAL;
END IF;
--
	
	
	BEGIN			
			select b.unit_number INTO ls_lead_unit_num from osp$award_units@coeus.kuali b
			where b.lead_unit_flag = 'Y'
			and   b.mit_award_number = r_awd_upd.MIT_AWARD_NUMBER
			and   b.sequence_number = ( select max(s1.sequence_number) 
										from osp$award_units@coeus.kuali s1
										where s1.mit_award_number = r_awd_upd.MIT_AWARD_NUMBER
										and   s1.sequence_number <= r_awd_upd.SEQUENCE_NUMBER
									  )
			and rownum < 2;
			
	EXCEPTION
	WHEN OTHERS THEN
		ls_lead_unit_num:=NULL;
	END;
	
	
li_orig_seq:=r_awd_upd.SEQUENCE_NUMBER;

UPDATE AWARD
SET CLOSEOUT_DATE=ll_closeout_date,
TRANSACTION_TYPE_CODE=ls_transaction_type_cd,
NOTICE_DATE=ll_notice_date,
LEAD_UNIT_NUMBER=ls_lead_unit_num,
ACTIVITY_TYPE_CODE=r_awd_upd.ACTIVITY_TYPE_CODE,
AWARD_TYPE_CODE=r_awd_upd.AWARD_TYPE_CODE,
PRIME_SPONSOR_CODE=r_awd_upd.PRIME_SPONSOR_CODE,
CFDA_NUMBER=r_awd_upd.CFDA_NUMBER,
METHOD_OF_PAYMENT_CODE=r_awd_upd.METHOD_OF_PAYMENT_CODE,
DFAFS_NUMBER=r_awd_upd.DFAFS_NUMBER,
PRE_AWARD_AUTHORIZED_AMOUNT=r_awd_upd.PRE_AWARD_AUTHORIZED_AMOUNT,
PRE_AWARD_EFFECTIVE_DATE=r_awd_upd.PRE_AWARD_EFFECTIVE_DATE,
PROCUREMENT_PRIORITY_CODE=r_awd_upd.PROCUREMENT_PRIORITY_CODE,
PROPOSAL_NUMBER=r_awd_upd.PROPOSAL_NUMBER,
SPECIAL_EB_RATE_OFF_CAMPUS=r_awd_upd.SPECIAL_EB_RATE_OFF_CAMPUS,
SPECIAL_EB_RATE_ON_CAMPUS=r_awd_upd.SPECIAL_EB_RATE_ON_CAMPUS,
SUB_PLAN_FLAG=r_awd_upd.SUB_PLAN_FLAG,
TITLE=r_awd_upd.TITLE,
UPDATE_TIMESTAMP=r_awd_upd.UPDATE_TIMESTAMP,
UPDATE_USER=r_awd_upd.UPDATE_USER,
ARCHIVE_LOCATION=ls_archive_location,
BASIS_OF_PAYMENT_CODE=r_awd_upd.BASIS_OF_PAYMENT_CODE,
SPONSOR_CODE=r_awd_upd.SPONSOR_CODE,
STATUS_CODE=r_awd_upd.STATUS_CODE,
TEMPLATE_CODE=r_awd_upd.TEMPLATE_CODE,
ACCOUNT_NUMBER=r_awd_upd.ACCOUNT_NUMBER,
APPRVD_EQUIPMENT_INDICATOR=r_awd_upd.APPRVD_EQUIPMENT_INDICATOR,
APPRVD_FOREIGN_TRIP_INDICATOR=r_awd_upd.APPRVD_FOREIGN_TRIP_INDICATOR,
APPRVD_SUBCONTRACT_INDICATOR=r_awd_upd.APPRVD_SUBCONTRACT_INDICATOR,
AWARD_EFFECTIVE_DATE=r_awd_upd.AWARD_EFFECTIVE_DATE,
AWARD_EXECUTION_DATE=r_awd_upd.AWARD_EXECUTION_DATE,
BEGIN_DATE=r_awd_upd.BEGIN_DATE,
COST_SHARING_INDICATOR=r_awd_upd.COST_SHARING_INDICATOR,
IDC_INDICATOR=r_awd_upd.IDC_INDICATOR,
MODIFICATION_NUMBER=r_awd_upd.MODIFICATION_NUMBER,
NSF_CODE=r_awd_upd.NSF_CODE,
PAYMENT_SCHEDULE_INDICATOR=r_awd_upd.PAYMENT_SCHEDULE_INDICATOR,
SCIENCE_CODE_INDICATOR=r_awd_upd.SCIENCE_CODE_INDICATOR,
SPECIAL_REVIEW_INDICATOR=r_awd_upd.SPECIAL_REVIEW_INDICATOR,
SPONSOR_AWARD_NUMBER=r_awd_upd.SPONSOR_AWARD_NUMBER,
TRANSFER_SPONSOR_INDICATOR=r_awd_upd.TRANSFER_SPONSOR_INDICATOR,
ACCOUNT_TYPE_CODE=r_awd_upd.ACCOUNT_TYPE_CODE
WHERE AWARD_NUMBER=ls_award_number
AND SEQUENCE_NUMBER=li_orig_seq;


INSERT INTO SYNC_AWARD_LOG(feed_id,execution_date) VALUES(r_awd_upd.feed_id,sysdate);

END LOOP;
CLOSE c_awd_upd;
END;
/
ALTER TABLE AWARD_PERSON_UNITS DISABLE  CONSTRAINT FK_APU_AW_PERSON
/
ALTER TABLE AWARD_PERSON_CREDIT_SPLITS DISABLE CONSTRAINT FK_AP_CREDIT_SPLIT_AP
/
select ' Ended UPDATE_AWARD ' from dual
/