CREATE SEQUENCE  SEQ_SAP_BATCH_ID
MINVALUE 1 
MAXVALUE 999
INCREMENT BY 1 
START WITH 1 
NOCACHE 
NOORDER 
CYCLE
/
CREATE SEQUENCE SEQ_ROLO_FEED_ID
START WITH 1
MAXVALUE 999
INCREMENT BY 1 
MINVALUE 1
CYCLE
NOCACHE
NOORDER
/  
CREATE SEQUENCE SEQ_SAP_ID
START WITH 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER
/   
CREATE SEQUENCE SEQ_SAP_FEED_BATCH_ID
START WITH 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER
/
CREATE SEQUENCE  SEQ_SPON_BATCH_ID  
MINVALUE 1 
MAXVALUE 999 
INCREMENT BY 1 
START WITH 1 
NOCACHE  
NOORDER  
CYCLE
/  
CREATE SEQUENCE  SEQ_SAP_FEED_ERROR_ID
START WITH 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER
/   
CREATE TABLE TEMP_SAP_SPON_CD  (
"SPONSOR_CODE" CHAR(6 BYTE), 
"SPONSOR_NAME" VARCHAR2(60 BYTE), 
"ADMIN_ACTIVITY_CODE" CHAR(2 BYTE),
"UPDATE_TIMESTAMP" DATE, 
"UPDATE_USER" VARCHAR2(60 BYTE), 
"VER_NBR" NUMBER(8,0) DEFAULT 1, 
"OBJ_ID" VARCHAR2(36 BYTE) NOT NULL ENABLE)
/	
CREATE TABLE SAP_FEED
(SAP_FEED_ID NUMBER(12,0) NOT NULL ENABLE,	
SAP_FEED_BATCH_ID NUMBER(12,0),
"BATCH_ID" NUMBER(3,0) NOT NULL ENABLE, 
"FEED_ID" NUMBER(10,0) NOT NULL ENABLE, 
"SAP_TRANSACTION" CHAR(4) NOT NULL ENABLE, 
"WBS_TYPE" CHAR(1) NOT NULL ENABLE, 
"ACCOUNT_LEVEL" CHAR(1) NOT NULL ENABLE, 
"MIT_SAP_ACCOUNT" CHAR(12) NOT NULL ENABLE, 
"DEPTNO" CHAR(7) NOT NULL ENABLE, 
"BILLING_ELEMENT" CHAR(1), 
"BILLING_TYPE" CHAR(2), 
"BILLING_FORM" CHAR(2), 
"SPON_CODE" CHAR(6), 
"PRIMARY_SPONSOR" CHAR(6), 
"CONTRACT" CHAR(70), 
"CUSTOMER" CHAR(10), 
"TERM_CODE" CHAR(1), 
"PARENT_ACCOUNT" CHAR(12) NOT NULL ENABLE, 
"ACCTNAME" CHAR(60), 
"EFFECT_DATE" CHAR(8), 
"EXPIRATION" CHAR(8), 
"SUB_PLAN" CHAR(1), 
"MAIL_CODE" CHAR(1), 
"SUPERVISOR" CHAR(9), 
"SUPER_ROOM" CHAR(10), 
"ADDRESSEE" CHAR(9), 
"ADDR_ROOM" CHAR(10), 
"AGREE_TYPE" CHAR(2), 
"AUTH_TOTAL" CHAR(12), 
"COST_SHARE" CHAR(1), 
"FUND_CLASS" CHAR(3), 
"POOL_CODE" CHAR(1), 
"PENDING_CODE" CHAR(1), 
"FS_CODE" CHAR(1), 
"DFAFS" CHAR(20), 
"CALC_CODE" CHAR(1), 
"CFDANO" CHAR(7), 
"COSTING_SHEET_KEY" CHAR(6), 
"LAB_ALLOCATION_KEY" CHAR(6), 
"EB_ADJUSTMENT_KEY" CHAR(6), 
"OH_ADJUSTMENT_KEY" CHAR(6), 
"COMMENT1" CHAR(60), 
"COMMENT2" CHAR(60), 
"COMMENT3" CHAR(60), 
"TITLE" CHAR(150), 
"SORT_ID" NUMBER(6,0),
"UPDATE_USER" VARCHAR2(8) NOT NULL ENABLE, 
"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
"VER_NBR" NUMBER(8,0) NOT NULL ENABLE, 
"OBJ_ID" VARCHAR2(36) NOT NULL ENABLE,
CONSTRAINT "PK_SAP_FEED" PRIMARY KEY ("SAP_FEED_ID"),
CONSTRAINT "UQ_SAP_FEED" UNIQUE  ("BATCH_ID", "FEED_ID"))
/  
CREATE TABLE SAP_FEED_BATCH_LIST 
(	SAP_FEED_BATCH_ID NUMBER(12,0) NOT NULL ENABLE,
"BATCH_ID" NUMBER(3,0) NOT NULL ENABLE, 
"BATCH_FILE_NAME" CHAR(27) NOT NULL ENABLE, 
"BATCH_TIMESTAMP" DATE NOT NULL ENABLE, 
"UPDATE_USER" VARCHAR2(8) NOT NULL ENABLE, 
"NO_OF_RECORDS" NUMBER(5,0) NOT NULL ENABLE,
"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
"VER_NBR" NUMBER(8,0) NOT NULL ENABLE, 
"OBJ_ID" VARCHAR2(36) NOT NULL ENABLE,
CONSTRAINT "PK_SAP_FEED_BATCH_LIST" PRIMARY KEY ("SAP_FEED_BATCH_ID"))
/	
CREATE TABLE SAP_FEED_ERROR_LOG
(	"SAP_FEED_ERROR_ID"  NUMBER(12,0) NOT NULL ENABLE,
SAP_FEED_BATCH_ID NUMBER(12,0),
"BATCH_ID" NUMBER(3,0) NOT NULL ENABLE, 
"FEED_ID" NUMBER(10,0) NOT NULL ENABLE, 
"ERROR_MESSAGE" VARCHAR2(1000),
"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
"VER_NBR" NUMBER(8,0) NOT NULL ENABLE, 
"OBJ_ID" VARCHAR2(36) NOT NULL ENABLE,
"UPDATE_USER" VARCHAR2(8) NOT NULL ENABLE,
CONSTRAINT "PK_SAP_FEED_ERROR_LOG" PRIMARY KEY ("SAP_FEED_ERROR_ID")
)
/
ALTER TABLE  SAP_FEED_DETAILS ADD SAP_FEED_BATCH_ID NUMBER(12,0)
/
ALTER TABLE SAP_FEED_ERROR_LOG ADD CONSTRAINT FK_SAP_FEED_ERROR_LOG   FOREIGN KEY (SAP_FEED_BATCH_ID)  REFERENCES SAP_FEED_BATCH_LIST(SAP_FEED_BATCH_ID)
/
ALTER TABLE SAP_FEED ADD CONSTRAINT FK_SAP_FEED   FOREIGN KEY (SAP_FEED_BATCH_ID)  REFERENCES SAP_FEED_BATCH_LIST(SAP_FEED_BATCH_ID)
/
ALTER TABLE SAP_FEED_DETAILS ADD CONSTRAINT FK_SAP_FEED_DETAILS   FOREIGN KEY (SAP_FEED_BATCH_ID)  REFERENCES SAP_FEED_BATCH_LIST(SAP_FEED_BATCH_ID)
/
