CREATE TABLE PROPOSAL_ATTACHMENT_TYPE(
ATTACHMENT_TYPE_CODE NUMBER(3,0) NOT NULL ENABLE, 
DESCRIPTION VARCHAR2(200) NOT NULL ENABLE, 
ALLOW_MULTIPLE VARCHAR2(1) NOT NULL ENABLE, 
UPDATE_TIMESTAMP DATE NOT NULL ENABLE, 
UPDATE_USER VARCHAR2(8) NOT NULL ENABLE, 
VER_NBR NUMBER(8,0), 
OBJ_ID VARCHAR2(36), 
CONSTRAINT PK_ATTACHMENT_TYPE_CODE PRIMARY KEY (ATTACHMENT_TYPE_CODE)
)
/
