CREATE TABLE PROPOSAL_ATTACHMENTS_DATA(	
PROPOSAL_ATTACHMENTS_DATA_ID NUMBER(12,0), 
DOCUMENT BLOB, 
FILE_NAME VARCHAR2(2000), 
CONTENT_TYPE VARCHAR2(255), 
VER_NBR NUMBER(8,0), 
OBJ_ID VARCHAR2(36), 
UPDATE_USER VARCHAR2(60) NOT NULL ENABLE, 
UPDATE_TIMESTAMP DATE NOT NULL ENABLE, 
PROPOSAL_NUMBER VARCHAR2(8), 
PROPOSAL_ID NUMBER(12,0), 
SEQUENCE_NUMBER NUMBER(4,0), 
ATTACHMENT_NUMBER NUMBER(2,0), 
CONSTRAINT PK_PROPOSAL_ATTACHMT_DATA PRIMARY KEY (PROPOSAL_ATTACHMENTS_DATA_ID)  
)
/
