CREATE TABLE RCR_APPOINTMENTS
(
  RCR_APPOINT_ID			NUMBER(12)  NOT NULL,
  PERSON_ID                 VARCHAR2(40)     NOT NULL,
  ACCOUNT_NUMBER            VARCHAR2(20)    NOT NULL,
  APPOINTMENT_DATE          DATE,
  APPOINTMENT_TYPE          VARCHAR2(200),
  DATA_LOAD_DATE            DATE,
  UPDATE_TIMESTAMP          DATE                NOT NULL,
  UPDATE_USER               VARCHAR2(60)    NOT NULL,
  VER_NBR	              NUMBER(8,0)  NOT NULL,
  OBJ_ID	              VARCHAR2(36)  NOT NULL,
   CONSTRAINT PK_RCR_APPOINTMENTS   PRIMARY KEY (RCR_APPOINT_ID),
  CONSTRAINT UK_RCR_APPOINTMENTS   UNIQUE (PERSON_ID, ACCOUNT_NUMBER),
  CONSTRAINT FK1_RCR_APPOINTMENTS FOREIGN KEY (PERSON_ID)  REFERENCES KRIM_PRNCPL_T (PRNCPL_ID)
)
/
CREATE SEQUENCE SEQ_RCR_APPOINT_ID
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER; 
CREATE TABLE RCR_PAYROLL_DATES
(
  RCR_PAYROLL_DATES_ID			NUMBER(12)  NOT NULL,	
  PERSON_ID                 VARCHAR2(40)    NOT NULL,
  ACCOUNT_NUMBER            VARCHAR2(20)    NOT NULL,
  PAYROLL_NUMBER            NUMBER(4)       NOT NULL,
  BASE_DATE                 DATE            NOT NULL,
  TRAINING_DEADLINE         DATE            NOT NULL,
  UPDATE_TIMESTAMP          DATE            NOT NULL,
  UPDATE_USER               VARCHAR2(60)    NOT NULL,
  VER_NBR	              	NUMBER(8,0)  	NOT NULL,
  OBJ_ID	              	VARCHAR2(36)  	NOT NULL,
  CONSTRAINT PK_RCR_PAYROLL_DATES   PRIMARY KEY (RCR_PAYROLL_DATES_ID),
    CONSTRAINT UK_RCR_PAYROLL_DATES   UNIQUE (PERSON_ID, ACCOUNT_NUMBER, PAYROLL_NUMBER),
  CONSTRAINT FK1_RCR_PAYROLL_DATES FOREIGN KEY (PERSON_ID, ACCOUNT_NUMBER)  REFERENCES RCR_APPOINTMENTS (PERSON_ID, ACCOUNT_NUMBER) 
)
/
CREATE TABLE RCR_NOTIF_TYPE
(
  RCR_NOTIF_TYPE_CODE       NUMBER(4)       NOT NULL,
  NOTIFICATION_TYPE_ID  	NUMBER(6,0)    NOT NULL,
  DESCRIPTION               VARCHAR2(200)    NOT NULL,
  NO_OF_DAYS_PRIOR          NUMBER(3)       NOT NULL,
  UPDATE_TIMESTAMP          DATE                NOT NULL,
  UPDATE_USER               VARCHAR2(8)    NOT NULL,
  CONSTRAINT PK_RCR_NOTIF_TYPE   PRIMARY KEY (RCR_NOTIF_TYPE_CODE)
  ) 
/
CREATE SEQUENCE SEQ_RCR_PAYROLL_DATES_ID
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER; 
CREATE SEQUENCE SEQ_RCR_NOTIFICATION_ID
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER; 
CREATE TABLE RCR_NOTIFICATIONS
(
  NOTIFICATION_ID           NUMBER(10)       NOT NULL,
  NOTIFICATION_TYPE_CODE      NUMBER(6)       NOT NULL,
  NOTIFICATION_DATE         DATE            NOT NULL,
  NO_OF_DAYS_PRIOR          NUMBER(3)       NOT NULL,
  UPDATE_TIMESTAMP          DATE                NOT NULL,
  UPDATE_USER               VARCHAR2(60)    NOT NULL,
  VER_NBR	              NUMBER(8,0)  NOT NULL,
  OBJ_ID	              VARCHAR2(36)  NOT NULL,
  CONSTRAINT PK_RCR_NOTIFICATIONS  PRIMARY KEY  (NOTIFICATION_ID)
 )
/
CREATE TABLE RCR_NOTIF_DETAILS
(
  NOTIFICATION_ID           NUMBER(10)       NOT NULL,
  PERSON_ID                 VARCHAR2(40)     NOT NULL,
  ACCOUNT_NUMBER            VARCHAR2(20)    NOT NULL,
  TRAINING_DEADLINE         DATE            NOT NULL,
  RECIPIENT_ID              VARCHAR2(40)     NOT NULL,
  RECIPIENT_ROLE            VARCHAR2(50)    NOT NULL,
  RECIPIENT_EMAIL           VARCHAR2(60)    NOT NULL,
  UNIT_NUMBER               VARCHAR2(8)     NULL,
  MAIL_SENT_STATUS				CHAR(1),
  UPDATE_TIMESTAMP          DATE                NOT NULL,
  UPDATE_USER               VARCHAR2(60)    NOT NULL,
  VER_NBR	              NUMBER(8,0)  NOT NULL,
  OBJ_ID	              VARCHAR2(36)  NOT NULL,
  CONSTRAINT PK_RCR_NOTIF_DETAILS   PRIMARY KEY (NOTIFICATION_ID, PERSON_ID, ACCOUNT_NUMBER, RECIPIENT_ROLE, RECIPIENT_ID ),
 CONSTRAINT FK1_RCR_NOTIF_DETAILS FOREIGN KEY (NOTIFICATION_ID)  REFERENCES RCR_NOTIFICATIONS(NOTIFICATION_ID) 
 )
/
ALTER TABLE RCR_NOTIF_TYPE ADD  CONSTRAINT FK_RCR_NOTIF_TYPE_1 FOREIGN KEY (NOTIFICATION_TYPE_ID)  REFERENCES NOTIFICATION_TYPE(NOTIFICATION_TYPE_ID)
/
CREATE TABLE RCR_PAYROLL_DATES_DROPPED 
(	PERSON_ID VARCHAR2(9) NOT NULL, 
ACCOUNT_NUMBER VARCHAR2(20) NOT NULL, 
PAYROLL_NUMBER NUMBER(4,0) NOT NULL, 
BASE_DATE DATE NOT NULL, 
TRAINING_DEADLINE DATE NOT NULL, 
UPDATE_TIMESTAMP DATE NOT NULL, 
UPDATE_USER VARCHAR2(8) NOT NULL, 
DROPPED_DATE DATE NOT NULL
)
/
CREATE TABLE RCR_PAYROLL_WH 
(	PERSON_ID VARCHAR2(9) NOT NULL, 
ACCOUNT_NUMBER VARCHAR2(20) NOT NULL, 
PAYROLL_PAYMENT_DATE DATE
)
/
CREATE TABLE RCR_APPOINT_WH 
(	PERSON_ID VARCHAR2(9) NOT NULL, 
ACCOUNT_NUMBER VARCHAR2(20) NOT NULL, 
APPOINTMENT_DATE DATE, 
APPOINTMENT_TYPE VARCHAR2(200)
)
/
CREATE TABLE RCR_APPOINTMENTS_DROPPED 
(	PERSON_ID VARCHAR2(9) NOT NULL, 
ACCOUNT_NUMBER VARCHAR2(20) NOT NULL, 
APPOINTMENT_DATE DATE, 
APPOINTMENT_TYPE VARCHAR2(200), 
DATA_LOAD_DATE DATE, 
UPDATE_TIMESTAMP DATE NOT NULL, 
UPDATE_USER VARCHAR2(8) NOT NULL, 
DROPPED_DATE DATE NOT NULL
)
/
CREATE TABLE TRAINING_MODULES 
(	
TRAINING_MODULES_ID NUMBER(8,0),
TRAINING_CODE NUMBER(4,0) , 
MODULE_CODE NUMBER(3,0) NOT NULL ENABLE, 
SUB_MODULE_CODE NUMBER(3,0), 
DESCRIPTION VARCHAR2(200) NOT NULL ENABLE, 
UPDATE_TIMESTAMP DATE NOT NULL ENABLE, 
UPDATE_USER VARCHAR2(60) NOT NULL ENABLE,
VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL ENABLE, 
OBJ_ID VARCHAR2(36) NOT NULL ENABLE
)
/
CREATE SEQUENCE SEQ_TRAINING_MODULES_ID
START WITH 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER
/