  CREATE TABLE RCR_PAYROLL_DATES_DROPPED 
   (	PERSON_ID VARCHAR2(9) NOT NULL, 
	ACCOUNT_NUMBER VARCHAR2(20) NOT NULL, 
	PAYROLL_NUMBER NUMBER(4,0) NOT NULL, 
	BASE_DATE DATE NOT NULL, 
	TRAINING_DEADLINE DATE NOT NULL, 
	UPDATE_TIMESTAMP DATE NOT NULL, 
	UPDATE_USER VARCHAR2(8) NOT NULL, 
	DROPPED_DATE DATE NOT NULL
   )
/
CREATE TABLE RCR_PAYROLL_WH 
   (	PERSON_ID VARCHAR2(9) NOT NULL, 
	ACCOUNT_NUMBER VARCHAR2(20) NOT NULL, 
	PAYROLL_PAYMENT_DATE DATE
   )
/
CREATE TABLE RCR_APPOINT_WH 
   (	PERSON_ID VARCHAR2(9) NOT NULL, 
	ACCOUNT_NUMBER VARCHAR2(20) NOT NULL, 
	APPOINTMENT_DATE DATE, 
	APPOINTMENT_TYPE VARCHAR2(200)
   )
/
CREATE TABLE RCR_APPOINTMENTS_DROPPED 
   (	PERSON_ID VARCHAR2(9) NOT NULL, 
	ACCOUNT_NUMBER VARCHAR2(20) NOT NULL, 
	APPOINTMENT_DATE DATE, 
	APPOINTMENT_TYPE VARCHAR2(200), 
	DATA_LOAD_DATE DATE, 
	UPDATE_TIMESTAMP DATE NOT NULL, 
	UPDATE_USER VARCHAR2(8) NOT NULL, 
	DROPPED_DATE DATE NOT NULL
   )
/
