Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_AWARD',SYS_GUID(),1,'CONFG','1','Module Code for Award Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_INSTITUTIONAL_PROPOSAL',SYS_GUID(),1,'CONFG','2','Module Code for Institute Proposal Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_PROPOSAL_DEVELOPMENT',SYS_GUID(),1,'CONFG','3','Module Code For Proposal development Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_SUBCONTRACTS',SYS_GUID(),1,'CONFG','4','Module Code For Subcontarcts Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_NEGOTIATIONS',SYS_GUID(),1,'CONFG','5','Module Code For Negotiation Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_PERSON',SYS_GUID(),1,'CONFG','6','Module Code For Person Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_IRB',SYS_GUID(),1,'CONFG','7','Module Code For IRB Protocol Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_COI_DISCLOSURE',SYS_GUID(),1,'CONFG','8','Module Code For Coi Disclosure Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_IACUC_PROTOCOL',SYS_GUID(),1,'CONFG','9','Module Code For IACUC Protocol Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_COMMITTEE',SYS_GUID(),1,'CONFG','11','Module Code For Committee Module','A','KC')
/

Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_AWARD_INT',SYS_GUID(),1,'CONFG','1','Module Code Int for Award Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_INT_INSTITUTIONAL_PROPOSAL',SYS_GUID(),1,'CONFG','2','Module Code Int for Institute Proposal Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_INT_PROPOSAL_DEVELOPMENT',SYS_GUID(),1,'CONFG','3','Module Code Int For Proposal development Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_INT_SUBCONTRACTS',SYS_GUID(),1,'CONFG','4','Module Code Int For Subcontarcts Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_INT_NEGOTIATIONS',SYS_GUID(),1,'CONFG','5','Module Code Int For Negotiation Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_INT_PERSON',SYS_GUID(),1,'CONFG','6','Module Code Int For Person Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_INT_IRB',SYS_GUID(),1,'CONFG','7','Module Code Int For IRB Protocol Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_INT_COI_DISCLOSURE',SYS_GUID(),1,'CONFG','8','Module Code Int For Coi Disclosure Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_INT_IACUC_PROTOCOL',SYS_GUID(),1,'CONFG','9','Module Code Int For IACUC Protocol Module','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','All','KC_MODULE_INT_COMMITTEE',SYS_GUID(),1,'CONFG','11','Module Code Int For Committee Module','A','KC')
/
