CREATE SEQUENCE SEQ_EVERIFY_NOTIFICATION_ID
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
CREATE SEQUENCE SEQ_EVERIFY_NOTIF_DETAILS_ID
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
CREATE TABLE EVERIFY_NOTIFICATIONS
(
  NOTIFICATION_ID           NUMBER(10)       NOT NULL,
  NOTIFICATION_DATE         DATE            NOT NULL,
  UPDATE_TIMESTAMP          DATE                NOT NULL,
  UPDATE_USER               VARCHAR2(60)    NOT NULL,
  VER_NBR	              NUMBER(8,0)  NOT NULL,
  OBJ_ID	              VARCHAR2(36)  NOT NULL,
  CONSTRAINT PK_EVERIFY_NOTIFICATIONS
   PRIMARY KEY  (NOTIFICATION_ID)
 )
/
CREATE TABLE EVERIFY_NOTIF_DETAILS
(
  NOTIF_DETAILS_ID			 NUMBER(10)       NOT NULL,
  NOTIFICATION_ID           NUMBER(10)       NOT NULL,
  AWARD_NUMBER          VARCHAR2(12)     NOT NULL,
  SEQUENCE_NUMBER           NUMBER(4)        NOT NULL,
  RECIPIENT_ID              VARCHAR2(40)     NOT NULL,
  RECIPIENT_ROLE            VARCHAR2(50)    NOT NULL,
  RECIPIENT_EMAIL           VARCHAR2(60)    NOT NULL,
  UNIT_NUMBER               VARCHAR2(8)     NULL,
  MAIL_SENT_STATUS          CHAR(1),
  UPDATE_TIMESTAMP          DATE                NOT NULL,
  UPDATE_USER               VARCHAR2(60)    NOT NULL,
  VER_NBR	              NUMBER(8,0)  NOT NULL,
  OBJ_ID	              VARCHAR2(36)  NOT NULL,
  CONSTRAINT PK_EVERIFY_NOTIF_DETAILS   PRIMARY KEY (NOTIF_DETAILS_ID ), 
  CONSTRAINT UK_EVERIFY_NOTIF_DETAILS   UNIQUE (NOTIFICATION_ID, AWARD_NUMBER, RECIPIENT_ROLE, RECIPIENT_ID ), 
  CONSTRAINT FK1_EVERIFY_NOTIF_DETAILS FOREIGN KEY (NOTIFICATION_ID)  REFERENCES EVERIFY_NOTIFICATIONS (NOTIFICATION_ID) 
 )
/