declare
li_count number;
begin

select count(*) into li_count from user_tables where table_name='TEMP_QUESTIONNAIRE';
if li_count>0 then
execute immediate('drop table TEMP_QUESTIONNAIRE');
end if;

select count(*) into li_count from user_tables where table_name='TEMP_QUESTION_EXPLANATION';
if li_count>0 then
execute immediate('drop table TEMP_QUESTION_EXPLANATION');
end if;
end;
/
ALTER TABLE QUESTIONNAIRE_ANSWER ENABLE CONSTRAINT FK_QUESTIONNAIRE_ANS_COMP_ID;
/
ALTER TABLE QUESTIONNAIRE_USAGE ENABLE CONSTRAINT FK_QUESTIONNAIRE_USAGE;
/
ALTER TABLE QUESTIONNAIRE_ANSWER_HEADER ENABLE CONSTRAINT FK_QUESTIONNAIRE_QID;
/
ALTER TABLE QUESTIONNAIRE_QUESTIONS ENABLE CONSTRAINT FK_QUESTIONNAIRE_QUESTIONNAIRE;
/
ALTER TABLE QUESTION_EXPLANATION ENABLE CONSTRAINT FK_QUESTION_EXPLANATION;
/
ALTER TABLE QUESTIONNAIRE_ANSWER ENABLE CONSTRAINT FK_QUESTIONNAIRE_ANS_QID;
/
ALTER TABLE QUESTIONNAIRE_QUESTIONS ENABLE CONSTRAINT FK_QUESTIONNAIRE_QUESTIONS;
/