  CREATE TABLE "TEMP_QUESTIONNAIRE" 
   (	"QUESTIONNAIRE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"IS_FINAL" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(1000 BYTE), 
	"TEMPLATE" CLOB, 
	"VERSION_NUMBER" NUMBER(3,0) NOT NULL ENABLE, 
	"GROUP_TYPE_CODE" NUMBER(3,0));
	commit;
	insert into TEMP_QUESTIONNAIRE(QUESTIONNAIRE_ID,VERSION_NUMBER,NAME,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_FINAL,FILE_NAME,TEMPLATE,GROUP_TYPE_CODE)
	select  QUESTIONNAIRE_ID,VERSION_NUMBER,NAME,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_FINAL,FILE_NAME,TEMPLATE,GROUP_TYPE_CODE from  OSP$QUESTIONNAIRE@coeus.kuali;
	commit;

  CREATE TABLE "TEMP_QUESTION_EXPLANATION" 
   (	"QUESTION_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"EXPLANATION_TYPE" CHAR(1 BYTE) NOT NULL ENABLE, 
	"EXPLANATION" CLOB, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(8 BYTE) NOT NULL ENABLE);
	commit;
	insert into TEMP_QUESTION_EXPLANATION(QUESTION_ID,EXPLANATION_TYPE,EXPLANATION,UPDATE_TIMESTAMP,UPDATE_USER)
	select  QUESTION_ID,EXPLANATION_TYPE,EXPLANATION,UPDATE_TIMESTAMP,UPDATE_USER from OSP$QUESTION_EXPLANATION@coeus.kuali;
	commit;
/*
declare
li_count number;
begin
select count(*) into li_count from user_tables where table_name='TEMP_QUESTIONNAIRE';
if li_count=0 then
execute immediate('create table TEMP_QUESTIONNAIRE as select  * from  OSP$QUESTIONNAIRE@coeus.kuali');
else
execute immediate('drop table TEMP_QUESTIONNAIRE');
execute immediate('create table TEMP_QUESTIONNAIRE as select  * from  OSP$QUESTIONNAIRE@coeus.kuali');
end if;

select count(*) into li_count from user_tables where table_name='TEMP_QUESTION_EXPLANATION';
if li_count=0 then
execute immediate('create table TEMP_QUESTION_EXPLANATION as select  * from  OSP$QUESTION_EXPLANATION@coeus.kuali');
else
execute immediate('drop table TEMP_QUESTION_EXPLANATION');
execute immediate('create table TEMP_QUESTION_EXPLANATION as select  * from  OSP$QUESTION_EXPLANATION@coeus.kuali');
end if;
end;
*/
/
ALTER TABLE QUESTIONNAIRE_QUESTIONS DISABLE CONSTRAINT FK_QUESTIONNAIRE_QUESTIONS;
/
ALTER TABLE QUESTIONNAIRE_ANSWER DISABLE CONSTRAINT FK_QUESTIONNAIRE_ANS_QID;
/
ALTER TABLE QUESTION_EXPLANATION DISABLE CONSTRAINT FK_QUESTION_EXPLANATION;
/
ALTER TABLE QUESTIONNAIRE_QUESTIONS DISABLE CONSTRAINT FK_QUESTIONNAIRE_QUESTIONNAIRE;
/
ALTER TABLE QUESTIONNAIRE_ANSWER_HEADER DISABLE CONSTRAINT FK_QUESTIONNAIRE_QID;
/
ALTER TABLE QUESTIONNAIRE_USAGE DISABLE CONSTRAINT FK_QUESTIONNAIRE_USAGE;
/
ALTER TABLE QUESTIONNAIRE_ANSWER DISABLE CONSTRAINT FK_QUESTIONNAIRE_ANS_COMP_ID;
/
TRUNCATE TABLE QUESTION_EXPLANATION;
/
TRUNCATE TABLE QUESTIONNAIRE_QUESTIONS;
/
TRUNCATE TABLE QUESTIONNAIRE_ANSWER;
/
TRUNCATE TABLE QUESTIONNAIRE_ANSWER_HEADER;
/
TRUNCATE TABLE QUESTIONNAIRE_USAGE;
/
TRUNCATE TABLE QUESTIONNAIRE;
/
TRUNCATE TABLE QUESTION;
/