set serveroutput on
/
declare
li_count number;
li_count_coeus number;
begin
  select  count(table_name) into li_count  from user_tables  
  where table_name = 'OSP$PERSON';
  
  select  count(table_name) into li_count_coeus  from user_tables  
  where table_name = 'OSP$PERSON_COEUS_COPY';
  
  if li_count <> 0 and li_count_coeus = 0 then
  
	execute immediate('ALTER TABLE OSP$PERSON RENAME TO OSP$PERSON_COEUS_COPY');
	li_count := 0;
   
  end if; 
   
  if li_count = 0 then 
   execute immediate('
		 CREATE TABLE OSP$PERSON 
   (	PERSON_ID VARCHAR2(40) NOT NULL ENABLE, 
	SSN VARCHAR2(9), 
	LAST_NAME VARCHAR2(80), 
	FIRST_NAME VARCHAR2(40), 
	MIDDLE_NAME VARCHAR2(40), 
	FULL_NAME VARCHAR2(90), 
	PRIOR_NAME VARCHAR2(30), 
	USER_NAME VARCHAR2(100), 
	EMAIL_ADDRESS VARCHAR2(60), 
	DATE_OF_BIRTH DATE, 
	AGE NUMBER(3,0), 
	AGE_BY_FISCAL_YEAR NUMBER(3,0), 
	GENDER VARCHAR2(30), 
	RACE VARCHAR2(30), 
	EDUCATION_LEVEL VARCHAR2(30), 
	DEGREE VARCHAR2(11), 
	MAJOR VARCHAR2(30), 
	IS_HANDICAPPED CHAR(1), 
	HANDICAP_TYPE VARCHAR2(30), 
	IS_VETERAN CHAR(1), 
	VETERAN_TYPE VARCHAR2(30), 
	VISA_CODE VARCHAR2(20), 
	VISA_TYPE VARCHAR2(30), 
	VISA_RENEWAL_DATE DATE, 
	HAS_VISA CHAR(1), 
	OFFICE_LOCATION VARCHAR2(30), 
	OFFICE_PHONE VARCHAR2(20), 
	SECONDRY_OFFICE_LOCATION VARCHAR2(30), 
	SECONDRY_OFFICE_PHONE VARCHAR2(20), 
	SCHOOL VARCHAR2(50), 
	YEAR_GRADUATED VARCHAR2(30), 
	DIRECTORY_DEPARTMENT VARCHAR2(30), 
	SALUTATION VARCHAR2(30), 
	COUNTRY_OF_CITIZENSHIP VARCHAR2(30), 
	PRIMARY_TITLE VARCHAR2(51), 
	DIRECTORY_TITLE VARCHAR2(50), 
	HOME_UNIT VARCHAR2(8), 
	IS_FACULTY CHAR(1), 
	IS_GRADUATE_STUDENT_STAFF CHAR(1), 
	IS_RESEARCH_STAFF CHAR(1), 
	IS_SERVICE_STAFF CHAR(1), 
	IS_SUPPORT_STAFF CHAR(1), 
	IS_OTHER_ACCADEMIC_GROUP CHAR(1), 
	IS_MEDICAL_STAFF CHAR(1), 
	VACATION_ACCURAL CHAR(1), 
	IS_ON_SABBATICAL CHAR(1), 
	ID_PROVIDED VARCHAR2(30), 
	ID_VERIFIED VARCHAR2(30), 
	UPDATE_TIMESTAMP DATE , 
	UPDATE_USER VARCHAR2(8), 
	ADDRESS_LINE_1 VARCHAR2(80), 
	ADDRESS_LINE_2 VARCHAR2(80), 
	ADDRESS_LINE_3 VARCHAR2(80), 
	CITY VARCHAR2(30), 
	COUNTY VARCHAR2(30), 
	STATE VARCHAR2(30), 
	POSTAL_CODE VARCHAR2(15), 
	COUNTRY_CODE CHAR(3), 
	FAX_NUMBER VARCHAR2(20), 
	PAGER_NUMBER VARCHAR2(20), 
	MOBILE_PHONE_NUMBER VARCHAR2(20), 
	ERA_COMMONS_USER_NAME VARCHAR2(20), 
	STATUS VARCHAR2(1), 
	SALARY_ANNIVERSARY_DATE DATE
		)');  
  end if;
end;
/
TRUNCATE TABLE OSP$PERSON
/
DECLARE
	ls_is_fclty CHAR(1);
	ls_med_staff CHAR(1);
	ls_oth_acad CHAR(1);
	ls_support_staff CHAR(1);
	ls_srvc_staff CHAR(1);
	ls_research_staff CHAR(1);
	ls_grd_stdnt_staff CHAR(1);
	ls_phone_number VARCHAR2(20);
	ls_emp_stat VARCHAR2(1);
	ls_secondary_number VARCHAR2(20);
	ls_fax_number VARCHAR2(20);
	ls_pgr_number VARCHAR2(20);
	ls_mobile_number VARCHAR2(20);
	li_count number(10);
CURSOR c_person IS
SELECT p.PRNCPL_ID,p.PRNCPL_NM,p.ENTITY_ID,n.FIRST_NM,n.MIDDLE_NM,n.LAST_NM,(n.LAST_NM||','||n.FIRST_NM||' '||n.MIDDLE_NM) FULL_NAME,e.EMAIL_ADDR,b.BIRTH_DT,
pe.AGE_BY_FISCAL_YEAR,pe.RACE,pe.EDUCATION_LEVEL,pe.DEGREE,pe.MAJOR,pe.IS_HANDICAPPED,pe.HANDICAP_TYPE,pe.IS_VETERAN,pe.VETERAN_TYPE,pe.VISA_CODE,
pe.VISA_TYPE,pe.VISA_RENEWAL_DATE,pe.HAS_VISA,pe.OFFICE_LOCATION,pe.SECONDRY_OFFICE_LOCATION,pe.SCHOOL,pe.YEAR_GRADUATED,pe.DIRECTORY_DEPARTMENT,pe.PRIMARY_TITLE,
pe.DIRECTORY_TITLE,em.PRMRY_DEPT_CD,em.EMP_STAT_CD,pe.VACATION_ACCURAL,pe.IS_ON_SABBATICAL,pe.ID_PROVIDED,pe.ID_VERIFIED,NVL(pe.UPDATE_TIMESTAMP,sysdate)UPDATE_TIMESTAMP,NVL(pe.UPDATE_USER,'admin') UPDATE_USER,pe.COUNTY, 
ea.ADDR_LINE_1,ea.ADDR_LINE_2,ea.ADDR_LINE_3,ea.CITY,ea.STATE_PVC_CD,ea.POSTAL_CD,ea.POSTAL_CNTRY_CD,pe.ERA_COMMON_USER_NAME,pe.SALARY_ANNIVERSARY_DATE FROM KRIM_PRNCPL_T p 
INNER JOIN KRIM_ENTITY_NM_T n ON p.ENTITY_ID=n.ENTITY_ID 
LEFT OUTER JOIN KRIM_ENTITY_EMAIL_T e ON p.ENTITY_ID=e.ENTITY_ID
LEFT OUTER JOIN KRIM_ENTITY_BIO_T b ON p.ENTITY_ID=b.ENTITY_ID
LEFT OUTER JOIN PERSON_EXT_T pe ON p.PRNCPL_ID=pe.PERSON_ID
LEFT OUTER JOIN KRIM_ENTITY_EMP_INFO_T em ON p.ENTITY_ID=em.ENTITY_ID
LEFT OUTER JOIN KRIM_ENTITY_ADDR_T ea ON p.ENTITY_ID=ea.ENTITY_ID;
r_person c_person%ROWTYPE;

BEGIN
IF c_person%ISOPEN THEN
CLOSE c_person;
END IF;
OPEN c_person;
LOOP
FETCH c_person INTO r_person;
EXIT WHEN c_person%NOTFOUND;

        BEGIN
       SELECT PHONE_NBR INTO ls_fax_number FROM KRIM_ENTITY_PHONE_T WHERE ENTITY_ID=r_person.ENTITY_ID AND PHONE_TYP_CD='FAX';
       EXCEPTION
       WHEN OTHERS THEN
       ls_fax_number:=null;
       END;
       BEGIN
	    SELECT PHONE_NBR INTO ls_pgr_number FROM KRIM_ENTITY_PHONE_T WHERE ENTITY_ID=r_person.ENTITY_ID AND PHONE_TYP_CD='PGR';
      EXCEPTION
       WHEN OTHERS THEN
       ls_pgr_number:=null;
       END;
      BEGIN 
	   SELECT PHONE_NBR INTO ls_mobile_number FROM KRIM_ENTITY_PHONE_T WHERE ENTITY_ID=r_person.ENTITY_ID AND PHONE_TYP_CD='MBL';
     EXCEPTION
       WHEN OTHERS THEN
       ls_mobile_number:=null;
       END;
       BEGIN 
	   SELECT PHONE_NBR INTO ls_secondary_number FROM KRIM_ENTITY_PHONE_T WHERE ENTITY_ID=r_person.ENTITY_ID AND PHONE_TYP_CD='WRK';
	    EXCEPTION
       WHEN OTHERS THEN
       ls_mobile_number:=null;
       END;
	   
       ls_med_staff:='N';
       ls_oth_acad:='N'; 
       ls_support_staff:='N';
       ls_srvc_staff:='N';
       ls_research_staff:='N';
       ls_grd_stdnt_staff:='N';
	   
	   SELECT count(AFLTN_TYP_CD) INTO li_count FROM KRIM_ENTITY_AFLTN_T WHERE ENTITY_ID=r_person.ENTITY_ID AND AFLTN_TYP_CD='FCLTY';
	   
	   IF li_count=1 THEN
	      ls_is_fclty:='Y';
		END IF;  
		
       SELECT count(AFLTN_TYP_CD) INTO li_count FROM KRIM_ENTITY_AFLTN_T WHERE ENTITY_ID=r_person.ENTITY_ID AND AFLTN_TYP_CD='STAFF';

        IF li_count=1 THEN
	      ls_is_fclty:='N';
		END IF;	 

       SELECT count(AFLTN_TYP_CD) INTO li_count FROM KRIM_ENTITY_AFLTN_T WHERE ENTITY_ID=r_person.ENTITY_ID AND AFLTN_TYP_CD='MED_STAFF';

        IF li_count=1 THEN
	      ls_med_staff:='Y';
		END IF;	

        SELECT count(AFLTN_TYP_CD) INTO li_count FROM KRIM_ENTITY_AFLTN_T WHERE ENTITY_ID=r_person.ENTITY_ID AND AFLTN_TYP_CD='OTH_ACADMC_GRP';

        IF li_count=1 THEN
	      ls_oth_acad:='Y';
		END IF;

        SELECT count(AFLTN_TYP_CD) INTO li_count FROM KRIM_ENTITY_AFLTN_T WHERE ENTITY_ID=r_person.ENTITY_ID AND AFLTN_TYP_CD='SUPPRT_STAFF';

        IF li_count=1 THEN
	      ls_support_staff:='Y';
		END IF;	

        SELECT count(AFLTN_TYP_CD) INTO li_count FROM KRIM_ENTITY_AFLTN_T WHERE ENTITY_ID=r_person.ENTITY_ID AND AFLTN_TYP_CD='SRVC_STAFF';

        IF li_count=1 THEN
	      ls_srvc_staff:='Y';
		END IF;	

        SELECT count(AFLTN_TYP_CD) INTO li_count FROM KRIM_ENTITY_AFLTN_T WHERE ENTITY_ID=r_person.ENTITY_ID AND AFLTN_TYP_CD='RSRCH_STAFF';

        IF li_count=1 THEN
	      ls_research_staff:='Y'; 
		END IF;					
       
        SELECT count(AFLTN_TYP_CD) INTO li_count FROM KRIM_ENTITY_AFLTN_T WHERE ENTITY_ID=r_person.ENTITY_ID AND AFLTN_TYP_CD='GRD_STDNT_STAFF';

        IF li_count=1 THEN
	      ls_grd_stdnt_staff:='Y'; 
		END IF;	
       
       
       BEGIN
	   
		   INSERT INTO OSP$PERSON(PERSON_ID,SSN,LAST_NAME,FIRST_NAME,MIDDLE_NAME,FULL_NAME,PRIOR_NAME,USER_NAME,EMAIL_ADDRESS,DATE_OF_BIRTH,AGE,AGE_BY_FISCAL_YEAR,GENDER,RACE,EDUCATION_LEVEL,DEGREE,MAJOR,IS_HANDICAPPED,HANDICAP_TYPE,IS_VETERAN,VETERAN_TYPE,VISA_CODE,VISA_TYPE,VISA_RENEWAL_DATE,HAS_VISA,OFFICE_LOCATION,OFFICE_PHONE,SECONDRY_OFFICE_LOCATION,SECONDRY_OFFICE_PHONE,SCHOOL,YEAR_GRADUATED,DIRECTORY_DEPARTMENT,SALUTATION,COUNTRY_OF_CITIZENSHIP,PRIMARY_TITLE,DIRECTORY_TITLE,HOME_UNIT,IS_FACULTY,IS_GRADUATE_STUDENT_STAFF,IS_RESEARCH_STAFF,IS_SERVICE_STAFF,IS_SUPPORT_STAFF,IS_OTHER_ACCADEMIC_GROUP,IS_MEDICAL_STAFF,VACATION_ACCURAL,IS_ON_SABBATICAL,ID_PROVIDED,ID_VERIFIED,UPDATE_TIMESTAMP,UPDATE_USER,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,CITY,COUNTY,STATE,POSTAL_CODE,COUNTRY_CODE,FAX_NUMBER,PAGER_NUMBER,MOBILE_PHONE_NUMBER,ERA_COMMONS_USER_NAME,STATUS,SALARY_ANNIVERSARY_DATE)
		   VALUES(r_person.PRNCPL_ID,null,r_person.LAST_NM,r_person.FIRST_NM,r_person.MIDDLE_NM,r_person.FULL_NAME,null,r_person.PRNCPL_NM,r_person.EMAIL_ADDR,r_person.BIRTH_DT,null,r_person.AGE_BY_FISCAL_YEAR,null,r_person.RACE,r_person.EDUCATION_LEVEL,r_person.DEGREE,r_person.MAJOR,r_person.IS_HANDICAPPED,r_person.HANDICAP_TYPE,r_person.IS_VETERAN,r_person.VETERAN_TYPE,r_person.VISA_CODE,r_person.VISA_TYPE,r_person.VISA_RENEWAL_DATE,r_person.HAS_VISA,r_person.OFFICE_LOCATION,ls_secondary_number,r_person.SECONDRY_OFFICE_LOCATION,ls_secondary_number,r_person.SCHOOL,r_person.YEAR_GRADUATED,r_person.DIRECTORY_DEPARTMENT,null,null,r_person.PRIMARY_TITLE,r_person.DIRECTORY_TITLE,r_person.PRMRY_DEPT_CD,ls_is_fclty,ls_grd_stdnt_staff,ls_research_staff,ls_srvc_staff,ls_support_staff,ls_oth_acad,ls_med_staff,r_person.VACATION_ACCURAL,r_person.IS_ON_SABBATICAL,r_person.ID_PROVIDED,r_person.ID_VERIFIED,r_person.UPDATE_TIMESTAMP,r_person.UPDATE_USER,r_person.ADDR_LINE_1,r_person.ADDR_LINE_2,r_person.ADDR_LINE_3,r_person.CITY,r_person.COUNTY,r_person.STATE_PVC_CD,r_person.POSTAL_CD,r_person.POSTAL_CNTRY_CD,ls_fax_number,ls_pgr_number,ls_mobile_number,r_person.ERA_COMMON_USER_NAME,r_person.EMP_STAT_CD,r_person.SALARY_ANNIVERSARY_DATE);
	   
       EXCEPTION
       WHEN OTHERS THEN
       dbms_output.put_line('PERSON_ID:'||r_person.PRNCPL_ID||' and error is'||sqlerrm);
	   END;

END LOOP;
CLOSE c_person;
END;
/
