UPDATE KRCR_PARM_T SET VAL = 'outgoing.mit.edu' WHERE PARM_NM = 'KC_DB_MAIL_HOST' AND NMSPC_CD = 'KC-GEN'
/
UPDATE KRCR_PARM_T SET VAL = '25' WHERE PARM_NM = 'KC_DB_MAIL_PORT' AND NMSPC_CD = 'KC-GEN'
/
UPDATE KRCR_PARM_T SET VAL = 'kc-notifications@mit.edu' WHERE PARM_NM = 'KC_DB_SENDER_ID' AND NMSPC_CD = 'KC-GEN'
/
UPDATE KRCR_PARM_T SET VAL = 'kc-notifications@mit.edu'WHERE PARM_NM = 'KC_DB_REPLY_ID' AND NMSPC_CD = 'KC-GEN'
/
UPDATE KRCR_PARM_T SET VAL = 'kc-notifications@mit.edu' WHERE PARM_NM = 'EMAIL_NOTIFICATION_FROM_ADDRESS' AND NMSPC_CD='KC-GEN'
/
UPDATE KRCR_PARM_T SET VAL = 'kc-notifications@mit.edu' WHERE PARM_NM = 'EMAIL_NOTIFICATION_TEST_ADDRESS' AND NMSPC_CD='KC-GEN'
/
UPDATE KRCR_PARM_T SET VAL = 'kc-notifications@mit.edu' WHERE PARM_NM = 'EMAIL_NOTIFICATION_TEST_ADDRESS' AND NMSPC_CD='KR-WKFLW'
/
UPDATE KRCR_PARM_T SET VAL = 'kc-notifications@mit.edu' WHERE PARM_NM = 'FROM_ADDRESS' AND NMSPC_CD='KR-WKFLW'
/
UPDATE KRCR_PARM_T SET VAL = 'kc-notifications@mit.edu' WHERE PARM_NM = 'LOOKUP_CONTACT_EMAIL' AND NMSPC_CD='KC-GEN'
/
UPDATE KRCR_PARM_T SET VAL = 'Y' WHERE PARM_NM = 'EMAIL_NOTIFICATIONS_ENABLED' AND NMSPC_CD='KC-GEN'
/
UPDATE KRCR_PARM_T SET VAL = 'Y' WHERE PARM_NM = 'EMAIL_NOTIFICATIONS_TEST_ENABLED' AND NMSPC_CD='KC-GEN'
/
UPDATE KRCR_PARM_T SET VAL = '0 */10 * * * ?' WHERE PARM_NM = 'REPORT_TRACKING_NOTIFICATIONS_BATCH_CRON_TRIGGER'
/
UPDATE KRCR_PARM_T SET VAL = '0 0 7,19 * * ?' WHERE PARM_NM = 'CITI_TRAINING_DATA_FEED_CRON_TRIGGER'
/
UPDATE KRCR_PARM_T SET VAL = 'Y' WHERE PARM_NM = 'ENABLE_CITI_TRAINING_DATA_FEED'
/
UPDATE KRCR_PARM_T SET VAL = 'Y' WHERE PARM_NM = 'SEND_EMAIL_NOTIFICATION_IND'
/
UPDATE KRCR_PARM_T SET VAL = 'COEUS.KUALI',PARM_DESC_TXT =  'DB Link to connect with Coeus DB to get the COI Functions' WHERE NMSPC_CD = 'KC-GEN' AND PARM_NM = 'KC_COI_DB_LINK'
/
UPDATE KRCR_PARM_T SET VAL ='1' WHERE  PARM_NM='ENABLE_AWARD_HUMAN_REVIEW_VALID'
/
UPDATE KRCR_PARM_T SET VAL ='1' WHERE  PARM_NM='ENABLE_AWARD_DNA_REVIEW_VALID'
/
UPDATE KRCR_PARM_T SET VAL ='1' WHERE  PARM_NM='ENABLE_AWARD_ISOTOPE_REVIEW_VALID'
/
UPDATE KRCR_PARM_T SET VAL ='1' WHERE  PARM_NM='ENABLE_AWARD_INTER_REVIEW_VALID'
/
UPDATE KRCR_PARM_T SET VAL ='N' WHERE  PARM_NM='AWARD_ON_HOLD_BASED_ON_COI'
/
UPDATE KRCR_PARM_T SET VAL ='N' WHERE  PARM_NM='ENABLE_AWARD_NSF_RCR_REVIEW_VALID'
/
UPDATE KRCR_PARM_T SET VAL ='Y' WHERE  PARM_NM='ENABLE_AWARD_REPORT_VALIDATION'
/
UPDATE KRCR_PARM_T SET VAL ='Y' WHERE  PARM_NM='ENABLE_AWARD_VALIDATIONS'
/
UPDATE KRCR_PARM_T SET VAL ='2' WHERE  PARM_NM='IACUC_SPL_REV_TYPE_CODE'
/
UPDATE KRCR_PARM_T SET VAL ='1' WHERE  PARM_NM='SPL_REV_TYPE_CODE_HUMAN'
/
UPDATE KRCR_PARM_T SET VAL = 'Y' WHERE  PARM_NM='disableAttachmentRemoval' AND NMSPC_CD='KC-GEN'
/
UPDATE KRCR_PARM_T SET VAL = 'Y' WHERE  PARM_NM='ENABLE_SEP_LINK' AND NMSPC_CD='KC-GEN'
/
UPDATE KRCR_PARM_T SET VAL = '1' WHERE  PARM_NM= 'ENABLE_ANIMAL_REVIEW_VALID' AND NMSPC_CD='KC-AWARD'
/
UPDATE KRCR_PARM_T SET VAL ='1' WHERE  PARM_NM='ENABLE_AWARD_BIOHAZARD_REVIEW_VALID' AND NMSPC_CD='KC-AWARD'
/
UPDATE KRCR_PARM_T SET VAL ='Y' WHERE  PARM_NM='ENABLE_AWARD_TERM_REVIEW_VALID'
/
UPDATE KRCR_PARM_T SET VAL ='NIH Multiple PI' WHERE  PARM_NM='ALL_SPONSOR_HIERARCHY_NIH_MULTI_PI' AND NMSPC_CD ='KC-GEN'
/
UPDATE KRCR_PARM_T SET VAL ='Y' WHERE  PARM_NM='ALL_SPONSOR_HIERARCHY_NIH_MULTI_PI' AND NMSPC_CD ='KC-PD'
/
UPDATE KRCR_PARM_T SET VAL ='10' WHERE  PARM_NM='SAP_AWD_BUD_FEED_STATUS'
/
UPDATE KRCR_PARM_T SET VAL ='2015' WHERE  PARM_NM='SAP_FEED_CURRENT_FISCAL_YEAR'
/
UPDATE KRCR_PARM_T SET VAL = ' ' WHERE  PARM_NM = 'SAP_FEED_SPONSOR_FEED_USER'
/
UPDATE KRCR_PARM_T SET VAL = ' ' WHERE  PARM_NM = 'SAP_FEED_SPONSOR_FEED_DATE'
/
UPDATE KRCR_PARM_T SET VAL = ' ' WHERE  PARM_NM = 'SAP_FEED_ROLODEX_FEED_USER'
/
UPDATE KRCR_PARM_T SET VAL = ' ' WHERE  PARM_NM = 'SAP_FEED_ROLODEX_FEED_DATE'
/
UPDATE KRCR_PARM_T SET VAL ='1005,1006,1007' WHERE  PARM_NM = 'PROP_PERSON_COI_CERTIFY_QID'
/
UPDATE KRCR_PARM_T SET VAL = 'kc-notifications@mit.edu' WHERE  PARM_NM = 'KC_DEFAULT_EMAIL_RECIPIENT'
/
UPDATE KRCR_PARM_T SET VAL = '15' WHERE PARM_NM='awardBudgetStatusRePosted'
/
UPDATE KRCR_PARM_T SET VAL = '0' WHERE NMSPC_CD = 'KC-AWARD' AND PARM_NM = 'awardUncertifiedKeyPersonnel'
/
UPDATE KRCR_PARM_T SET VAL ='2' WHERE PARM_NM = 'OSP_ADMINISTRATOR_TYPE_CODE'
/
UPDATE KRCR_PARM_T SET VAL = 'false' WHERE PARM_NM = 'proposaldevelopment.displayKeywordPanel'
/
UPDATE KRCR_PARM_T SET VAL = 'N' WHERE PARM_NM= 'iacuc.protocol.institute.proposal.linking.enabled'
/
UPDATE KRCR_PARM_T SET VAL = 'N' WHERE PARM_NM= 'irb.protocol.institute.proposal.linking.enabled'
/
UPDATE KRCR_PARM_T SET VAL = 'N' WHERE PARM_NM= 'iacuc.protocol.award.linking.enabled'
/
UPDATE KRCR_PARM_T SET VAL = 'N' WHERE PARM_NM = 'irb.protocol.award.linking.enabled'
/
UPDATE KRCR_PARM_T SET VAL = 'N' WHERE PARM_NM= 'iacuc.protocol.proposal.development.linking.enabled'
/
UPDATE KRCR_PARM_T SET VAL = 'N' WHERE PARM_NM= 'irb.protocol.development.proposal.linking.enabled'
/ 
UPDATE KRCR_PARM_T SET VAL = '000001' WHERE PARM_NM='DEFAULT_ORGANIZATION_ID'
/
UPDATE KRCR_PARM_T SET VAL='6' WHERE PARM_NM = 'KC_FISCAL_START_MONTH'
/
UPDATE KRCR_PARM_T SET VAL='1' WHERE PARM_NM = 'KC_MODULE_AWARD'
/
UPDATE KRCR_PARM_T SET VAL='2' WHERE PARM_NM ='KC_MODULE_INSTITUTIONAL_PROPOSAL'
/
UPDATE KRCR_PARM_T SET VAL='3' WHERE PARM_NM ='KC_MODULE_PROPOSAL_DEVELOPMENT'
/
UPDATE KRCR_PARM_T SET VAL='4' WHERE PARM_NM ='KC_MODULE_SUBCONTRACTS'
/
UPDATE KRCR_PARM_T SET VAL='5' WHERE PARM_NM ='KC_MODULE_NEGOTIATIONS'
/
UPDATE KRCR_PARM_T SET VAL='6' WHERE PARM_NM ='KC_MODULE_PERSON'
/
UPDATE KRCR_PARM_T SET VAL='7' WHERE PARM_NM ='KC_MODULE_IRB'
/
UPDATE KRCR_PARM_T SET VAL='8' WHERE PARM_NM ='KC_MODULE_COI_DISCLOSURE'
/
UPDATE KRCR_PARM_T SET VAL='9' WHERE PARM_NM ='KC_MODULE_IACUC_PROTOCOL'
/
UPDATE KRCR_PARM_T SET VAL='11' WHERE PARM_NM ='KC_MODULE_COMMITTEE'
/
UPDATE KRCR_PARM_T SET VAL='1' WHERE PARM_NM ='KC_MODULE_AWARD_INT'
/
UPDATE KRCR_PARM_T SET VAL='2' WHERE PARM_NM ='KC_MODULE_INT_INSTITUTIONAL_PROPOSAL'
/
UPDATE KRCR_PARM_T SET VAL='3' WHERE PARM_NM ='KC_MODULE_INT_PROPOSAL_DEVELOPMENT'
/
UPDATE KRCR_PARM_T SET VAL='4' WHERE PARM_NM ='KC_MODULE_INT_SUBCONTRACTS'
/
UPDATE KRCR_PARM_T SET VAL='5' WHERE PARM_NM ='KC_MODULE_INT_NEGOTIATIONS'
/
UPDATE KRCR_PARM_T SET VAL='6' WHERE PARM_NM ='KC_MODULE_INT_PERSON'
/
UPDATE KRCR_PARM_T SET VAL='7' WHERE PARM_NM ='KC_MODULE_INT_IRB'
/
UPDATE KRCR_PARM_T SET VAL='8' WHERE PARM_NM ='KC_MODULE_INT_COI_DISCLOSURE'
/
UPDATE KRCR_PARM_T SET VAL='9' WHERE PARM_NM ='KC_MODULE_INT_IACUC_PROTOCOL'
/
UPDATE KRCR_PARM_T SET VAL='11' WHERE PARM_NM ='KC_MODULE_INT_COMMITTEE'
/
UPDATE KRCR_PARM_T SET VAL='N' WHERE PARM_NM ='JOBCODE_VALIDATION_ENABLED'
/
UPDATE KRCR_PARM_T SET VAL='1' WHERE PARM_NM ='TXN_TYPE_DEF_COPIED_AWARD' AND nmspc_cd ='KC-AWARD'
/
UPDATE KRCR_PARM_T SET VAL='Y' WHERE PARM_NM ='EnableRoleIntegration'
/
UPDATE KRCR_PARM_T SET VAL='AWRD' WHERE PARM_NM ='RoleCentralDbCategoryCode'
/
UPDATE KRCR_PARM_T SET VAL='Y' WHERE PARM_NM ='EnableFrequencyBaseValidationForNull'
/
UPDATE KRCR_PARM_T SET VAL='Y' WHERE PARM_NM ='EnableFrequencyVALidationForNull'
/
UPDATE KRCR_PARM_T SET VAL='directory name' WHERE PARM_NM ='SAP_FEED_DEVELOPMENT'
/
UPDATE KRCR_PARM_T SET VAL='TEST' WHERE PARM_NM ='SAP_FEED_TEST'
/
UPDATE KRCR_PARM_T SET VAL='directory name' WHERE PARM_NM ='SAP_FEED_PRODUCTION'
/
UPDATE KRCR_PARM_T SET VAL='0 5 7 * * ?' WHERE PARM_NM ='CAC_DATA_FEED_CRON_TRIGGER'
/
UPDATE KRCR_PARM_T SET VAL='Y' WHERE PARM_NM ='ENABLE_CAC_DATA_FEED'
/
UPDATE KRCR_PARM_T SET VAL = '2' WHERE PARM_NM= 'PROPOSAL_CONTACT_TYPE'
/
UPDATE  KRCR_PARM_T SET VAL='Y' WHERE PARM_NM='AUTO_GENERATE_NON_EMPLOYEE_ID'
/
UPDATE  KRCR_PARM_T SET VAL='MIT' WHERE PARM_NM='SCHOOL_ACRONYM'
/
UPDATE  KRCR_PARM_T SET VAL='Massachusetts Institute of Technology' WHERE PARM_NM='SCHOOL_NAME'
/
UPDATE  KRCR_PARM_T SET VAL='4'WHERE PARM_NM='MODULE_SUB_ITEM_CODE_PI_CERTIFICATION'
/
UPDATE  KRCR_PARM_T SET VAL='5'WHERE PARM_NM='MODULE_SUB_ITEM_CODE_COI_CERTIFICATION'
/
UPDATE  KRCR_PARM_T SET VAL='6'WHERE PARM_NM='MODULE_SUB_ITEM_CODE_KP_CERTIFICATION'
/
UPDATE  KRCR_PARM_T SET VAL='N' WHERE PARM_NM='award.creditsplit.enabled'
/
UPDATE  KRCR_PARM_T SET VAL='N' WHERE PARM_NM='proposaldevelopment.creditsplit.enabled'
/
UPDATE  KRCR_PARM_T SET VAL='N' WHERE PARM_NM='institutionalproposal.creditsplit.enabled'
/
UPDATE KRCR_PARM_T SET VAL = 'N' WHERE PARM_NM = 'ENABLE_CREATE_PROPOSAL_TO_IACUC_PROTOCOL'
/
UPDATE KRCR_PARM_T SET VAL = 'N' WHERE PARM_NM = 'ENABLE_CREATE_PROPOSAL_TO_IRB_PROTOCOL'
/
UPDATE KRCR_PARM_T SET VAL = 'Y' WHERE PARM_NM = 'enableFormulatedCostCalculation'
/
UPDATE KRCR_PARM_T SET VAL = '0' WHERE PARM_NM = 'enableSalaryInflationAnniversaryDate'
/
UPDATE KRCR_PARM_T SET VAL = 'FDP_ATT_5' WHERE PARM_NM = 'Subaward_FDP_Attachment_5_Form_ID'
/
UPDATE KRCR_PARM_T SET VAL = 'P,N' WHERE PARM_NM = 'budgetCategoryType.personnel.extension'
/
UPDATE KRCR_PARM_T SET VAL = 'COI Hierarchy requiring KPs' WHERE PARM_NM = 'COIHierarchyRequiringKPs'
/
UPDATE KRCR_PARM_T SET VAL = 'FALSE' WHERE PARM_NM = 'award.ip.displayKeywordPanel' AND NMSPC_CD='KC-GEN'
/
UPDATE KRCR_PARM_T set VAL ='Project Period' WHERE  PARM_NM = 'CostShareProjectPeriodNameLabel'
/
---------------------------------------
UPDATE KRCR_PARM_T set VAL = '14' WHERE  PARM_NM = 'PROPOSAL_TYPE_CODE_PRE_PROPOSAL' AND NMSPC_CD='KC-PD'
/
UPDATE KRCR_PARM_T set VAL = '@{#param("KC-PD", "Document", "PROPOSAL_TYPE_CODE_PRE_PROPOSAL")}' WHERE  PARM_NM = 'PROPOSAL_TYPE_CODE_PRE_PROPOSAL' AND NMSPC_CD='KC-S2S'
/
UPDATE KRCR_PARM_T set VAL = '17' WHERE  PARM_NM = 'PROPOSAL_TYPE_CODE_BUDGET_SOW_UPDATE' AND NMSPC_CD = 'KC-PD'
/
UPDATE KRCR_PARM_T set VAL = '15' WHERE  PARM_NM = 'PROPOSAL_TYPE_CODE_SUPPLEMENT_CHANGE_CORRECTED' AND NMSPC_CD = 'KC-PD'
/
UPDATE KRCR_PARM_T set VAL = '@{#param("KC-PD", "Document", "PROPOSAL_TYPE_CODE_SUPPLEMENT_CHANGE_CORRECTED")}' WHERE  PARM_NM = 'PROPOSAL_TYPE_CODE_SUPPLEMENT_CHANGE_CORRECTED' AND NMSPC_CD = 'KC-S2S'
/
UPDATE KRCR_PARM_T set VAL = '18' WHERE  PARM_NM = 'PROPOSAL_TYPE_CODE_RENEWAL_CHANGE_CORRECTED' AND NMSPC_CD = 'KC-PD'
/
UPDATE KRCR_PARM_T set VAL = '@{#param("KC-PD", "Document", "PROPOSAL_TYPE_CODE_RENEWAL_CHANGE_CORRECTED")}' WHERE  PARM_NM = 'PROPOSAL_TYPE_CODE_RENEWAL_CHANGE_CORRECTED' AND NMSPC_CD = 'KC-S2S'
/
UPDATE KRCR_PARM_T set VAL = '16' WHERE  PARM_NM = 'PROPOSAL_TYPE_CODE_RESUBMISSION_CHANGE_CORRECTED' AND NMSPC_CD = 'KC-PD'
/
UPDATE KRCR_PARM_T set VAL = '@{#param("KC-PD", "Document", "PROPOSAL_TYPE_CODE_RESUBMISSION_CHANGE_CORRECTED")}' WHERE  PARM_NM = 'PROPOSAL_TYPE_CODE_RESUBMISSION_CHANGE_CORRECTED' AND NMSPC_CD = 'KC-S2S'
/
UPDATE KRCR_PARM_T set VAL = '10' WHERE  PARM_NM = 'PROPOSAL_TYPE_CODE_NEW_CHANGE_CORRECTED' AND NMSPC_CD = 'KC-PD'
/
UPDATE KRCR_PARM_T set VAL = '@{#param("KC-PD", "Document", "PROPOSAL_TYPE_CODE_NEW_CHANGE_CORRECTED")}' WHERE  PARM_NM = 'PROPOSAL_TYPE_CODE_NEW_CHANGE_CORRECTED' AND NMSPC_CD = 'KC-S2S'
/
UPDATE KRCR_PARM_T set VAL = '000001 Office of Sponsored Programs CA' WHERE  PARM_NM = 'OSP_PEOPLE_FLOW_NAME'
/
UPDATE KRCR_PARM_T set VAL = 'Workload Balancing' WHERE  PARM_NM = 'WL_SPONSOR_HIERARCHY_NAME'
/
UPDATE KRCR_PARM_T set VAL = 'N' WHERE  PARM_NM = 'ENABLE_WL_ROUTING'
/
UPDATE KRCR_PARM_T set VAL = 'COI Disclosures' WHERE  PARM_NM = 'COIHierarchyName'
/
UPDATE KRCR_PARM_T set VAL = 'COI Disclosures with KP Req' WHERE  PARM_NM = 'COIHierarchyLevel1'
/