CREATE SEQUENCE  SEQ_SHARED_DOCUMENT_TYPE
MINVALUE 1 
MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE  
ORDER  
NOCYCLE
/
CREATE TABLE SHARED_DOCUMENT_TYPE(	
SHARED_DOCUMENT_TYPE_ID   NUMBER(12,0),
COEUS_MODULE_CODE NUMBER(3,0) NOT NULL ENABLE, 
DOCUMENT_TYPE_CODE NUMBER(3,0) NOT NULL ENABLE, 
UPDATE_TIMESTAMP DATE NOT NULL ENABLE, 
UPDATE_USER VARCHAR2(60 BYTE) NOT NULL ENABLE,
VER_NBR	NUMBER(8,0),
OBJ_ID	VARCHAR2(36),
CONSTRAINT "PK_SHARED_DOCUMENT_TYP" PRIMARY KEY (SHARED_DOCUMENT_TYPE_ID)
)
/
