CREATE TABLE PROP_QUESTIONNAIRE_VALIDATION
(
   QUESTIONNAIRE_VALIDATION_ID  NUMBER (12) NOT NULL,
   QUESTIONNAIRE_ID		    	NUMBER (12) NOT NULL,
   QUESTION_ID	     		    NUMBER (12) NOT NULL,
   ANSWER                       VARCHAR2 (2000) NOT NULL,
   VALIDATION_MESSAGE		    VARCHAR2 (1000) NOT NULL,
   UPDATE_TIMESTAMP             DATE DEFAULT SYSDATE NOT NULL,
   UPDATE_USER                  VARCHAR2 (60) NOT NULL,
   VER_NBR                      NUMBER (8) DEFAULT 1 NOT NULL,
   OBJ_ID                       VARCHAR2 (36) DEFAULT SYS_GUID() NOT NULL
)
/

ALTER TABLE PROP_QUESTIONNAIRE_VALIDATION
ADD CONSTRAINT PK_PQ_VALIDATION_ID
PRIMARY KEY (QUESTIONNAIRE_VALIDATION_ID)
/

ALTER TABLE PROP_QUESTIONNAIRE_VALIDATION
ADD CONSTRAINT UQ_PQ_VALIDATION_ID
UNIQUE (QUESTIONNAIRE_ID, QUESTION_ID)
/

