CREATE TABLE ALERT_TYPE
(
   ALERT_TYPE_ID  			NUMBER (12) NOT NULL,
   ALERT_TYPE_NAME		    VARCHAR2 (500) NOT NULL,
   ALERT_TYPE_NMSPC_CD	    VARCHAR2 (40) NOT NULL,
   ALERT_TYPE_SERVICE_NM    VARCHAR2 (500) NOT NULL,
   ALERT_TYPE_ACTIVE		CHAR (1) DEFAULT 'Y' NOT NULL,
   UPDATE_TIMESTAMP         DATE DEFAULT SYSDATE NOT NULL,
   UPDATE_USER              VARCHAR2 (60) NOT NULL,
   VER_NBR                  NUMBER (8) DEFAULT 1 NOT NULL,
   OBJ_ID                   VARCHAR2 (36) DEFAULT SYS_GUID() NOT NULL
)
/

ALTER TABLE ALERT_TYPE
ADD CONSTRAINT PK_ALERT_TYPE_ID
PRIMARY KEY (ALERT_TYPE_ID)
/

