ALTER TABLE SYSTEM_ALERTS
ADD ALERT_TYPE_ID  NUMBER (12) NOT NULL
/

ALTER TABLE SYSTEM_ALERTS
ADD CONSTRAINT FK_ALERT_TYPE_ID
FOREIGN KEY (ALERT_TYPE_ID)
REFERENCES ALERT_TYPE (ALERT_TYPE_ID)
/

ALTER TABLE SYSTEM_ALERTS
DROP COLUMN MODULE_NMSPC_CD
/

ALTER TABLE SYSTEM_ALERTS
DROP COLUMN MODULE_NAME
/
