CREATE TABLE DASH_BOARD_MENU_ITEMS
(
   DASH_BOARD_MENU_ITEM_ID   	NUMBER (12) NOT NULL,
   MENU_ITEM                     VARCHAR2 (500) NOT NULL,
   MENU_ACTION		    		VARCHAR2 (2000) NOT NULL,
   OSP_ONLY_FLAG				CHAR(1) NOT NULL,
   ACTIVE			CHAR(1) NOT NULL,
   UPDATE_TIMESTAMP             DATE DEFAULT SYSDATE NOT NULL,
   UPDATE_USER                  VARCHAR2 (60) NOT NULL,
   VER_NBR                      NUMBER (8) DEFAULT 1 NOT NULL,
   OBJ_ID                       VARCHAR2 (36) DEFAULT SYS_GUID() NOT NULL
)
/

ALTER TABLE DASH_BOARD_MENU_ITEMS
ADD CONSTRAINT PK_DASH_BOARD_MENU_ITEM
PRIMARY KEY (DASH_BOARD_MENU_ITEM_ID)
/

