INSERT INTO KRCR_PARM_T(NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID)
VALUES ('KC-GEN', 'All', 'OSP_PEOPLE_FLOW_NAME', SYS_GUID(), '1', 'CONFG', '000001-Office of Sponsored Programs-CA', 'The name of OSP peopleflow', 'A', 'KC')
/
INSERT INTO KRCR_PARM_T(NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID)
VALUES ('KC-GEN', 'All', 'WL_SPONSOR_HIERARCHY_NAME', SYS_GUID(), '1', 'CONFG', 'Workload Balancing', 'The name of Workload Balancing sponsor heirachy', 'A', 'KC')
/
INSERT INTO KRCR_PARM_T(NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID)
VALUES ('KC-GEN', 'All', 'ENABLE_WL_ROUTING', SYS_GUID(), '1', 'CONFG', 'N', 'To Enable WL routing', 'A', 'KC')
/
