UPDATE KRCR_PARM_T SET VAL = '3' WHERE PARM_NM = 'PROPOSAL_TYPE_CODE_CONTINUATION' and NMSPC_CD='KC-PD'
/

UPDATE KRCR_PARM_T SET VAL = '4' WHERE PARM_NM = 'PROPOSAL_TYPE_CODE_REVISION' and NMSPC_CD='KC-PD'
/

UPDATE KRCR_PARM_T SET VAL = '5' WHERE PARM_NM = 'PROPOSAL_TYPE_CODE_RENEWAL' and NMSPC_CD='KC-PD'
/

UPDATE KRCR_PARM_T SET VAL = '6' WHERE PARM_NM = 'PROPOSAL_TYPE_CODE_RESUBMISSION' and NMSPC_CD='KC-PD'
/

UPDATE KRCR_PARM_T SET VAL = '9' WHERE PARM_NM = 'PROPOSAL_TYPE_CODE_TASK_ORDER' and NMSPC_CD='KC-PD'
/
