Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values
('KC-GEN','All','PROPOSAL_IP_REVIEW_COMMENT_CODE',SYS_GUID(),1,'CONFG','16','Comment type code for IP review comments','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values
('KC-GEN','All','PROPOSAL_SUMMARY_COMMENT_CODE',SYS_GUID(),1,'CONFG','12','Code number of Proposal Summary value','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values
('KC-GEN','All','SPECIAL_RATE_COMMENT_CODE',SYS_GUID(),1,'CONFG','7','Comment type code for Special rate comments in awards','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values
('KC-GEN','All','SPECIAL_REVIEW_COMMENT_CODE',SYS_GUID(),1,'CONFG','10','Comment type code for Special review comments','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values
('KC-GEN','All','FISCAL_REPORT_COMMENT_CODE',SYS_GUID(),1,'CONFG','3','Code of value Fiscal Reports Comment','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values
('KC-GEN','All','INDIRECT_COST_COMMENT_CODE',SYS_GUID(),1,'CONFG','8','Comment type code for Indirect cost Comments','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values
('KC-GEN','All','INVOICE_INSTRUCTION_COMMENT_CODE',SYS_GUID(),1,'CONFG','1','Comment type code for Invoice instructions','A','KC')
/
commit
/
