Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values
('KC-GEN','All','FISCAL_CLASS_CODE',SYS_GUID(),1,'CONFG','1','Code for report class Fiscal','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values
('KC-GEN','All','INTELLECTUAL_PROPERTY_CLASS_CODE',SYS_GUID(),1,'CONFG','3','Report class code for Intellectual property reports','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values
('KC-GEN','All','PROCUREMENT_CLASS_CODE',SYS_GUID(),1,'CONFG','5','Report class code for Procurement reports','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values
('KC-GEN','All','PROPERTY_CLASS_CODE',SYS_GUID(),1,'CONFG','2','Report class code for Property reports','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values
('KC-GEN','All','TECHNICAL_MANAGEMENT_CLASS_CODE',SYS_GUID(),1,'CONFG','4','Report class code for Technical/Management reports','A','KC')
/
commit
/