CREATE SEQUENCE SEQ_IP_FY_BASED_ID INCREMENT BY 1 MAXVALUE 9999 MINVALUE 1 CACHE 20
/
ALTER SEQUENCE SEQ_IP_FY_BASED_ID CYCLE;
/
REM INSERTING into KRCR_PARM_T
SET DEFINE OFF;
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-PD','Document','GENERATE_IP_BASED_ON_FY',sys_guid(),1,'CONFG','Y','On enabling this parameter,IP Number will be generated based on the fiscal year.','A','KUALI');
commit;

