Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values
('KC-GEN','All','MODULE_SUB_ITEM_CODE_PI_CERTIFICATION',SYS_GUID(),1,'CONFG','4','Module Sub Item Code For PI Certification Questionnire','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values
('KC-GEN','All','MODULE_SUB_ITEM_CODE_COI_CERTIFICATION',SYS_GUID(),1,'CONFG','5','Module Sub Item Code For PI Certification Questionnire','A','KC')
/
Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values
('KC-GEN','All','MODULE_SUB_ITEM_CODE_KP_CERTIFICATION',SYS_GUID(),1,'CONFG','6','Module Sub Item Code For PI Certification Questionnire','A','KC')
/
