INSERT INTO KRCR_PARM_T(NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID)
VALUES ('KC-PD','Document','COIHierarchyName',SYS_GUID(),1,'CONFG','COI Disclosures','COI Hierarchy name','A','KC')
/
INSERT INTO KRCR_PARM_T(NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID)
VALUES ('KC-PD','Document','COIHierarchyLevel1',SYS_GUID(),1,'CONFG','COI Disclosures with KP Req','COI Hierarchy requiring KPs sponsor heirarchy','A','KC')
/
