//Drop TABLE  CAC_DATA
///
CREATE TABLE  CAC_DATA
(
  CAC_DATA_ID               NUMBER (22),
  APPROVAL_DATE             VARCHAR2(12 BYTE),
  CONTACT_EMAIL                VARCHAR2(200 BYTE),
  DEPT                        VARCHAR2(200 BYTE),
  EXPIRATION_DATE           VARCHAR2(12 BYTE),
  FUNDING_AGENCY            VARCHAR2(200 BYTE),
  FUNDING_AGENCY2           VARCHAR2(200 BYTE),
  FUNDING_AGENCY3           VARCHAR2(200 BYTE),
  FUNDING_AGENCY4           VARCHAR2(200 BYTE),
  FUNDING_AGENCY5           VARCHAR2(200 BYTE),
  FUNDING_AGENCY6           VARCHAR2(200 BYTE),
  GRANT_NUMBER              VARCHAR2(200 BYTE),  
  GRANT_NUMBER2             VARCHAR2(200 BYTE),  
  GRANT_NUMBER3             VARCHAR2(200 BYTE),  
  GRANT_NUMBER4             VARCHAR2(200 BYTE),  
  GRANT_NUMBER5             VARCHAR2(200 BYTE),  
  GRANT_NUMBER6             VARCHAR2(200 BYTE),
  PI_EMAIL                    VARCHAR2(200 BYTE),  
  PI_FIRST_NAME                VARCHAR2(200 BYTE),
  PI_LAST_NAME                VARCHAR2(200 BYTE),
  PREVIOUS_PROTOCOL_NUMBER  VARCHAR2(20 BYTE),
  PROPOSAL_TYPE             VARCHAR2(200 BYTE),  
  PROTOCOL_NUMBER           VARCHAR2(20 BYTE),  
  REVIEW_LEVEL              VARCHAR2(200 BYTE),  
  SUBMISSION_DATE           VARCHAR2(12 BYTE),
  WBS_IP_1                  VARCHAR2(200 BYTE),
  WBS_IP_2                  VARCHAR2(200 BYTE),
  WBS_IP_3                  VARCHAR2(200 BYTE), 
  WBS_IP_4                  VARCHAR2(200 BYTE),
  WBS_IP_5                  VARCHAR2(200 BYTE),
  WBS_IP_6                  VARCHAR2(200 BYTE),
  --VER_NBR             NUMBER(8)     DEFAULT 1   NOT NULL,
  --OBJ_ID              VARCHAR2(36 BYTE)   DEFAULT sys_guid()       NOT NULL,
  CONSTRAINT PK_CAC_DATA PRIMARY KEY (CAC_DATA_ID)
)
/


CREATE SEQUENCE SEQ_CAC_DATA_ID
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  CYCLE
  NOCACHE
  NOORDER; 


CREATE SEQUENCE SEQ_CAC_LOG_DATA_ID
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER; 

CREATE TABLE  CAC_LOG_DATA
(
  CAC_LOG_DATA_ID		NUMBER(12)  NOT NULL,
  PROTOCOL_NUMBER_CAC         VARCHAR2(20 BYTE),
  AWARD_IP_NUMBER             VARCHAR2(12 BYTE), 
  WBS_IP_CAC                  VARCHAR2(200 BYTE),
  COMMENTS			              VARCHAR2(900 BYTE), 
  lOG_NOTE                     VARCHAR2(200 BYTE),
  SPREV_APPROVAL_DATE          VARCHAR2(12 BYTE),
  AWARD_EXPIRATION_DATE       VARCHAR2(12 BYTE),  
  SUBMISSION_DATE_CAC         VARCHAR2(12 BYTE),
  APPROVAL_DATE_CAC           VARCHAR2(12 BYTE),
  LOG_INDICATOR			          VARCHAR2(2 BYTE),  
  UPDATE_TIMESTAMP   DATE,
  VER_NBR             NUMBER(8)   DEFAULT 1     NOT NULL,
  OBJ_ID              VARCHAR2(36 BYTE)         NOT NULL,
  CONSTRAINT PK_CAC_LOG_DATA  PRIMARY KEY  (CAC_LOG_DATA_ID)
)
/




