@ddl_sap_04082015.sql
@ddl_award_kp_confrm_rmvl.sql
@../feed/sap/upd_sap_feed_log_error.sql
@../feed/sap/fn_spool_batch.sql
@../feed/sap/kc_sap_feed_pkg.sql
@../feed/sap/fn_generate_sap_feed.sql
@../feed/sap/fn_spool_awd_budget_batch.sql
@../feed/sap/fn_generate_sap_budget_feed.sql
@../feed/sap/fn_generate_master_sap_feed.sql
@../notification/kp_notification/t_kp_confirm_aft_insert_row.sql
