ALTER TABLE SAP_FEED ADD SAP_FEED_BATCH_ID NUMBER(12,0)
/
ALTER TABLE SAP_FEED_ERROR_LOG ADD SAP_FEED_BATCH_ID NUMBER(12,0)
/
ALTER TABLE  SAP_FEED_DETAILS ADD SAP_FEED_BATCH_ID NUMBER(12,0)
/
ALTER TABLE SAP_FEED_BATCH_LIST DROP CONSTRAINT UQ_BATCH_LIST
/
ALTER TABLE SAP_FEED_ERROR_LOG ADD CONSTRAINT FK_SAP_FEED_ERROR_LOG   FOREIGN KEY (SAP_FEED_BATCH_ID)  REFERENCES SAP_FEED_BATCH_LIST(SAP_FEED_BATCH_ID)
/
ALTER TABLE SAP_FEED ADD CONSTRAINT FK_SAP_FEED   FOREIGN KEY (SAP_FEED_BATCH_ID)  REFERENCES SAP_FEED_BATCH_LIST(SAP_FEED_BATCH_ID)
/
ALTER TABLE SAP_FEED_DETAILS ADD CONSTRAINT FK_SAP_FEED_DETAILS   FOREIGN KEY (SAP_FEED_BATCH_ID)  REFERENCES SAP_FEED_BATCH_LIST(SAP_FEED_BATCH_ID)
/
ALTER TABLE SAP_BUDGET_FEED_DETAILS ADD SAP_BUDGET_FEED_BATCH_ID NUMBER(12,0)
/
ALTER TABLE SAP_BUDGET_FEED ADD SAP_BUDGET_FEED_BATCH_ID NUMBER(12,0)
/
