ALTER TABLE AWARD_PERSON_REMOVE  RENAME TO AWARD_KEY_PERS_REMOVED
/
ALTER TABLE AWARD_KEY_PERS_REMOVED RENAME COLUMN AWARD_PERSON_REMOVE_ID TO AWARD_KEY_PERS_REMOVED_ID
/
ALTER TABLE AWARD_PERSON_CONFIRM  RENAME TO AWARD_KEY_PERS_CONFIRM
/
ALTER TABLE AWARD_KEY_PERS_CONFIRM RENAME COLUMN AWARD_PERSON_CONFIRM_ID TO AWARD_KEY_PERS_CONFIRM_ID
/
