CREATE SEQUENCE  SEQ_SAP_FEED_ERROR_ID
START WITH 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER
/ 
TRUNCATE TABLE SAP_FEED_ERROR_LOG
/
ALTER TABLE SAP_FEED_ERROR_LOG ADD SAP_FEED_ERROR_ID NUMBER(12)
/
ALTER TABLE SAP_FEED_ERROR_LOG MODIFY ERROR_MESSAGE VARCHAR2(1000)
/
ALTER TABLE SAP_FEED_ERROR_LOG ADD CONSTRAINT PK_SAP_FEED_ERROR_LOG PRIMARY KEY (SAP_FEED_ERROR_ID )
/
