INSERT INTO CUSTOM_ATTRIBUTE_DOCUMENT(DOCUMENT_TYPE_CODE,IS_REQUIRED,CUSTOM_ATTRIBUTE_ID,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,ACTIVE_FLAG,OBJ_ID)
select 'SAWD','N',c.ID,c.UPDATE_TIMESTAMP,c.UPDATE_USER,1,'Y',sys_guid() from CUSTOM_ATTRIBUTE c 
left outer join CUSTOM_ATTRIBUTE_DOCUMENT ca on c.ID=ca.CUSTOM_ATTRIBUTE_ID
where ca.CUSTOM_ATTRIBUTE_ID IS NULL
and c.NAME='NEG_NUMBER_SUB'
/

