DROP TABLE OSP$AWARD_KEY_PERS_REMOVED
/
CREATE TABLE OSP$AWARD_KEY_PERS_REMOVED
(	AWARD_KP_REMOVED_NUMBER NUMBER(10,0), 
MIT_AWARD_NUMBER VARCHAR2(12), 
SEQUENCE_NUMBER NUMBER(4,0), 
PERSON_ID VARCHAR2(9), 
CONFIRM_FLAG CHAR(1), 
CONFIRM_TIMESTAMP DATE, 
CONFIRM_USER VARCHAR2(8), 
DELETE_TIMESTAMP DATE, 
DELETE_USER VARCHAR2(8)
)
/
INSERT INTO OSP$AWARD_KEY_PERS_REMOVED(
AWARD_KP_REMOVED_NUMBER,
MIT_AWARD_NUMBER,
SEQUENCE_NUMBER,
PERSON_ID,
CONFIRM_FLAG,
CONFIRM_TIMESTAMP,
CONFIRM_USER,
DELETE_TIMESTAMP,
DELETE_USER
)
SELECT AWARD_KP_REMOVED_NUMBER,
MIT_AWARD_NUMBER,
SEQUENCE_NUMBER,
PERSON_ID,
CONFIRM_FLAG,
CONFIRM_TIMESTAMP,
CONFIRM_USER,
DELETE_TIMESTAMP,
DELETE_USER
FROM OSP$AWARD_KEY_PERS_REMOVED@coeus.kuali
/
COMMIT
/
UPDATE OSP$AWARD_KEY_PERS_REMOVED SET MIT_AWARD_NUMBER = replace(MIT_AWARD_NUMBER,'-','-00')
/
COMMIT
/
DELETE FROM AWARD_KEY_PERS_REMOVED WHERE (AWARD_NUMBER,sequence_number) in ( select MIT_AWARD_NUMBER,sequence_number from OSP$AWARD_KEY_PERS_REMOVED )
/
commit
/
INSERT INTO AWARD_KEY_PERS_REMOVED(
AWARD_KEY_PERS_REMOVED_ID,
AWARD_PERSON_ID,
AWARD_ID,
AWARD_NUMBER,
PERSON_ID,
CONFIRM_FLAG,
UPDATE_TIMESTAMP,
UPDATE_USER,
VER_NBR,
OBJ_ID,
UPDATE_TIMESTAMP_CONFIRM,
UPDATE_USER_CONFIRM,
SEQUENCE_NUMBER
)
SELECT
SEQ_AWARD_PERSON_REMOVE_ID.NEXTVAL,
null,
t3.AWARD_ID,
t3.AWARD_NUMBER,
t1.PERSON_ID,
t1.CONFIRM_FLAG,
t1.DELETE_TIMESTAMP,
t1.DELETE_USER,
1,
sys_guid(),
t1.CONFIRM_TIMESTAMP,
t1.CONFIRM_USER,
t3.SEQUENCE_NUMBER
FROM OSP$AWARD_KEY_PERS_REMOVED t1
INNER JOIN AWARD t3 on t1.MIT_AWARD_NUMBER = t3.AWARD_NUMBER AND t1.SEQUENCE_NUMBER = t3.SEQUENCE_NUMBER 
 /
 commit
 /
DROP TABLE OSP$AWARD_KEY_PERS_CONFIRM
/