UPDATE UNIT_ADMINISTRATOR_TYPE
SET DEFAULT_GROUP_FLAG = 'C'
WHERE UPDATE_USER like 'admin'
AND DEFAULT_GROUP_FLAG <> 'N'
/
UPDATE UNIT_ADMINISTRATOR_TYPE
SET DEFAULT_GROUP_FLAG = 'U'
WHERE UPDATE_USER <>'admin'
/
commit
/
