truncate table TRAINING_MODULES
/
INSERT INTO TRAINING_MODULES(
TRAINING_MODULES_ID,
TRAINING_CODE,
MODULE_CODE,
SUB_MODULE_CODE,
DESCRIPTION,
UPDATE_TIMESTAMP,
UPDATE_USER,
VER_NBR,
OBJ_ID
)
SELECT 
SEQ_TRAINING_MODULES_ID.NEXTVAL,
TRAINING_CODE,
MODULE_CODE,
SUB_MODULE_CODE,
DESCRIPTION,
UPDATE_TIMESTAMP,
UPDATE_USER,
1,
sys_guid()
FROM OSP$TRAINING_MODULES@coeus.kuali
/
