set serveroutput on;
declare
  li_max_coeus_kc_prop      NUMBER;
  li_len_max_coeus_kc_prop  NUMBER;
  li_max_kc_prop            NUMBER;
  li_seq_prop               NUMBER;
  li_new_increment          NUMBER;
begin

  select max(to_number(a.proposal_number)) into li_max_coeus_kc_prop from eps_proposal a, osp$eps_proposal@coeus.kuali b
  where to_number(a.proposal_number)=to_number(b.proposal_number);  
  dbms_output.put_line('li_max_coeus_kc_prop := '||li_max_coeus_kc_prop);
  
  li_len_max_coeus_kc_prop := length(li_max_coeus_kc_prop);
  dbms_output.put_line('li_len_max_coeus_kc_prop := '||li_len_max_coeus_kc_prop);
  
  select max(to_number(a.proposal_number)) into li_max_kc_prop from eps_proposal a 
  where length(a.proposal_number) <= li_len_max_coeus_kc_prop;
  dbms_output.put_line('li_max_kc_prop := '||li_max_kc_prop);
  
  SELECT SEQ_PROPOSAL_NUMBER_KRA.NEXTVAL into li_seq_prop FROM DUAL;
  dbms_output.put_line('li_seq_prop := '||li_seq_prop);
  
  li_new_increment := li_max_kc_prop - li_seq_prop;
  dbms_output.put_line('li_new_increment := '||li_new_increment);
  
  li_new_increment := li_new_increment + 10;
  dbms_output.put_line('li_new_increment := '||li_new_increment);
  
  execute immediate('alter sequence SEQ_PROPOSAL_NUMBER_KRA increment by '||li_new_increment);   
  
end;
/
select SEQ_PROPOSAL_NUMBER_KRA.NEXTVAL from dual
/
alter sequence SEQ_PROPOSAL_NUMBER_KRA increment by 1
/
create table temp_eps_prop_mapping_1(
PROPOSAL_NUMBER     VARCHAR2(12),
NEW_PROPOSAL_NUMBER  VARCHAR2(12)
)
/
INSERT INTO temp_eps_prop_mapping_1(PROPOSAL_NUMBER,NEW_PROPOSAL_NUMBER)
SELECT t1.proposal_number,SEQ_PROPOSAL_NUMBER_KRA.NEXTVAL FROM 
( select  proposal_number from eps_proposal where proposal_number > 
(
select max(to_number(a.proposal_number)) from eps_proposal a, osp$eps_proposal@coeus.kuali b
where to_number(a.proposal_number)=to_number(b.proposal_number)
)
and length(proposal_number) > (select length(max(to_number(a.proposal_number))) from eps_proposal a, osp$eps_proposal@coeus.kuali b
where to_number(a.proposal_number)=to_number(b.proposal_number))
order by to_number(proposal_number)
)t1
/
commit
/
ALTER TABLE EPS_PROP_LOCATION DISABLE CONSTRAINT FK_EPS_PROP_LOCATION_KRA ;
ALTER TABLE S2S_OPPORTUNITY DISABLE CONSTRAINT FK_S2S_OPPORTUNITY_KRA2 ;
ALTER TABLE PROPOSAL_ADMIN_DETAILS DISABLE CONSTRAINT FK_PROPOSAL_ADMIN_DETAILS_1 ;
ALTER TABLE EPS_PROPOSAL_BUDGET_STATUS DISABLE CONSTRAINT FK_EPS_PROP_BUDGET_STATUS_KRA ;
ALTER TABLE EPS_PROPOSAL DISABLE CONSTRAINT EPS_PROPOSAL_FK1 ;
ALTER TABLE EPS_PROP_SITES DISABLE CONSTRAINT FK_EPS_PROP_SITES1 ;
ALTER TABLE EPS_PROP_SCIENCE_KEYWORD DISABLE CONSTRAINT FK_EPS_PROP_SCIE_KEY_PROP_KRA ;
ALTER TABLE EPS_PROP_UNIT_CREDIT_SPLIT DISABLE CONSTRAINT FK1_EPS_PROP_UNIT_CREDIT_SPLIT ;
ALTER TABLE S2S_OPP_FORMS DISABLE CONSTRAINT FK_S2S_OPP_FORMS_KRA ;
ALTER TABLE BUDGET_DETAILS DISABLE CONSTRAINT FK_BUDGET_DETAILS_HIER ;
ALTER TABLE NARRATIVE DISABLE CONSTRAINT FK_NARRATIVE_HIER ;
ALTER TABLE EPS_PROP_ABSTRACT DISABLE CONSTRAINT FK_EPS_PROP_ABSTRACT_KRA ;
ALTER TABLE EPS_PROP_SPECIAL_REVIEW DISABLE CONSTRAINT FK_EPS_PROP_SPECIAL_REVIEW_KRA ;
ALTER TABLE S2S_APPLICATION DISABLE CONSTRAINT FK_S2S_APPLICATION_KRA ;
ALTER TABLE NARRATIVE DISABLE CONSTRAINT FK_NARRATIVE_KRA ;
ALTER TABLE BUDGET_PERSONS DISABLE CONSTRAINT FK_BUDGET_PERSONS_HIER ;
ALTER TABLE EPS_PROP_YNQ DISABLE CONSTRAINT FK_EPS_PROP_YNQ_KRA ;
ALTER TABLE EPS_PROP_USER_ROLES DISABLE CONSTRAINT FK_EPS_PROP_USER_ROLES_KRA ;
ALTER TABLE EPS_PROP_SPECIAL_REVIEW DISABLE CONSTRAINT FK_EPS_PROP_SPEC_RVW_HIER ;
ALTER TABLE EPS_PROP_SCIENCE_KEYWORD DISABLE CONSTRAINT FK_EPS_PROP_SCI_KWD_HIER ;
ALTER TABLE EPS_PROP_PERSON DISABLE CONSTRAINT FK_EPS_PROP_PERSON_HIER ;
ALTER TABLE S2S_APP_SUBMISSION DISABLE CONSTRAINT FK_S2S_APP_SUBMISSION_KRA ;
ALTER TABLE S2S_USER_ATTACHED_FORM DISABLE CONSTRAINT FK1_S2S_USER_ATTACHED_FORM ;
ALTER TABLE EPS_PROP_PER_CREDIT_SPLIT DISABLE CONSTRAINT FK1_EPS_PROP_PER_CREDIT_SPLIT ;
ALTER TABLE S2S_APP_ATTACHMENTS DISABLE CONSTRAINT FK_S2S_APP_ATTACHMENTS_KRA ;
ALTER TABLE NARRATIVE_ATTACHMENT DISABLE CONSTRAINT FK_NARRATIVE_ATTACHMENT_KRA;
ALTER TABLE EPS_PROP_EXEMPT_NUMBER DISABLE CONSTRAINT FK_EPS_PROP_SPECIAL_REVIEW;
ALTER TABLE NARRATIVE_USER_RIGHTS DISABLE CONSTRAINT FK_NARRATIVE_USER_RIGHTS_KRA
/
DECLARE

CURSOR c_eps IS
SELECT PROPOSAL_NUMBER,NEW_PROPOSAL_NUMBER FROM temp_eps_prop_mapping_1;
r_eps c_eps%ROWTYPE;

BEGIN
IF c_eps%ISOPEN THEN
CLOSE c_eps;
END IF;
OPEN c_eps;
LOOP
FETCH c_eps INTO r_eps;
EXIT WHEN c_eps%NOTFOUND;


BEGIN 

UPDATE EPS_PROPOSAL e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;

UPDATE EPS_PROPOSAL_BUDGET_STATUS e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;
                 
UPDATE EPS_PROP_ABSTRACT e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;  
               
UPDATE EPS_PROP_LOCATION e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;
                 
UPDATE EPS_PROP_PERSON e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;
                 
UPDATE S2S_USER_ATTACHED_FORM e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;
                 
UPDATE PROPOSAL_ADMIN_DETAILS e 
SET e.DEV_PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.DEV_PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;

UPDATE NARRATIVE e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 

UPDATE NARRATIVE_ATTACHMENT e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
 
UPDATE NARRATIVE_USER_RIGHTS e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;  
	

UPDATE NARRATIVE e 
SET e.HIERARCHY_PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.HIERARCHY_PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                          
UPDATE EPS_PROP_YNQ e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 

UPDATE EPS_PROP_PER_CREDIT_SPLIT e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;  
                                                                                         
UPDATE EPS_PROP_SITES e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                        
UPDATE BUDGET_DETAILS e 
SET e.HIERARCHY_PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.HIERARCHY_PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;
                                                                                           
UPDATE S2S_OPPORTUNITY e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                          
UPDATE S2S_APP_SUBMISSION e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                          
UPDATE BUDGET_PERSONS e 
SET e.HIERARCHY_PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.HIERARCHY_PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                 
UPDATE EPS_PROP_SPECIAL_REVIEW e 
SET e.HIERARCHY_PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                          
UPDATE EPS_PROP_SPECIAL_REVIEW e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                          
UPDATE S2S_APPLICATION e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                       
UPDATE S2S_OPP_FORMS e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                          
UPDATE EPS_PROP_USER_ROLES e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                          
UPDATE EPS_PROP_UNIT_CREDIT_SPLIT e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;
                                                                                           
UPDATE EPS_PROP_SCIENCE_KEYWORD e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                     
UPDATE EPS_PROP_SCIENCE_KEYWORD e 
SET e.HIERARCHY_PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.HIERARCHY_PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                          
UPDATE S2S_APP_ATTACHMENTS e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;
  
UPDATE BUDGET_CHANGED_DATA e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;
                                                                                          
UPDATE BUDGET_PROJECT_INCOME e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                        
UPDATE BUDGET_SUB_AWARDS e 
SET e.HIERARCHY_PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.HIERARCHY_PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                          
UPDATE EPS_PROP_CHANGED_DATA e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;   
                                                                                        
UPDATE EPS_PROP_CONG_DISTRICT e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;  
                                                                                       
UPDATE EPS_PROP_COST_SHARING e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                           
UPDATE EPS_PROP_IDC_RATE e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                          
UPDATE EPS_PROP_IDC_RATE e 
SET e.HIERARCHY_PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.HIERARCHY_PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;  
                                                                                      
UPDATE EPS_PROP_PERS_YNQ e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;  
                                                                                         
UPDATE EPS_PROP_PERSON_BIO e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;  
                                                                                          
UPDATE EPS_PROP_PERSON_BIO_ATTACHMENT e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;  
                                                                                       
UPDATE EPS_PROP_PERSON_DEGREE e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;  
                                                                                        
UPDATE EPS_PROP_PERSON_UNITS e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER; 
                                                                                          
UPDATE EPS_PROPOSAL_BUDGET_EXT e 
SET e.PROPOSAL_NUMBER=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.PROPOSAL_NUMBER=r_eps.PROPOSAL_NUMBER;
                                                                                      
                                                                                        
UPDATE PROTOCOL_FUNDING_SOURCE e 
SET e.FUNDING_SOURCE=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.FUNDING_SOURCE=r_eps.PROPOSAL_NUMBER
AND e.FUNDING_SOURCE_TYPE_CODE=1 ; 

UPDATE questionnaire_answer_header e 
SET e.module_item_key=r_eps.NEW_PROPOSAL_NUMBER
WHERE e.module_item_key=r_eps.PROPOSAL_NUMBER
AND e.module_item_code = 3 ; 

EXCEPTION
WHEN OTHERS THEN
dbms_output.put_line('OLD_PROPOSAL:'|| r_eps.PROPOSAL_NUMBER||'  '||'NEW_PROPOSAL:'|| r_eps.NEW_PROPOSAL_NUMBER ||' - '||sqlerrm);                                                                                        
END;
END LOOP;
CLOSE c_eps;
END;
/ 
commit
/                                                                    
ALTER TABLE S2S_USER_ATTACHED_FORM ENABLE CONSTRAINT FK1_S2S_USER_ATTACHED_FORM ;
ALTER TABLE S2S_APP_ATTACHMENTS ENABLE CONSTRAINT FK_S2S_APP_ATTACHMENTS_KRA ;
ALTER TABLE BUDGET_PERSONS ENABLE CONSTRAINT FK_BUDGET_PERSONS_HIER ;
ALTER TABLE EPS_PROP_YNQ ENABLE CONSTRAINT FK_EPS_PROP_YNQ_KRA ;
ALTER TABLE EPS_PROP_PER_CREDIT_SPLIT ENABLE CONSTRAINT FK1_EPS_PROP_PER_CREDIT_SPLIT ;
ALTER TABLE NARRATIVE ENABLE CONSTRAINT FK_NARRATIVE_KRA ;
ALTER TABLE EPS_PROP_USER_ROLES ENABLE CONSTRAINT FK_EPS_PROP_USER_ROLES_KRA ;
ALTER TABLE EPS_PROP_SCIENCE_KEYWORD ENABLE CONSTRAINT FK_EPS_PROP_SCI_KWD_HIER ;
ALTER TABLE EPS_PROP_SCIENCE_KEYWORD ENABLE CONSTRAINT FK_EPS_PROP_SCIE_KEY_PROP_KRA ;
ALTER TABLE BUDGET_DETAILS ENABLE CONSTRAINT FK_BUDGET_DETAILS_HIER ;
ALTER TABLE EPS_PROPOSAL ENABLE CONSTRAINT EPS_PROPOSAL_FK1 ;
ALTER TABLE S2S_OPP_FORMS ENABLE CONSTRAINT FK_S2S_OPP_FORMS_KRA ;
ALTER TABLE S2S_APPLICATION ENABLE CONSTRAINT FK_S2S_APPLICATION_KRA ;
ALTER TABLE EPS_PROP_SPECIAL_REVIEW ENABLE CONSTRAINT FK_EPS_PROP_SPEC_RVW_HIER ;
ALTER TABLE EPS_PROP_LOCATION ENABLE CONSTRAINT FK_EPS_PROP_LOCATION_KRA ;
ALTER TABLE S2S_OPPORTUNITY ENABLE CONSTRAINT FK_S2S_OPPORTUNITY_KRA2 ;
ALTER TABLE EPS_PROP_SPECIAL_REVIEW ENABLE CONSTRAINT FK_EPS_PROP_SPECIAL_REVIEW_KRA ;
ALTER TABLE EPS_PROP_SITES ENABLE CONSTRAINT FK_EPS_PROP_SITES1 ;
ALTER TABLE EPS_PROP_ABSTRACT ENABLE CONSTRAINT FK_EPS_PROP_ABSTRACT_KRA ;
ALTER TABLE NARRATIVE ENABLE CONSTRAINT FK_NARRATIVE_HIER ;
ALTER TABLE S2S_APP_SUBMISSION ENABLE CONSTRAINT FK_S2S_APP_SUBMISSION_KRA ;
ALTER TABLE EPS_PROP_PERSON ENABLE CONSTRAINT FK_EPS_PROP_PERSON_HIER ;
ALTER TABLE EPS_PROPOSAL_BUDGET_STATUS ENABLE CONSTRAINT FK_EPS_PROP_BUDGET_STATUS_KRA ;
ALTER TABLE EPS_PROP_UNIT_CREDIT_SPLIT ENABLE CONSTRAINT FK1_EPS_PROP_UNIT_CREDIT_SPLIT ;
ALTER TABLE PROPOSAL_ADMIN_DETAILS ENABLE CONSTRAINT FK_PROPOSAL_ADMIN_DETAILS_1 ;
ALTER TABLE NARRATIVE_ATTACHMENT ENABLE CONSTRAINT FK_NARRATIVE_ATTACHMENT_KRA;
ALTER TABLE EPS_PROP_EXEMPT_NUMBER ENABLE CONSTRAINT FK_EPS_PROP_SPECIAL_REVIEW;
ALTER TABLE NARRATIVE_USER_RIGHTS ENABLE CONSTRAINT FK_NARRATIVE_USER_RIGHTS_KRA
/
