DECLARE
li_count number(4,0);
ls_award_number VARCHAR2(12);
li_seq number(4,0);

CURSOR c_awd IS
SELECT AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER FROM AWARD
ORDER BY AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER;
r_awd c_awd%ROWTYPE;

CURSOR c_awd_comment(as_awd varchar2,as_seq number) IS
SELECT AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,COMMENT_TYPE_CODE,CHECKLIST_PRINT_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,COMMENTS FROM AWARD_COMMENT
WHERE AWARD_NUMBER=as_awd AND SEQUENCE_NUMBER=(SELECT MAX(ac.SEQUENCE_NUMBER) FROM AWARD_COMMENT ac WHERE ac.AWARD_NUMBER=as_awd AND ac.SEQUENCE_NUMBER<as_seq);
r_awd_comment c_awd_comment%ROWTYPE;

BEGIN

IF c_awd%ISOPEN THEN
CLOSE c_awd;
END IF;
OPEN c_awd;
LOOP
FETCH c_awd INTO r_awd;
EXIT WHEN c_awd% NOTFOUND;

ls_award_number:=r_awd.AWARD_NUMBER;
li_seq:=r_awd.SEQUENCE_NUMBER;

IF c_awd_comment%ISOPEN THEN
CLOSE c_awd_comment;
END IF;
OPEN c_awd_comment(ls_award_number,li_seq);
LOOP
FETCH c_awd_comment INTO r_awd_comment;
EXIT WHEN c_awd_comment% NOTFOUND;

SELECT COUNT(*) INTO li_count FROM AWARD_COMMENT WHERE AWARD_NUMBER=r_awd.AWARD_NUMBER AND SEQUENCE_NUMBER=r_awd.SEQUENCE_NUMBER  AND COMMENT_TYPE_CODE=r_awd_comment.COMMENT_TYPE_CODE;

IF li_count=0 THEN

INSERT INTO AWARD_COMMENT(AWARD_COMMENT_ID,AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,COMMENT_TYPE_CODE,CHECKLIST_PRINT_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,COMMENTS)
VALUES(SEQ_AWARD_COMMENT_ID.NEXTVAL,r_awd.AWARD_ID,r_awd.AWARD_NUMBER,r_awd.SEQUENCE_NUMBER,r_awd_comment.COMMENT_TYPE_CODE,r_awd_comment.CHECKLIST_PRINT_FLAG,r_awd_comment.UPDATE_TIMESTAMP,r_awd_comment.UPDATE_USER,1,SYS_GUID(),r_awd_comment.COMMENTS);

commit;
END IF;

END LOOP;
CLOSE c_awd_comment;
END LOOP;
CLOSE c_awd;
END;
/