SET DEFINE OFF
/
UPDATE ATTACHMENT_FILE SET FILE_NAME = REGEXP_REPLACE(FILE_NAME,'[^[a-z,A-Z,0-9,chr(0)-chr(127)]]*','_')
/ 
UPDATE NARRATIVE_ATTACHMENT SET FILE_NAME = REGEXP_REPLACE(FILE_NAME,'[^[a-z,A-Z,0-9,chr(0)-chr(127)]]*','_')
/ 
UPDATE PROPOSAL_ATTACHMENTS SET FILE_NAME = REGEXP_REPLACE(FILE_NAME,'[^[a-z,A-Z,0-9,chr(0)-chr(127)]]*','_')
/ 
UPDATE SUBAWARD_ATTACHMENTS SET FILE_NAME = REGEXP_REPLACE(FILE_NAME,'[^[a-z,A-Z,0-9,chr(0)-chr(127)]]*','_')
/ 
commit
/