UPDATE PROPOSAL p
SET p.MAIL_BY=(SELECT m.MAIL_BY_CODE FROM MAIL_BY m
WHERE p.MAIL_BY=SUBSTR(m.DESCRIPTION,1,1))
/
UPDATE PROPOSAL p
SET p.MAIL_TYPE=(SELECT m.MAIL_TYPE FROM MAIL_TYPE m
WHERE p.MAIL_TYPE=SUBSTR(m.DESCRIPTION,1,1))
/
commit
/