DROP TABLE V_SUBAWARDCLOSE
/
TRUNCATE TABLE SUBAWARD_CLOSEOUT
/
DROP TABLE TEMP_SUBAWD_CLOSE
/
CREATE TABLE V_SUBAWARDCLOSE 
   (KUALI_SUBAWD NUMBER, 
	KUALI_SEQUENCE_NUMBER NUMBER(4,0), 
	CHANGED CHAR(1 BYTE), 
	MIT_SEQUENCE_NUMBER NUMBER(4,0), 
	SEQUENCE_NUMBER NUMBER(4,0), 
	SUBCONTRACT_CODE VARCHAR2(20 BYTE), 
	SUBAWARD_ID NUMBER(12,0), 
	CLOSEOUT_NUMBER NUMBER(3,0), 
	CLOSEOUT_TYPE_CODE NUMBER(3,0), 
	DATE_REQUESTED DATE, 
	DATE_FOLLOWUP DATE, 
	DATE_RECEIVED DATE, 
	COMMENTS VARCHAR2(1000 BYTE), 
	UPDATE_TIMESTAMP DATE, 
	UPDATE_USER VARCHAR2(8 BYTE))
/
INSERT INTO V_SUBAWARDCLOSE(KUALI_SUBAWD,KUALI_SEQUENCE_NUMBER,CHANGED,MIT_SEQUENCE_NUMBER,SEQUENCE_NUMBER,SUBCONTRACT_CODE,SUBAWARD_ID,CLOSEOUT_NUMBER,CLOSEOUT_TYPE_CODE,DATE_REQUESTED,DATE_FOLLOWUP,DATE_RECEIVED,COMMENTS,UPDATE_TIMESTAMP,UPDATE_USER)   
select  to_number(l.MODULE_ITEM_KEY) kuali_subawd,l.kuali_sequence_number,l.changed,a.sequence_number  Mit_sequence_number,a.sequence_number,a.SUBCONTRACT_CODE,aw.SUBAWARD_ID,a.CLOSEOUT_NUMBER,a.CLOSEOUT_TYPE_CODE,a.DATE_REQUESTED,a.DATE_FOLLOWUP,a.DATE_RECEIVED,a.COMMENTS,a.update_timestamp,a.update_user 
from TEMP_SEQ_LOG l
Left outer join OSP$SUBCONTRACT_CLOSEOUT@Coeus.Kuali a on l.module_item_key=a.SUBCONTRACT_CODE and l.mit_sequence_number=a.sequence_number inner join SUBAWARD aw on aw.SUBAWARD_CODE=to_number(l.MODULE_ITEM_KEY) and aw.SEQUENCE_NUMBER=l.KUALI_SEQUENCE_NUMBER where
l.MODULE='SAWD'
/
CREATE INDEX V_SUBAWARDCLOSE_I1 ON V_SUBAWARDCLOSE(kuali_subawd,KUALI_SEQUENCE_NUMBER)
/
CREATE TABLE TEMP_SUBAWD_CLOSE 
   (KUALI_SUBAWD NUMBER, 
	KUALI_SEQUENCE_NUMBER NUMBER, 
	SEQUENC NUMBER(4,0))
/
INSERT INTO TEMP_SUBAWD_CLOSE(KUALI_SUBAWD,KUALI_SEQUENCE_NUMBER,SEQUENC)   
select kuali_subawd,(
select max(aw.KUALI_SEQUENCE_NUMBER) from V_SUBAWARDCLOSE aw where aw.kuali_subawd=v.kuali_subawd
and aw.KUALI_SEQUENCE_NUMBER<=v.KUALI_SEQUENCE_NUMBER and aw.SUBCONTRACT_CODE is not null)  as kuali_sequence_number,v.KUALI_SEQUENCE_NUMBER SEQUENC  from V_SUBAWARDCLOSE v  where v.SUBCONTRACT_CODE is null
/
commit
/
CREATE INDEX temp_subawd_close_I1 ON temp_subawd_close(kuali_subawd,kuali_sequence_number)
/
commit
/
INSERT INTO SUBAWARD_CLOSEOUT(SUBAWARD_CLOSEOUT_ID,SUBAWARD_ID,CLOSEOUT_NUMBER,CLOSEOUT_TYPE_CODE,DATE_REQUESTED,DATE_FOLLOWUP,DATE_RECEIVED,COMMENTS,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,SEQUENCE_NUMBER,SUBAWARD_CODE)
SELECT SUBAWARD_CLOSEOUT_ID_S.NEXTVAL,sc.SUBAWARD_ID,NULL,sc.CLOSEOUT_TYPE_CODE,sc.DATE_REQUESTED,sc.DATE_FOLLOWUP,sc.DATE_RECEIVED,sc.COMMENTS,sc.UPDATE_TIMESTAMP,sc.UPDATE_USER,1,sys_guid(),sc.kuali_sequence_number,sc.kuali_subawd 
FROM V_SUBAWARDCLOSE sc  where sc.SUBCONTRACT_CODE IS NOT NULL
/
commit
/
INSERT INTO SUBAWARD_CLOSEOUT(SUBAWARD_CLOSEOUT_ID,SUBAWARD_ID,CLOSEOUT_NUMBER,CLOSEOUT_TYPE_CODE,DATE_REQUESTED,DATE_FOLLOWUP,DATE_RECEIVED,COMMENTS,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,SEQUENCE_NUMBER,SUBAWARD_CODE)
SELECT SUBAWARD_CLOSEOUT_ID_S.NEXTVAL,sc.SUBAWARD_ID,NULL,sc.CLOSEOUT_TYPE_CODE,sc.DATE_REQUESTED,sc.DATE_FOLLOWUP,sc.DATE_RECEIVED,sc.COMMENTS,sc.UPDATE_TIMESTAMP,sc.UPDATE_USER,1,sys_guid(),v2.SEQUENC,sc.kuali_subawd 
FROM V_SUBAWARDCLOSE sc inner join
temp_subawd_close v2 on sc.kuali_subawd=v2.kuali_subawd and sc.sequence_number=v2.kuali_sequence_number
/
commit
/
update SUBAWARD_CLOSEOUT pp set pp.SUBAWARD_id = (select p.SUBAWARD_id from SUBAWARD p where
												p.SUBAWARD_CODE = pp.SUBAWARD_CODE
												and p.sequence_number = pp.sequence_number)
where exists (select p.SUBAWARD_id from SUBAWARD p where p.SUBAWARD_CODE = pp.SUBAWARD_CODE 
				and p.sequence_number = pp.sequence_number)
/
