Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1193',sys_guid(),1,'KC10011','874','Y');
Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1194',sys_guid(),1,'KC10011','872','Y');
Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1195',sys_guid(),1,'KC10011','893','Y');
Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1196',sys_guid(),1,'KC10011','849','Y');
Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1197',sys_guid(),1,'KC10011','850','Y');
Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1198',sys_guid(),1,'KC10011','982','Y');
Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1199',sys_guid(),1,'KC10011','848','Y');
Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1200',sys_guid(),1,'KC10011','851','Y');
Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1201',sys_guid(),1,'KC10011','871','Y');
Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1202',sys_guid(),1,'KC10011','KC1115','Y');
Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1203',sys_guid(),1,'KC10011','846','Y');
Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1204',sys_guid(),1,'KC10011','1029','Y');
Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1205',sys_guid(),1,'KC10011','1030','Y');
Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1206',sys_guid(),1,'KC10011','861','Y');
Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1207',sys_guid(),1,'KC10011','862','Y');
Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1208',sys_guid(),1,'KC10011','1114','Y');
Insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND) values ('KC1209',sys_guid(),1,'KC10011','860','Y');
INSERT INTO KRIM_ROLE_PERM_T(ROLE_PERM_ID,OBJ_ID,VER_NBR,ROLE_ID,PERM_ID,ACTV_IND)
VALUES(KRIM_ROLE_PERM_ID_S.nextval,sys_guid(),1,'KC10011',(select perm_id from krim_perm_t where nm = 'NOTIFY_PROPOSAL_PERSONS'),'Y');
commit
/
