truncate table valid_ce_rate_types
/
alter table INSTITUTE_RATES disable constraint FK_INSTITUTE_RATES_KRA
/
alter table RATE_CLASS_BASE_INCLUSION disable constraint FK_RATE_CLASS_BASE_INCL
/
delete from RATE_TYPE
/
delete from RATE_CLASS
/
INSERT INTO RATE_CLASS(RATE_CLASS_CODE,DESCRIPTION,RATE_CLASS_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT RATE_CLASS_CODE,DESCRIPTION,RATE_CLASS_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM OSP$RATE_CLASS@coeus.kuali
/
INSERT INTO RATE_CLASS (RATE_CLASS_CODE,DESCRIPTION,RATE_CLASS_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
VALUES('13','MTDC - AWARD','O',sysdate,'admin',1,sys_guid())
/
INSERT INTO RATE_TYPE(RATE_CLASS_CODE,RATE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
select rt. RATE_CLASS_CODE,rt.RATE_TYPE_CODE,rt.DESCRIPTION,rt.UPDATE_TIMESTAMP,rt.UPDATE_USER,1,SYS_GUID() from osp$rate_type@coeus.kuali rt
/
INSERT INTO RATE_TYPE (RATE_CLASS_CODE,RATE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
select 13,IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() from OSP$IDC_RATE_TYPE@coeus.kuali
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
select coe.COST_ELEMENT,coe.RATE_CLASS_CODE,coe.RATE_TYPE_CODE,'Y',coe.UPDATE_TIMESTAMP,coe.UPDATE_USER,1,SYS_GUID()
from OSP$VALID_CE_RATE_TYPES@coeus.kuali coe
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','1',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','5',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
/                  
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','6',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
/                   
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','9',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
/                    
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','15',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
/                    
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','16',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','25',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
/                    
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','26',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','28',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','31',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','27',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','10',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','17',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','24',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=1
/                    
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','13',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=1
/                    
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','10',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=2
/                    
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','17',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=2
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','24',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=2
/                    
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','13',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=2
/                    
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','10',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=3
/                    
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','17',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=3
/                    
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','24',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=3
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','13',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=3
/                    
commit
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00300',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400300'
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00025',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400025'
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00005',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400005'
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00390',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400390'
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00350',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400350'
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00706',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400706'
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00754',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400754'
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00250',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400250'
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00001',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400496'
/
commit
/
alter table INSTITUTE_RATES enable constraint FK_INSTITUTE_RATES_KRA
/
alter table RATE_CLASS_BASE_INCLUSION enable constraint FK_RATE_CLASS_BASE_INCL
/
