INSERT INTO REPORT_STATUS(REPORT_STATUS_CODE,DESCRIPTION,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT REPORT_STATUS_CODE,DESCRIPTION,'Y',UPDATE_TIMESTAMP,UPDATE_USER,1,SYS_GUID() FROM OSP$REPORT_STATUS@coeus.kuali 
WHERE REPORT_STATUS_CODE NOT IN(SELECT REPORT_STATUS_CODE FROM REPORT_STATUS);
commit;
/