INSERT INTO COMMENT_TYPE(COMMENT_TYPE_CODE,DESCRIPTION,TEMPLATE_FLAG,CHECKLIST_FLAG,AWARD_COMMENT_SCREEN_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COMMENT_CODE+4,DESCRIPTION,TEMPLATE_FLAG,CHECKLIST_FLAG,AWARD_COMMENT_SCREEN_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,SYS_GUID() FROM OSP$COMMENT@coeus.kuali
WHERE DESCRIPTION IN('ARRA Award Description','ARRA Quarterly Activities');