DECLARE

CURSOR c_closeout IS 
SELECT a.AWARD_NUMBER,a.SEQUENCE_NUMBER,a.REPORT_CLASS_CODE,a.REPORT_CODE,a.FREQUENCY_CODE,a.FREQUENCY_BASE_CODE,a.OSP_DISTRIBUTION_CODE,a.DUE_DATE FROM AWARD_REPORT_TERMS a
INNER JOIN (SELECT distinct award_number,sequence_number from award_closeout) b
ON a.AWARD_NUMBER=b.AWARD_NUMBER
AND a.SEQUENCE_NUMBER=b.SEQUENCE_NUMBER
WHERE a.REPORT_CLASS_CODE IN('1','2','3','4') AND
REPORT_CODE=5 AND FREQUENCY_CODE=12 AND FREQUENCY_BASE_CODE=4 AND OSP_DISTRIBUTION_CODE=1;
r_closeout c_closeout%rowtype;

BEGIN
IF c_closeout%ISOPEN THEN
CLOSE c_closeout;
END IF;

OPEN c_closeout;
LOOP
FETCH c_closeout INTO r_closeout;
EXIT WHEN c_closeout%NOTFOUND;
 IF r_closeout.REPORT_CLASS_CODE=3 THEN

UPDATE AWARD_CLOSEOUT
SET DUE_DATE=r_closeout.DUE_DATE
WHERE AWARD_NUMBER=r_closeout.award_number
AND SEQUENCE_NUMBER=r_closeout.SEQUENCE_NUMBER
AND CLOSEOUT_REPORT_CODE=3;

ELSIF r_closeout.REPORT_CLASS_CODE=2 THEN

UPDATE AWARD_CLOSEOUT
SET DUE_DATE=r_closeout.DUE_DATE
WHERE AWARD_NUMBER=r_closeout.award_number
AND SEQUENCE_NUMBER=r_closeout.SEQUENCE_NUMBER
AND CLOSEOUT_REPORT_CODE=2;

ELSIF r_closeout.REPORT_CLASS_CODE=4 THEN

UPDATE AWARD_CLOSEOUT
SET DUE_DATE=r_closeout.DUE_DATE
WHERE AWARD_NUMBER=r_closeout.award_number
AND SEQUENCE_NUMBER=r_closeout.SEQUENCE_NUMBER
AND CLOSEOUT_REPORT_CODE=4;

ELSIF r_closeout.REPORT_CLASS_CODE=1 THEN

UPDATE AWARD_CLOSEOUT
SET DUE_DATE=r_closeout.DUE_DATE
WHERE AWARD_NUMBER=r_closeout.award_number
AND SEQUENCE_NUMBER=r_closeout.SEQUENCE_NUMBER
AND CLOSEOUT_REPORT_CODE=1;

END IF;
END LOOP;
CLOSE c_closeout;
END;
/