TRUNCATE TABLE INSTITUTE_RATES
/
INSERT INTO INSTITUTE_RATES(RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,'Y',RATE,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM OSP$INSTITUTE_RATES@coeus.kuali
/
TRUNCATE TABLE INSTITUTE_LA_RATES
/
INSERT INTO INSTITUTE_LA_RATES(UNIT_NUMBER,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,RATE_CLASS_CODE,ACTIVE_FLAG,RATE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT UNIT_NUMBER,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,RATE_CLASS_CODE,'Y',RATE,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM OSP$INSTITUTE_LA_RATES@coeus.kuali
/
DECLARE

CURSOR c_inst IS
SELECT a.RATE_CLASS_CODE,a.RATE_TYPE_CODE,a.ACTIVITY_TYPE_CODE,a.FISCAL_YEAR,a.START_DATE,a.ON_OFF_CAMPUS_FLAG,a.UNIT_NUMBER,a.ACTIVE_FLAG,a.RATE FROM
(
SELECT '13' RATE_CLASS_CODE,'1' RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE from INSTITUTE_RATES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
UNION ALL
SELECT '13' RATE_CLASS_CODE,'5' RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE from INSTITUTE_RATES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
UNION ALL
SELECT '13' RATE_CLASS_CODE,'6' RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE from INSTITUTE_RATES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
UNION ALL
SELECT '13' RATE_CLASS_CODE,'9' RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE from INSTITUTE_RATES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
UNION ALL
SELECT '13' RATE_CLASS_CODE,'15' RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE from INSTITUTE_RATES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
UNION ALL
SELECT '13' RATE_CLASS_CODE,'16' RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE from INSTITUTE_RATES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
UNION ALL
SELECT '13' RATE_CLASS_CODE,'25' RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE from INSTITUTE_RATES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
UNION ALL
SELECT '13' RATE_CLASS_CODE,'26' RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE from INSTITUTE_RATES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
UNION ALL
SELECT '13' RATE_CLASS_CODE,'28' RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE from INSTITUTE_RATES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
UNION ALL
SELECT '13' RATE_CLASS_CODE,'31' RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE from INSTITUTE_RATES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
UNION ALL
SELECT '13' RATE_CLASS_CODE,'27' RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE from INSTITUTE_RATES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
UNION ALL
SELECT '13' RATE_CLASS_CODE,'10' RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE from INSTITUTE_RATES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE IN(1,2,3)
UNION ALL
SELECT '13' RATE_CLASS_CODE,'17' RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE from INSTITUTE_RATES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE IN(1,2,3)
UNION ALL
SELECT '13' RATE_CLASS_CODE,'24' RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE from INSTITUTE_RATES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE IN(1,2,3)
UNION ALL
SELECT '13' RATE_CLASS_CODE,'13' RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE from INSTITUTE_RATES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE IN(1,2,3)
) a;
r_inst c_inst%ROWTYPE;

BEGIN
IF c_inst%ISOPEN THEN
CLOSE c_inst;
END IF;
OPEN c_inst;
LOOP
FETCH c_inst INTO r_inst;
EXIT WHEN c_inst%NOTFOUND;

BEGIN
INSERT INTO INSTITUTE_RATES(RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVITY_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,ACTIVE_FLAG,RATE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
VALUES(r_inst.RATE_CLASS_CODE,r_inst.RATE_TYPE_CODE,r_inst.ACTIVITY_TYPE_CODE,r_inst.FISCAL_YEAR,r_inst.START_DATE,r_inst.ON_OFF_CAMPUS_FLAG,r_inst.UNIT_NUMBER,r_inst.ACTIVE_FLAG,r_inst.RATE,sysdate,'admin',1,sys_guid());
EXCEPTION
WHEN OTHERS THEN
continue;
END;

END LOOP;
CLOSE c_inst;
END;
/
DECLARE

CURSOR c_inst IS
SELECT a.UNIT_NUMBER,a.RATE_TYPE_CODE,a.FISCAL_YEAR,a.START_DATE,a.ON_OFF_CAMPUS_FLAG,a.RATE_CLASS_CODE,a.ACTIVE_FLAG,a.RATE FROM
(
SELECT UNIT_NUMBER,'1' RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,'13' RATE_CLASS_CODE,ACTIVE_FLAG,RATE FROM INSTITUTE_LA_RATES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
UNION ALL
SELECT UNIT_NUMBER,'5' RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,'13' RATE_CLASS_CODE,ACTIVE_FLAG,RATE FROM INSTITUTE_LA_RATES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
UNION ALL
SELECT UNIT_NUMBER,'6' RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,'13' RATE_CLASS_CODE,ACTIVE_FLAG,RATE FROM INSTITUTE_LA_RATES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
UNION ALL
SELECT UNIT_NUMBER,'9' RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,'13' RATE_CLASS_CODE,ACTIVE_FLAG,RATE FROM INSTITUTE_LA_RATES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
UNION ALL
SELECT UNIT_NUMBER,'15' RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,'13' RATE_CLASS_CODE,ACTIVE_FLAG,RATE FROM INSTITUTE_LA_RATES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
UNION ALL
SELECT UNIT_NUMBER,'16' RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,'13' RATE_CLASS_CODE,ACTIVE_FLAG,RATE FROM INSTITUTE_LA_RATES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
UNION ALL
SELECT UNIT_NUMBER,'25' RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,'13' RATE_CLASS_CODE,ACTIVE_FLAG,RATE FROM INSTITUTE_LA_RATES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
UNION ALL
SELECT UNIT_NUMBER,'26' RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,'13' RATE_CLASS_CODE,ACTIVE_FLAG,RATE FROM INSTITUTE_LA_RATES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
UNION ALL
SELECT UNIT_NUMBER,'28' RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,'13' RATE_CLASS_CODE,ACTIVE_FLAG,RATE FROM INSTITUTE_LA_RATES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
UNION ALL
SELECT UNIT_NUMBER,'31' RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,'13' RATE_CLASS_CODE,ACTIVE_FLAG,RATE FROM INSTITUTE_LA_RATES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
UNION ALL
SELECT UNIT_NUMBER,'27' RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,'13' RATE_CLASS_CODE,ACTIVE_FLAG,RATE FROM INSTITUTE_LA_RATES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
UNION ALL
SELECT UNIT_NUMBER,'10' RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,'13' RATE_CLASS_CODE,ACTIVE_FLAG,RATE FROM INSTITUTE_LA_RATES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE IN(1,2,3)
UNION ALL
SELECT UNIT_NUMBER,'17' RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,'13' RATE_CLASS_CODE,ACTIVE_FLAG,RATE FROM INSTITUTE_LA_RATES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE IN(1,2,3)
UNION ALL
SELECT UNIT_NUMBER,'24' RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,'13' RATE_CLASS_CODE,ACTIVE_FLAG,RATE FROM INSTITUTE_LA_RATES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE IN(1,2,3)
UNION ALL
SELECT UNIT_NUMBER,'13' RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,'13' RATE_CLASS_CODE,ACTIVE_FLAG,RATE FROM INSTITUTE_LA_RATES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE IN(1,2,3)
) a;
r_inst c_inst%ROWTYPE;

BEGIN
IF c_inst%ISOPEN THEN
CLOSE c_inst;
END IF;
OPEN c_inst;
LOOP
FETCH c_inst INTO r_inst;
EXIT WHEN c_inst%NOTFOUND;

BEGIN
INSERT INTO INSTITUTE_LA_RATES(UNIT_NUMBER,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,RATE_CLASS_CODE,ACTIVE_FLAG,RATE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
VALUES(r_inst.UNIT_NUMBER,r_inst.RATE_TYPE_CODE,r_inst.FISCAL_YEAR,r_inst.START_DATE,r_inst.ON_OFF_CAMPUS_FLAG,r_inst.RATE_CLASS_CODE,r_inst.ACTIVE_FLAG,r_inst.RATE,sysdate,'admin',1,sys_guid());
EXCEPTION
WHEN OTHERS THEN
continue;
END;

END LOOP;
CLOSE c_inst;
END;
/
commit
/
