CREATE OR REPLACE FORCE VIEW NOVI_NDA_SURVEY_RESP 
  (SURVEYRESPONSEID, QUESTION_DESC, ANSWER, PAGEINDEX, QUESTIONINDEX) AS 
  select q.SURVEYRESPONSEID, EL.ELEMENTTITLE,   
decode(e.ELEMENTTYPE ,'OPEN_ENDED', q.RESPONSEVALUE, AL.ANSWERTEXT) as answertext,
sp.POSINDEX, E.POSINDEX
from questionresponse@NOVI.MIT.EDU q, answer@NOVI.MIT.EDU a, answerloc@NOVI.MIT.EDU al, 
element@NOVI.MIT.EDU e, elementloc@NOVI.MIT.EDU el, surveypage@NOVI.MIT.EDU sp
where q.SURVEYRESPONSEID in (
        select SR.SURVEYRESPONSEID
        from surveyresponse@NOVI.MIT.EDU sr, surveypage@NOVI.MIT.EDU sp, survey@NOVI.MIT.EDU s
        where s.SURVEYID = 'edb1385874ee465cb7d81665d9718682'
        and S.SURVEYID = SP.SURVEYID
        and SP.SURVEYPAGEID = SR.SURVEYPAGEID)
and q.ANSWERID = A.ANSWERID
and A.ANSWERID = AL.ANSWERID
and A.ELEMENTID = E.ELEMENTID
and E.ELEMENTID = EL.ELEMENTID
and e.SURVEYPAGEID = sp.SURVEYPAGEID
order by q.SURVEYRESPONSEID, sp.POSINDEX, E.POSINDEX
/
