CREATE TABLE TEMP_REP_TERMS_RECNT 
   (CONTACT_ID NUMBER(12,0), 
	AWARD_REP_TERMS_RECNT_ID NUMBER(12,0), 
	AWARD_REPORT_TERMS_ID NUMBER(12,0), 
	CONTACT_TYPE_CODE VARCHAR2(3), 
	ROLODEX_ID NUMBER(6,0), 
	NUMBER_OF_COPIES NUMBER(2,0), 
	VER_NBR NUMBER(8,0), 
	UPDATE_TIMESTAMP DATE, 
	UPDATE_USER VARCHAR2(60) , 
	OBJ_ID VARCHAR2(36))
/	
INSERT INTO TEMP_REP_TERMS_RECNT(AWARD_REP_TERMS_RECNT_ID,CONTACT_ID,AWARD_REPORT_TERMS_ID,CONTACT_TYPE_CODE,ROLODEX_ID,NUMBER_OF_COPIES,VER_NBR,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
SELECT SEQ_AWARD_REP_TERMS_RECNT_ID.NEXTVAL,NULL,Ta.AWARD_REPORT_TERMS_ID,T.CONTACT_TYPE_CODE,T.ROLODEX_ID,T.NUMBER_OF_COPIES,T.VER_NBR,T.UPDATE_TIMESTAMP,T.UPDATE_USER,T.OBJ_ID 
FROM  TEMP_AWARD_REPORT_RCNT T INNER JOIN TEMP_AWARD_REPORT Ta
ON T.AWARD_NUMBER=Ta.AWARD_NUMBER AND T.SEQUENCE_NUMBER=Ta.SEQUENCE_NUMBER AND T.REPORT_CLASS_CODE=Ta.REPORT_CLASS_CODE
AND T.FREQUENCY_CODE=Ta.FREQUENCY_CODE
AND T.FREQUENCY_BASE_CODE=Ta.FREQUENCY_BASE_CODE
AND T.OSP_DISTRIBUTION_CODE=Ta.OSP_DISTRIBUTION_CODE 
/
commit
/
create index TEMP_REP_TERMS_RECNT_I1 on TEMP_REP_TERMS_RECNT(AWARD_REPORT_TERMS_ID)
/
commit
/
declare
li_count number;
li_num number;
cursor c_rep is
select award_report_terms_id from award_report_terms;
r_rep c_rep%rowtype;

begin
if c_rep%isopen then
close c_rep;
end if;
open c_rep;
loop
fetch c_rep into r_rep;
exit when c_rep%notfound;

select count(award_report_terms_id) into li_count from  AWARD_REP_TERMS_RECNT where award_report_terms_id=r_rep.award_report_terms_id;
select count(award_report_terms_id) into li_num from AWARD_REPORT_TERMS where AWARD_REPORT_TERMS_ID=r_rep.award_report_terms_id;

if li_count=0 and li_num<>0 then

 

   begin
   INSERT INTO AWARD_REP_TERMS_RECNT(AWARD_REP_TERMS_RECNT_ID,CONTACT_ID,AWARD_REPORT_TERMS_ID,CONTACT_TYPE_CODE,ROLODEX_ID,NUMBER_OF_COPIES,VER_NBR,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
   SELECT AWARD_REP_TERMS_RECNT_ID,CONTACT_ID,AWARD_REPORT_TERMS_ID,CONTACT_TYPE_CODE,ROLODEX_ID,NUMBER_OF_COPIES,VER_NBR,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID 
   FROM  TEMP_REP_TERMS_RECNT 
   WHERE AWARD_REPORT_TERMS_ID=r_rep.award_report_terms_id;
   
   exception
   when others then
   dbms_output.put_line(r_rep.award_report_terms_id);
   end;

end if;
end loop;
close c_rep;
end;
/
commit
/
drop table TEMP_REP_TERMS_RECNT
/
drop index TEMP_REP_TERMS_RECNT_I1
/