UPDATE NEGOTIATION_ACTIVITY a
SET a.START_DATE=( SELECT n.ACTIVITY_DATE FROM(
SELECT tn.NEGOTIATION_ACTIVITY_ID,cn.ACTIVITY_DATE
FROM OSP$NEGOTIATION_ACTIVITIES@Coeus.Kuali cn INNER JOIN TEMP_NEGOTIATION_ACT_ID tn 
ON cn.NEGOTIATION_NUMBER=tn.NEGOTIATION_NUMBER AND cn.ACTIVITY_NUMBER=tn.ACTIVITY_NUMBER) n
WHERE a.NEGOTIATION_ACTIVITY_ID=n.NEGOTIATION_ACTIVITY_ID)
/
commit
/
