DECLARE
li_count number;
BEGIN
   select count(*) into li_count  from user_tables where table_name='OSP$BUDGET_SUB_AWARDS';
   IF li_count=0 THEN
     execute immediate('CREATE TABLE OSP$BUDGET_SUB_AWARDS(	
	                    PROPOSAL_NUMBER VARCHAR2(8 BYTE) NOT NULL ENABLE, 
                        VERSION_NUMBER NUMBER(3,0) NOT NULL ENABLE, 
                        SUB_AWARD_NUMBER NUMBER(3,0) NOT NULL ENABLE, 
                        ORGANIZATION_NAME VARCHAR2(60 BYTE) NOT NULL ENABLE, 
                        SUB_AWARD_STATUS_CODE NUMBER(3,0) NOT NULL ENABLE, 
                        SUB_AWARD_XFD_FILE BLOB DEFAULT EMPTY_BLOB(), 
                        SUB_AWARD_XFD_FILE_NAME VARCHAR2(256 BYTE), 
                        COMMENTS VARCHAR2(2000 BYTE), 
                        XFD_UPDATE_USER VARCHAR2(8 BYTE), 
                        XFD_UPDATE_TIMESTAMP DATE, 
                        SUB_AWARD_XML_FILE CLOB DEFAULT EMPTY_CLOB(), 
                        TRANSLATION_COMMENTS VARCHAR2(2000 BYTE), 
                        XML_UPDATE_USER VARCHAR2(8 BYTE), 
                        XML_UPDATE_TIMESTAMP DATE, 
                        UPDATE_TIMESTAMP DATE NOT NULL ENABLE, 
                        UPDATE_USER VARCHAR2(8 BYTE) NOT NULL ENABLE, 
                        NAMESPACE VARCHAR2(200 BYTE), 
                        FORM_NAME VARCHAR2(100 BYTE)
						)');
    END IF;
END;
/
commit
/
DECLARE
li_count number;
BEGIN
  select count(*) into li_count from OSP$BUDGET_SUB_AWARDS;
  IF li_count=0 THEN
     insert into OSP$BUDGET_SUB_AWARDS(PROPOSAL_NUMBER, VERSION_NUMBER, SUB_AWARD_NUMBER,ORGANIZATION_NAME, SUB_AWARD_STATUS_CODE, COMMENTS, XFD_UPDATE_USER, XFD_UPDATE_TIMESTAMP,  TRANSLATION_COMMENTS, XML_UPDATE_USER, XML_UPDATE_TIMESTAMP,UPDATE_TIMESTAMP, UPDATE_USER, NAMESPACE, FORM_NAME, SUB_AWARD_XFD_FILE_NAME, SUB_AWARD_XFD_FILE,SUB_AWARD_XML_FILE)
     SELECT PROPOSAL_NUMBER, VERSION_NUMBER, SUB_AWARD_NUMBER,ORGANIZATION_NAME, SUB_AWARD_STATUS_CODE, COMMENTS, XFD_UPDATE_USER, XFD_UPDATE_TIMESTAMP,  TRANSLATION_COMMENTS, XML_UPDATE_USER, XML_UPDATE_TIMESTAMP,UPDATE_TIMESTAMP, UPDATE_USER, NAMESPACE, FORM_NAME, SUB_AWARD_XFD_FILE_NAME, SUB_AWARD_XFD_FILE,SUB_AWARD_XML_FILE FROM OSP$BUDGET_SUB_AWARDS@coeus.kuali;
  END IF;
END;
/
DECLARE
li_count number;
BEGIN
   select count(*) into li_count  from user_tables where table_name='OSP$BUDGET_SUB_AWARD_ATT';
   IF li_count=0 THEN
     execute immediate('CREATE TABLE OSP$BUDGET_SUB_AWARD_ATT(                              
	                           PROPOSAL_NUMBER VARCHAR2(8 BYTE) NOT NULL ENABLE, 
                               VERSION_NUMBER NUMBER(3,0) NOT NULL ENABLE, 
                               SUB_AWARD_NUMBER NUMBER(3,0) NOT NULL ENABLE, 
                               CONTENT_ID VARCHAR2(350 BYTE) NOT NULL ENABLE, 
                               CONTENT_TYPE VARCHAR2(30 BYTE), 
                               ATTACHMENT BLOB DEFAULT EMPTY_BLOB(), 
                               UPDATE_TIMESTAMP DATE NOT NULL ENABLE, 
                               UPDATE_USER VARCHAR2(8 BYTE) NOT NULL ENABLE
							   )');
    END IF;
END;
/  

/
commit
/
DECLARE
li_count number;
BEGIN
    select count(*) into li_count from OSP$BUDGET_SUB_AWARD_ATT;
    IF li_count=0 THEN
       insert into OSP$BUDGET_SUB_AWARD_ATT(PROPOSAL_NUMBER,VERSION_NUMBER,SUB_AWARD_NUMBER,CONTENT_ID,CONTENT_TYPE,ATTACHMENT,UPDATE_TIMESTAMP,UPDATE_USER)
       SELECT  PROPOSAL_NUMBER,VERSION_NUMBER,SUB_AWARD_NUMBER,CONTENT_ID,CONTENT_TYPE,ATTACHMENT,UPDATE_TIMESTAMP,UPDATE_USER  FROM OSP$BUDGET_SUB_AWARD_ATT@coeus.kuali;
	END IF;
END;
/
commit
/
DECLARE
li_count number;
BEGIN
   select count(*) into li_count  from user_tables where table_name='ORGANIZATION_MAPPING';
   IF li_count=0 THEN
     execute immediate('CREATE TABLE ORGANIZATION_MAPPING(
							ORGANIZATION_ID	VARCHAR2(8),
							ORGANIZATION_NAME	VARCHAR2(60),
							SUBAWARD_ORGANIZATION_NAME VARCHAR2(60)
							)');
    END IF;
END;
/
DECLARE
li_count number;
BEGIN
  select count(*) into li_count from ORGANIZATION_MAPPING;
  IF li_count=0 THEN
     INSERT INTO ORGANIZATION_MAPPING(ORGANIZATION_ID,ORGANIZATION_NAME,SUBAWARD_ORGANIZATION_NAME)
     SELECT distinct o.ORGANIZATION_ID,o.ORGANIZATION_NAME,t.ORGANIZATION_NAME FROM ORGANIZATION o,OSP$BUDGET_SUB_AWARDS t
     WHERE o.ORGANIZATION_NAME like '%'||t.ORGANIZATION_NAME||'%';
   END IF;
END;
/
TRUNCATE TABLE BUDGET_SUB_AWARD_ATT
/
TRUNCATE TABLE BUDGET_SUB_AWARD_FILES
/
ALTER TABLE BUDGET_DETAILS DISABLE CONSTRAINT FK2_BUDGET_DETAILS
/
ALTER TABLE BUDGET_SUB_AWARD_FILES DISABLE CONSTRAINT FK1_BUDGET_SUB_AWARD_FILES
/
ALTER TABLE BUDGET_SUB_AWARD_PERIOD_DETAIL DISABLE CONSTRAINT FK1_BUDGET_SUBAWARD_PER_DET
/
ALTER TABLE BUDGET_SUB_AWARD_ATT DISABLE CONSTRAINT FK1_BUDGET_SUB_AWARD_ATT
/
TRUNCATE TABLE BUDGET_SUB_AWARDS
/
ALTER TABLE BUDGET_DETAILS ENABLE CONSTRAINT FK2_BUDGET_DETAILS
/
ALTER TABLE BUDGET_SUB_AWARD_FILES ENABLE CONSTRAINT FK1_BUDGET_SUB_AWARD_FILES
/
ALTER TABLE BUDGET_SUB_AWARD_PERIOD_DETAIL ENABLE CONSTRAINT FK1_BUDGET_SUBAWARD_PER_DET
/
ALTER TABLE BUDGET_SUB_AWARD_ATT ENABLE CONSTRAINT FK1_BUDGET_SUB_AWARD_ATT
/
ALTER TABLE BUDGET_SUB_AWARDS MODIFY ORGANIZATION_ID NULL
/
DECLARE
li_ver_nbr number(8);
ls_hierarchy_proposal_number varchar2(12):=null;
ls_hide_in_hierarchy  char(1):='n';
li_budget_id number(12);
li_seq_sub_awd_bgt_att_id number(12);
li_sub_award_count number;
li_sub_files_count number;
li_sub_att_count number;
li_subawd_bud_period NUMBER(12,0);
li_sub_awd_detail number;
ls_organization VARCHAR2(8);
ls_organization_name VARCHAR2(60);

CURSOR c_AWRD IS  SELECT to_number(PROPOSAL_NUMBER) PROPOSAL_NUMBER, VERSION_NUMBER, SUB_AWARD_NUMBER,ORGANIZATION_NAME, SUB_AWARD_STATUS_CODE , COMMENTS, XFD_UPDATE_USER, XFD_UPDATE_TIMESTAMP,  TRANSLATION_COMMENTS, XML_UPDATE_USER, XML_UPDATE_TIMESTAMP , UPDATE_TIMESTAMP, UPDATE_USER, NAMESPACE, FORM_NAME, nvl(SUB_AWARD_XFD_FILE_NAME,'dummy') SUB_AWARD_XFD_FILE_NAME , nvl(SUB_AWARD_XFD_FILE,EMPTY_BLOB()) SUB_AWARD_XFD_FILE,SUB_AWARD_XML_FILE FROM OSP$BUDGET_SUB_AWARDS;
r_AWRD c_AWRD%ROWTYPE;

CURSOR c_sub_awd_att is
SELECT  to_number(PROPOSAL_NUMBER) PROPOSAL_NUMBER,VERSION_NUMBER,SUB_AWARD_NUMBER,CONTENT_ID,CONTENT_TYPE,ATTACHMENT,UPDATE_TIMESTAMP,UPDATE_USER  FROM OSP$BUDGET_SUB_AWARD_ATT;
r_sub_awd_att c_sub_awd_att%rowtype;

--CURSOR c_subawd_detail IS SELECT to_number(PROPOSAL_NUMBER) PROPOSAL_NUMBER,VERSION_NUMBER,SUB_AWARD_NUMBER,BUDGET_PERIOD,DIRECT_COST,INDIRECT_COST,COST_SHARING_AMOUNT,UPDATE_TIMESTAMP,UPDATE_USER FROM OSP$BUDGET_SUB_AWARDS_DETAILS@coeus.kuali;
--r_subawd_detail c_subawd_detail%ROWTYPE;

BEGIN
li_ver_nbr:=1;

IF c_AWRD%ISOPEN THEN
CLOSE c_AWRD;
END IF;

OPEN c_AWRD;
LOOP
FETCH c_AWRD INTO r_AWRD;
EXIT WHEN c_AWRD%NOTFOUND;

BEGIN
SELECT ORGANIZATION_ID INTO ls_organization FROM ORGANIZATION_MAPPING WHERE SUBAWARD_ORGANIZATION_NAME=r_AWRD.ORGANIZATION_NAME AND rownum=1;
EXCEPTION
WHEN OTHERS THEN
ls_organization:=NULL;
END;


BEGIN

select t1.budget_id  INTO li_budget_id  from budget t1 
			inner join eps_proposal_budget_ext t2 on t1.budget_id = t2.budget_id
			where t2.proposal_number = r_AWRD.PROPOSAL_NUMBER
			and t1.version_number = r_AWRD.VERSION_NUMBER;


BEGIN
INSERT INTO BUDGET_SUB_AWARDS(SUB_AWARD_NUMBER, ORGANIZATION_ID, SUB_AWARD_STATUS_CODE, SUB_AWARD_XFD_FILE_NAME, COMMENTS, XFD_UPDATE_USER, XFD_UPDATE_TIMESTAMP, TRANSLATION_COMMENTS, XML_UPDATE_USER, XML_UPDATE_TIMESTAMP
, UPDATE_TIMESTAMP, UPDATE_USER , VER_NBR, OBJ_ID
, BUDGET_ID, HIERARCHY_PROPOSAL_NUMBER, HIDE_IN_HIERARCHY
, SUB_AWARD_XFD_FILE, SUB_AWARD_XML_FILE, NAMESPACE, FORM_NAME) 
VALUES(r_AWRD.SUB_AWARD_NUMBER,ls_organization,r_AWRD.SUB_AWARD_STATUS_CODE,r_AWRD.SUB_AWARD_XFD_FILE_NAME,r_AWRD.COMMENTS,r_AWRD.XFD_UPDATE_USER,r_AWRD.XFD_UPDATE_TIMESTAMP,r_AWRD.TRANSLATION_COMMENTS,r_AWRD.XML_UPDATE_USER,r_AWRD.XML_UPDATE_TIMESTAMP
,r_AWRD.UPDATE_TIMESTAMP,r_AWRD.UPDATE_USER, li_ver_nbr, SYS_GUID()
,li_budget_id,ls_hierarchy_proposal_number,ls_hide_in_hierarchy, --managed data
r_AWRD.SUB_AWARD_XFD_FILE,r_AWRD.SUB_AWARD_XML_FILE,r_AWRD.NAMESPACE,r_AWRD.FORM_NAME);
EXCEPTION
WHEN OTHERS THEN 
dbms_output.put_line('Exception from BUDGET_SUB_AWARDS, Sub Awrd No:'||r_AWRD.SUB_AWARD_NUMBER||'  '||sqlerrm);
END;

BEGIN
INSERT INTO BUDGET_SUB_AWARD_FILES(SUB_AWARD_NUMBER, SUB_AWARD_XFD_FILE_NAME, UPDATE_TIMESTAMP, UPDATE_USER,  SUB_AWARD_XFD_FILE, SUB_AWARD_XML_FILE
,VER_NBR, OBJ_ID
,BUDGET_ID) 
VALUES( r_AWRD.SUB_AWARD_NUMBER, r_AWRD.SUB_AWARD_XFD_FILE_NAME, r_AWRD.UPDATE_TIMESTAMP, r_AWRD.UPDATE_USER, r_AWRD.SUB_AWARD_XFD_FILE, r_AWRD.SUB_AWARD_XML_FILE
, li_ver_nbr, SYS_GUID()
,li_budget_id);--managed data
EXCEPTION
WHEN OTHERS THEN 
dbms_output.put_line('Exception from BUDGET_SUB_AWARD_FILES, Sub Awrd No:'||r_AWRD.SUB_AWARD_NUMBER||'  '||sqlerrm);
END;
EXCEPTION
WHEN OTHERS THEN 
dbms_output.put_line('Exception from SUB AWARDS Main .Proposal Number is '||r_AWRD.PROPOSAL_NUMBER||' , Version Number is '||r_AWRD.VERSION_NUMBER||' . '||sqlerrm);
END;

END LOOP;
CLOSE c_AWRD;

IF c_sub_awd_att%ISOPEN THEN
CLOSE c_sub_awd_att;
END IF;
OPEN c_sub_awd_att;
LOOP
FETCH c_sub_awd_att INTO r_sub_awd_att;
EXIT WHEN c_sub_awd_att%NOTFOUND;



select t1.budget_id  INTO li_budget_id  from budget t1 
			inner join eps_proposal_budget_ext t2 on t1.budget_id = t2.budget_id
			where t2.proposal_number = r_sub_awd_att.PROPOSAL_NUMBER
			and t1.version_number = r_sub_awd_att.VERSION_NUMBER;

SELECT SEQ_SUB_AWD_BGT_ATT_ID.NEXTVAL INTO li_seq_sub_awd_bgt_att_id FROM DUAL;
BEGIN
INSERT INTO BUDGET_SUB_AWARD_ATT(SUB_AWARD_ATTACHMENT_ID,SUB_AWARD_NUMBER,CONTENT_ID,CONTENT_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,BUDGET_ID,ATTACHMENT,OBJ_ID)
VALUES(li_seq_sub_awd_bgt_att_id,r_sub_awd_att.SUB_AWARD_NUMBER,r_sub_awd_att.CONTENT_ID,r_sub_awd_att.CONTENT_TYPE,r_sub_awd_att.UPDATE_TIMESTAMP,r_sub_awd_att.UPDATE_USER,li_ver_nbr,li_budget_id,r_sub_awd_att.ATTACHMENT,SYS_GUID());
EXCEPTION
WHEN OTHERS THEN 
dbms_output.put_line('Exception from BUDGET_SUB_AWARD_ATT and subAward id '||r_sub_awd_att.SUB_AWARD_NUMBER||'  proposal Number is '||r_sub_awd_att.PROPOSAL_NUMBER||sqlerrm);
END;
commit;
END LOOP;
CLOSE c_sub_awd_att;
select count(SUB_AWARD_NUMBER) into li_sub_award_count from BUDGET_SUB_AWARDS;
select count(SUB_AWARD_NUMBER) into li_sub_files_count from BUDGET_SUB_AWARD_FILES;
select count(SUB_AWARD_ATTACHMENT_ID) into li_sub_att_count from BUDGET_SUB_AWARD_ATT;
dbms_output.put_line('------------------Row Counts----------------');
dbms_output.put_line('BUDGET_SUB_AWARDS : '|| li_sub_award_count);
dbms_output.put_line('BUDGET_SUB_AWARD_FILES : '|| li_sub_files_count);
dbms_output.put_line('BUDGET_SUB_AWARD_ATT : '|| li_sub_att_count);
dbms_output.put_line(CHR(10));
dbms_output.put_line('Successfully Completed!! ');
END;
/
