UPDATE CUSTOM_ATTRIBUTE_DOC_VALUE s
SET s.VALUE=(SELECT sc.NEGOTIATION_NUMBER FROM OSP$SUBCONTRACT@coeus.kuali sc 
INNER JOIN SUBAWARD su ON su.SUBAWARD_CODE=to_number(sc.SUBCONTRACT_CODE) AND su.SEQUENCE_NUMBER=sc.SEQUENCE_NUMBER
WHERE s.DOCUMENT_NUMBER=su.DOCUMENT_NUMBER)
WHERE s.CUSTOM_ATTRIBUTE_ID=(SELECT ID FROM CUSTOM_ATTRIBUTE WHERE NAME='NEG_NUMBER_SUB')
/
commit
/

