-- truncate and insert REPORT_STATUS Start
ALTER TABLE AWARD_PAYMENT_SCHEDULE DISABLE CONSTRAINT FK2_AWARD_PAYMENT_SCHEDULE 
/
truncate table REPORT_STATUS
/
insert into REPORT_STATUS(
REPORT_STATUS_CODE,
DESCRIPTION,
ACTIVE_FLAG,
UPDATE_TIMESTAMP,
UPDATE_USER,
VER_NBR,
OBJ_ID
)
select
REPORT_STATUS_CODE,
DESCRIPTION,
'Y',
UPDATE_TIMESTAMP,
UPDATE_USER,
1,
sys_guid()
from OSP$REPORT_STATUS@coeus.kuali
/
commit
/
ALTER TABLE AWARD_PAYMENT_SCHEDULE ENABLE CONSTRAINT FK2_AWARD_PAYMENT_SCHEDULE 
/
-- truncate and insert REPORT_STATUS ends
declare
li_count number;
begin
select  count(table_name) into li_count  from all_tables   where table_name = 'OSP$PERSON';
if li_count > 0 then
execute immediate('drop table OSP$PERSON');

end if;

end;

/
CREATE TABLE OSP$PERSON
(	PERSON_ID VARCHAR2(9 ) NOT NULL ENABLE, 
SSN VARCHAR2(9 ), 
LAST_NAME VARCHAR2(30 ), 
FIRST_NAME VARCHAR2(30 ), 
MIDDLE_NAME VARCHAR2(30 ), 
FULL_NAME VARCHAR2(90 ), 
PRIOR_NAME VARCHAR2(30 ), 
USER_NAME VARCHAR2(60 ), 
EMAIL_ADDRESS VARCHAR2(60 ), 
DATE_OF_BIRTH DATE, 
AGE NUMBER(3,0), 
AGE_BY_FISCAL_YEAR NUMBER(3,0), 
GENDER VARCHAR2(30 ), 
RACE VARCHAR2(30 ), 
EDUCATION_LEVEL VARCHAR2(30 ), 
DEGREE VARCHAR2(11 ), 
MAJOR VARCHAR2(30 ), 
IS_HANDICAPPED CHAR(1 ), 
HANDICAP_TYPE VARCHAR2(30 ), 
IS_VETERAN CHAR(1 ), 
VETERAN_TYPE VARCHAR2(30 ), 
VISA_CODE VARCHAR2(20 ), 
VISA_TYPE VARCHAR2(30 ), 
VISA_RENEWAL_DATE DATE, 
HAS_VISA CHAR(1 ), 
OFFICE_LOCATION VARCHAR2(30 ), 
OFFICE_PHONE VARCHAR2(20 ), 
SECONDRY_OFFICE_LOCATION VARCHAR2(30 ), 
SECONDRY_OFFICE_PHONE VARCHAR2(20 ), 
SCHOOL VARCHAR2(50 ), 
YEAR_GRADUATED VARCHAR2(30 ), 
DIRECTORY_DEPARTMENT VARCHAR2(30 ), 
SALUTATION VARCHAR2(30 ), 
COUNTRY_OF_CITIZENSHIP VARCHAR2(30 ), 
PRIMARY_TITLE VARCHAR2(51 ), 
DIRECTORY_TITLE VARCHAR2(50 ), 
HOME_UNIT VARCHAR2(8 ), 
IS_FACULTY CHAR(1 ), 
IS_GRADUATE_STUDENT_STAFF CHAR(1 ), 
IS_RESEARCH_STAFF CHAR(1 ), 
IS_SERVICE_STAFF CHAR(1 ), 
IS_SUPPORT_STAFF CHAR(1 ), 
IS_OTHER_ACCADEMIC_GROUP CHAR(1 ), 
IS_MEDICAL_STAFF CHAR(1 ), 
VACATION_ACCURAL CHAR(1 ), 
IS_ON_SABBATICAL CHAR(1 ), 
ID_PROVIDED VARCHAR2(30 ), 
ID_VERIFIED VARCHAR2(30 ), 
UPDATE_TIMESTAMP DATE NOT NULL ENABLE, 
UPDATE_USER VARCHAR2(8 ) NOT NULL ENABLE, 
ADDRESS_LINE_1 VARCHAR2(80 ), 
ADDRESS_LINE_2 VARCHAR2(80 ), 
ADDRESS_LINE_3 VARCHAR2(80 ), 
CITY VARCHAR2(30 ), 
COUNTY VARCHAR2(30 ), 
STATE VARCHAR2(30 ), 
POSTAL_CODE VARCHAR2(15 ), 
COUNTRY_CODE CHAR(3 ), 
FAX_NUMBER VARCHAR2(20 ), 
PAGER_NUMBER VARCHAR2(20 ), 
MOBILE_PHONE_NUMBER VARCHAR2(20 ), 
ERA_COMMONS_USER_NAME VARCHAR2(20 ), 
STATUS VARCHAR2(1 ) NOT NULL ENABLE, 
SALARY_ANNIVERSARY_DATE DATE);
commit;
insert into osp$person(PERSON_ID,SSN,LAST_NAME,FIRST_NAME,MIDDLE_NAME,FULL_NAME,PRIOR_NAME,USER_NAME,EMAIL_ADDRESS,DATE_OF_BIRTH,AGE,AGE_BY_FISCAL_YEAR,GENDER,
RACE,EDUCATION_LEVEL,DEGREE,MAJOR,IS_HANDICAPPED,HANDICAP_TYPE,IS_VETERAN,VETERAN_TYPE,VISA_CODE,VISA_TYPE,VISA_RENEWAL_DATE,HAS_VISA,OFFICE_LOCATION,
OFFICE_PHONE,SECONDRY_OFFICE_LOCATION,SECONDRY_OFFICE_PHONE,SCHOOL,YEAR_GRADUATED,DIRECTORY_DEPARTMENT,SALUTATION,COUNTRY_OF_CITIZENSHIP,PRIMARY_TITLE,
DIRECTORY_TITLE,HOME_UNIT,IS_FACULTY,IS_GRADUATE_STUDENT_STAFF,IS_RESEARCH_STAFF,IS_SERVICE_STAFF,IS_SUPPORT_STAFF,IS_OTHER_ACCADEMIC_GROUP,IS_MEDICAL_STAFF,
VACATION_ACCURAL,IS_ON_SABBATICAL,ID_PROVIDED,ID_VERIFIED,UPDATE_TIMESTAMP,UPDATE_USER,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,CITY,COUNTY,STATE,POSTAL_CODE,
COUNTRY_CODE,FAX_NUMBER,PAGER_NUMBER,MOBILE_PHONE_NUMBER,ERA_COMMONS_USER_NAME,STATUS,SALARY_ANNIVERSARY_DATE)
SELECT PERSON_ID,SSN,LAST_NAME,FIRST_NAME,MIDDLE_NAME,FULL_NAME,PRIOR_NAME,USER_NAME,EMAIL_ADDRESS,DATE_OF_BIRTH,AGE,AGE_BY_FISCAL_YEAR,GENDER,
RACE,EDUCATION_LEVEL,DEGREE,MAJOR,IS_HANDICAPPED,HANDICAP_TYPE,IS_VETERAN,VETERAN_TYPE,VISA_CODE,VISA_TYPE,VISA_RENEWAL_DATE,HAS_VISA,OFFICE_LOCATION,
OFFICE_PHONE,SECONDRY_OFFICE_LOCATION,SECONDRY_OFFICE_PHONE,SCHOOL,YEAR_GRADUATED,DIRECTORY_DEPARTMENT,SALUTATION,COUNTRY_OF_CITIZENSHIP,PRIMARY_TITLE,
DIRECTORY_TITLE,HOME_UNIT,IS_FACULTY,IS_GRADUATE_STUDENT_STAFF,IS_RESEARCH_STAFF,IS_SERVICE_STAFF,IS_SUPPORT_STAFF,IS_OTHER_ACCADEMIC_GROUP,IS_MEDICAL_STAFF,
VACATION_ACCURAL,IS_ON_SABBATICAL,ID_PROVIDED,ID_VERIFIED,UPDATE_TIMESTAMP,UPDATE_USER,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,CITY,COUNTY,STATE,POSTAL_CODE,
COUNTRY_CODE,FAX_NUMBER,PAGER_NUMBER,MOBILE_PHONE_NUMBER,ERA_COMMONS_USER_NAME,STATUS,SALARY_ANNIVERSARY_DATE FROM osp$person@coeus.kuali;
/
commit
/
alter table osp$person add constraint osp$person_P1 PRIMARY KEY (PERSON_ID)
/
update award_persons ap set  ap.full_name = (select p1.full_name from osp$person p1 where ap.person_id = p1.person_id)
where  ap.person_id is not null and ap.full_name is null
/
commit
/
truncate table AWARD_REPORT_TRACKING
/
alter table AWARD_REPORT_TRACKING modify COMMENTS VARCHAR2(1000)
/
CREATE TABLE TEMP_REPORTING(AWARD_NUMBER	VARCHAR2(12),
SEQUENCE_NUMBER	NUMBER(4,0),
PERSON_ID	VARCHAR2(40),
ROLODEX_ID	NUMBER(6,0),
FULL_NAME	VARCHAR2(90),
LEAD_UNIT_NUMBER	VARCHAR2(8),
SPONSOR_CODE	VARCHAR2(6),
SPONSOR_AWARD_NUMBER	VARCHAR2(70),
TITLE	VARCHAR2(200),
LAST_UPDATE_USER VARCHAR2(60),
LAST_UPDATE_DATE DATE,
UPDATE_TIMESTAMP	DATE,
UPDATE_USER	VARCHAR2(60)
)
/
create table TEMP_AWARD_REPORTING_M
(
MIT_AWARD_NUMBER CHAR(12),
REPORT_CLASS_CODE	NUMBER(3,0),
REPORT_CODE	NUMBER(3,0),
FREQUENCY_CODE	NUMBER(3,0),
FREQUENCY_BASE_CODE	NUMBER(3,0),
OSP_DISTRIBUTION_CODE	NUMBER(3,0),
DUE_DATE	DATE,
OVERDUE_COUNTER	NUMBER(3,0),
ACTIVITY_DATE	DATE,
COMMENTS	VARCHAR2(1000), 
PREPARER_ID VARCHAR2(40),
REPORT_STATUS_CODE	NUMBER(3,0)
)
/
create index i_award_person on AWARD_PERSONS(AWARD_NUMBER,SEQUENCE_NUMBER)
/
INSERT INTO TEMP_AWARD_REPORTING_M(MIT_AWARD_NUMBER,REPORT_CLASS_CODE,REPORT_CODE,FREQUENCY_CODE,FREQUENCY_BASE_CODE,OSP_DISTRIBUTION_CODE,
DUE_DATE,OVERDUE_COUNTER,ACTIVITY_DATE,COMMENTS,PREPARER_ID,REPORT_STATUS_CODE)
select replace(MIT_AWARD_NUMBER,'-','-00') as MIT_AWARD_NUMBER,REPORT_CLASS_CODE,REPORT_CODE,FREQUENCY_CODE,FREQUENCY_BASE_CODE,OSP_DISTRIBUTION_CODE,DUE_DATE,OVERDUE_COUNTER,
ACTIVITY_DATE,COMMENTS,PERSON_ID,REPORT_STATUS_CODE from OSP$AWARD_REPORTING@coeus.kuali
/
commit
/
INSERT INTO TEMP_REPORTING(AWARD_NUMBER,SEQUENCE_NUMBER,PERSON_ID,ROLODEX_ID,FULL_NAME,LEAD_UNIT_NUMBER,SPONSOR_CODE,SPONSOR_AWARD_NUMBER,TITLE,LAST_UPDATE_USER,LAST_UPDATE_DATE,UPDATE_TIMESTAMP,UPDATE_USER)
select a.award_number,a.sequence_number,ap.person_id,ap.rolodex_id,ap.full_name,a.lead_unit_number,a.sponsor_code,a.sponsor_award_number,a.title,a.update_user,a.update_timestamp,a.update_timestamp,a.update_user
from 
award a inner join award_persons ap on a.award_number=ap.award_number and a.sequence_number=ap.sequence_number
where a.sequence_number=(select max(aw.sequence_number) from award aw where aw.award_number=a.award_number) 
and ap.contact_role_code='PI'
/
commit
/
INSERT INTO AWARD_REPORT_TRACKING(AWARD_REPORT_TERM_ID,AWARD_NUMBER,PI_PERSON_ID,PI_ROLODEX_ID,PI_NAME,LEAD_UNIT_NUMBER,REPORT_CLASS_CODE,
REPORT_CODE,FREQUENCY_CODE,FREQUENCY_BASE_CODE,OSP_DISTRIBUTION_CODE,STATUS_CODE,BASE_DATE,DUE_DATE,ACTIVITY_DATE,OVERDUE,COMMENTS,
PREPARER_ID,PREPARER_NAME,SPONSOR_CODE,SPONSOR_AWARD_NUMBER,TITLE,LAST_UPDATE_USER,LAST_UPDATE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
select SEQUENCE_AWARD_ID.nextval,ap.award_number,ap.person_id,ap.rolodex_id,ap.full_name,ap.lead_unit_number,ar.report_class_code,
ar.report_code,ar.frequency_code,ar.frequency_base_code,ar.osp_distribution_code,ar.REPORT_STATUS_CODE,null,ar.due_date,ar.activity_date,
ar.overdue_counter,ar.comments,ar.PREPARER_ID,null,ap.sponsor_code,ap.sponsor_award_number,ap.title,ap.update_user,ap.update_timestamp,
ap.update_timestamp,ap.update_user,1,SYS_GUID()
from 
TEMP_REPORTING ap
inner join TEMP_AWARD_REPORTING_M ar on ap.award_number=ar.mit_award_number
/ 
commit
/
update AWARD_REPORT_TRACKING art set  art.PREPARER_NAME = (select distinct p1.full_name from osp$person p1 where art.PREPARER_ID = p1.person_id)
/
drop table TEMP_AWARD_REPORTING_M
/
drop table TEMP_REPORTING
/
drop index i_award_person
/
commit
/