drop table OSP$PROPOSAL_IDC_RATE
/
drop table V_PROPOSAL_IDC
/
drop table TEMP_PROPOSAL_IDC
/
CREATE TABLE "OSP$PROPOSAL_IDC_RATE" 
(	"PROPOSAL_NUMBER" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL ENABLE, 
"APPLICABLE_IDC_RATE" NUMBER(5,2) NOT NULL ENABLE, 
"IDC_RATE_TYPE_CODE" NUMBER(3,0) NOT NULL ENABLE, 
"FISCAL_YEAR" CHAR(4 BYTE) NOT NULL ENABLE, 
"ON_CAMPUS_FLAG" CHAR(1 BYTE) NOT NULL ENABLE, 
"UNDERRECOVERY_OF_IDC" NUMBER(12,2), 
"SOURCE_ACCOUNT" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
"UPDATE_USER" VARCHAR2(8 BYTE) NOT NULL ENABLE)
/
commit
/
insert into OSP$PROPOSAL_IDC_RATE(PROPOSAL_NUMBER,SEQUENCE_NUMBER,APPLICABLE_IDC_RATE,IDC_RATE_TYPE_CODE,FISCAL_YEAR,ON_CAMPUS_FLAG,
SOURCE_ACCOUNT,UNDERRECOVERY_OF_IDC,UPDATE_TIMESTAMP,UPDATE_USER)
SELECT PROPOSAL_NUMBER,SEQUENCE_NUMBER,APPLICABLE_IDC_RATE,IDC_RATE_TYPE_CODE,FISCAL_YEAR,ON_CAMPUS_FLAG,
SOURCE_ACCOUNT,UNDERRECOVERY_OF_IDC,UPDATE_TIMESTAMP,UPDATE_USER FROM OSP$PROPOSAL_IDC_RATE@coeus.kuali
/
commit
/
CREATE INDEX OSP$PROPOSAL_IDC_RATE_I ON OSP$PROPOSAL_IDC_RATE(PROPOSAL_NUMBER,SEQUENCE_NUMBER)
/
CREATE TABLE V_PROPOSAL_IDC(
"PROPOSAL_NUMBER" VARCHAR2(20),
"MIT_PROPOSAL_NUMBER" VARCHAR2(8),
"CHANGED" CHAR(1),
"PROPOSAL_ID"	NUMBER(12,0),
"KUALI_SEQUENCE_NUMBER" NUMBER(4,0), 
"SEQUENCE_NUMBER" NUMBER(4,0) ,
"APPLICABLE_IDC_RATE" NUMBER(5,2) , 
"IDC_RATE_TYPE_CODE" NUMBER(3,0) ,
"FISCAL_YEAR" CHAR(4) , 
"ON_CAMPUS_FLAG" CHAR(1), 
"SOURCE_ACCOUNT" VARCHAR2(100),
"UNDERRECOVERY_OF_IDC" NUMBER(12,2), 
"UPDATE_TIMESTAMP" DATE, 
"UPDATE_USER" VARCHAR2(8)
)
/
INSERT INTO V_PROPOSAL_IDC(PROPOSAL_NUMBER,MIT_PROPOSAL_NUMBER,CHANGED,PROPOSAL_ID,KUALI_SEQUENCE_NUMBER,SEQUENCE_NUMBER,APPLICABLE_IDC_RATE,IDC_RATE_TYPE_CODE,FISCAL_YEAR,ON_CAMPUS_FLAG,SOURCE_ACCOUNT,UNDERRECOVERY_OF_IDC,UPDATE_TIMESTAMP,UPDATE_USER) 
select l.MODULE_ITEM_KEY PROPOSAL_NUMBER,a.PROPOSAL_NUMBER MIT_PROPOSAL_NUMBER,l.changed,p.PROPOSAL_ID,l.kuali_sequence_number,a.SEQUENCE_NUMBER,a.APPLICABLE_IDC_RATE,a.IDC_RATE_TYPE_CODE,a.FISCAL_YEAR,a.ON_CAMPUS_FLAG,a.SOURCE_ACCOUNT,a.UNDERRECOVERY_OF_IDC,a.UPDATE_TIMESTAMP,a.UPDATE_USER 
FROM  TEMP_SEQ_LOG l 
Left outer join OSP$PROPOSAL_IDC_RATE a on l.module_item_key=a.PROPOSAL_NUMBER and l.mit_sequence_number=a.SEQUENCE_NUMBER inner join PROPOSAL p on p.PROPOSAL_NUMBER=l.MODULE_ITEM_KEY and p.SEQUENCE_NUMBER=l.kuali_sequence_number where l.MODULE='IP'
and p.IDC_RATE_INDICATOR not in('N1','N0')
/
CREATE TABLE TEMP_PROPOSAL_IDC
   (PROPOSAL_NUMBER VARCHAR2(20), 
	KUALI_SEQUENCE_NUMBER NUMBER, 
	SEQUENC NUMBER(4,0)  )
/
INSERT INTO TEMP_PROPOSAL_IDC(PROPOSAL_NUMBER,KUALI_SEQUENCE_NUMBER,SEQUENC)
select PROPOSAL_NUMBER,(select max(aw.sequence_number) from V_PROPOSAL_IDC aw where aw.proposal_number= v.proposal_number
and aw.KUALI_SEQUENCE_NUMBER<=v.KUALI_SEQUENCE_NUMBER and aw.mit_proposal_number is not null)  as kuali_sequence_number,v.KUALI_SEQUENCE_NUMBER SEQUENC  
from V_PROPOSAL_IDC v  where v.mit_proposal_number is null
/
CREATE INDEX TEMP_PROPOSAL_IDC_I1 ON TEMP_PROPOSAL_IDC(PROPOSAL_NUMBER,KUALI_SEQUENCE_NUMBER)
/
commit
/
truncate table PROPOSAL_IDC_RATE
/
INSERT INTO PROPOSAL_IDC_RATE(PROPOSAL_IDC_RATE_ID,PROPOSAL_ID,PROPOSAL_NUMBER,SEQUENCE_NUMBER,APPLICABLE_IDC_RATE,IDC_RATE_TYPE_CODE,FISCAL_YEAR,ON_CAMPUS_FLAG,UNDERRECOVERY_OF_IDC,SOURCE_ACCOUNT,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
select SEQ_UNRECOVERED_FNA_ID.NEXTVAL,a.PROPOSAL_ID,a.PROPOSAL_NUMBER,a.kuali_sequence_number,a.APPLICABLE_IDC_RATE,a.IDC_RATE_TYPE_CODE,a.FISCAL_YEAR,a.ON_CAMPUS_FLAG,a.UNDERRECOVERY_OF_IDC,a.SOURCE_ACCOUNT,a.UPDATE_TIMESTAMP,a.UPDATE_USER,1,SYS_GUID()
from V_PROPOSAL_IDC a where a.mit_proposal_number IS NOT NULL
/
commit
/
INSERT INTO PROPOSAL_IDC_RATE(PROPOSAL_IDC_RATE_ID,PROPOSAL_ID,PROPOSAL_NUMBER,SEQUENCE_NUMBER,APPLICABLE_IDC_RATE,IDC_RATE_TYPE_CODE,FISCAL_YEAR,ON_CAMPUS_FLAG,UNDERRECOVERY_OF_IDC,SOURCE_ACCOUNT,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
select SEQ_UNRECOVERED_FNA_ID.NEXTVAL,a.PROPOSAL_ID,a.PROPOSAL_NUMBER,v2.SEQUENC,a.APPLICABLE_IDC_RATE,a.IDC_RATE_TYPE_CODE,a.FISCAL_YEAR,a.ON_CAMPUS_FLAG,a.UNDERRECOVERY_OF_IDC,a.SOURCE_ACCOUNT,a.UPDATE_TIMESTAMP,a.UPDATE_USER,1,SYS_GUID()
from V_PROPOSAL_IDC a inner join
TEMP_PROPOSAL_IDC v2 on a.PROPOSAL_NUMBER=v2.PROPOSAL_NUMBER and a.sequence_number=v2.kuali_sequence_number
/
commit
/
--where a.changed='N';
update PROPOSAL_IDC_RATE pp set pp.proposal_id = (select p.proposal_id from proposal p where
p.proposal_number = pp.proposal_number
and p.sequence_number = pp.sequence_number
)
/
commit
/
drop table OSP$PROPOSAL_IDC_RATE
/
drop table V_PROPOSAL_IDC
/
drop table TEMP_PROPOSAL_IDC
/