set serveroutput on
/
SET DEFINE OFF
/
declare
li_count number;
begin
  select  count(table_name) into li_count  from user_tables   where table_name = 'BOOT_QUESTIONNAIRE';
  if li_count = 0 then  
	execute immediate('CREATE TABLE BOOT_QUESTIONNAIRE
	(	"QUESTIONNAIRE_REF_ID" NUMBER(12,0), 
	"QUESTIONNAIRE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(2000), 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(60) NOT NULL ENABLE, 
	"IS_FINAL" VARCHAR2(1) NOT NULL ENABLE, 
	"VER_NBR" NUMBER(8,0) DEFAULT 1 NOT NULL ENABLE, 
	"OBJ_ID" VARCHAR2(36) NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(1000), 
	"TEMPLATE" CLOB, 
	"DOCUMENT_NUMBER" VARCHAR2(40))');
	
  end if;
  
  select  count(table_name) into li_count  from user_tables   where table_name = 'BOOT_QUESTIONNAIRE_QUESTIONS';
  if li_count = 0 then    
	execute immediate('CREATE TABLE BOOT_QUESTIONNAIRE_QUESTIONS 
	(	"QUESTIONNAIRE_QUESTIONS_ID" NUMBER(12,0), 
	"QUESTIONNAIRE_REF_ID_FK" NUMBER(12,0) NOT NULL ENABLE, 
	"QUESTION_REF_ID_FK" NUMBER(12,0) NOT NULL ENABLE, 
	"QUESTION_NUMBER" NUMBER(6,0) NOT NULL ENABLE, 
	"PARENT_QUESTION_NUMBER" NUMBER(6,0) NOT NULL ENABLE, 
	"CONDITION_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"CONDITION_TYPE" VARCHAR2(3), 
	"CONDITION_VALUE" VARCHAR2(2000 BYTE), 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(60) NOT NULL ENABLE, 
	"QUESTION_SEQ_NUMBER" NUMBER(3,0), 
	"VER_NBR" NUMBER(8,0) DEFAULT 1 NOT NULL ENABLE, 
	"OBJ_ID" VARCHAR2(36) NOT NULL ENABLE, 
	"RULE_ID" VARCHAR2(40))');
	
  end if;
	
  select  count(table_name) into li_count  from user_tables   where table_name = 'BOOT_QUESTION';
  if li_count = 0 then    
	execute immediate('CREATE TABLE BOOT_QUESTION 
	(	"QUESTION_REF_ID" NUMBER(12,0), 
	"QUESTION_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL ENABLE, 
	"SEQUENCE_STATUS" CHAR(1 BYTE) NOT NULL ENABLE, 
	"QUESTION" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	"STATUS" CHAR(1 BYTE) NOT NULL ENABLE, 
	"GROUP_TYPE_CODE" NUMBER(3,0) NOT NULL ENABLE, 
	"QUESTION_TYPE_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"LOOKUP_CLASS" VARCHAR2(100 BYTE), 
	"LOOKUP_RETURN" VARCHAR2(30 BYTE), 
	"DISPLAYED_ANSWERS" NUMBER(2,0), 
	"MAX_ANSWERS" NUMBER(2,0), 
	"ANSWER_MAX_LENGTH" NUMBER(4,0), 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"VER_NBR" NUMBER(8,0) DEFAULT 1 NOT NULL ENABLE, 
	"OBJ_ID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	"DOCUMENT_NUMBER" VARCHAR2(14 BYTE))');
	
  end if;
  
  end;
 /
truncate table BOOT_QUESTIONNAIRE_QUESTIONS
/
truncate table BOOT_QUESTIONNAIRE
/
truncate table BOOT_QUESTION
/
delete from  questionnaire t1 where t1.QUESTIONNAIRE_ID = 5
and not exists ( select t2.questionnaire_ref_id_fk from questionnaire_questions t2 
where t1.questionnaire_ref_id = t2.questionnaire_ref_id_fk )
/
commit
/
Insert into BOOT_QUESTIONNAIRE (QUESTIONNAIRE_REF_ID,QUESTIONNAIRE_ID,SEQUENCE_NUMBER,NAME,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_FINAL,VER_NBR,OBJ_ID,FILE_NAME,TEMPLATE,DOCUMENT_NUMBER) values (855,5,1,'GG S2S Forms','Multiple Grants.gov forms:NASA Other Project Information, NASA PI/AOR Data Sheet, PHS 398 Checklist, PHS 398 Cover Page Supplement, RR Other Project Information, SF 424 R&R, SF 424, ED SF424 Supplement',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin','Y',1,'0619063A9721AAAFE050007F01007FE8',null,null,null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (861,855,839,1,0,'N',null,null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9727AAAFE050007F01007FE8','KC150');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (862,855,840,2,1,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9728AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (866,855,841,3,2,'N',null,null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A972CAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (869,855,842,4,2,'N',null,null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',2,1,'0619063A972FAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (877,855,843,5,4,'N',null,null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9737AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (865,855,841,6,5,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A972BAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (872,855,842,7,5,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',2,1,'0619063A9732AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (876,855,843,8,7,'N',null,null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9736AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (867,855,841,9,8,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A972DAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (874,855,842,10,8,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',2,1,'0619063A9734AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (879,855,843,11,10,'N',null,null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9739AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (868,855,841,12,11,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A972EAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (871,855,842,13,11,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',2,1,'0619063A9731AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (878,855,843,14,13,'N',null,null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9738AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (863,855,841,15,14,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9729AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (873,855,842,16,14,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',2,1,'0619063A9733AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (875,855,843,17,16,'N',null,null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9735AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (864,855,841,18,17,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A972AAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (870,855,842,19,17,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',2,1,'0619063A9730AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (880,855,845,20,0,'N',null,null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',2,1,'0619063A973AAAAFE050007F01007FE8','KC150');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (881,855,846,21,20,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A973BAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (887,855,847,22,0,'N','4',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',3,1,'0619063A9741AAAFE050007F01007FE8','KC150');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (888,855,848,23,22,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9742AAAFE050007F01007FE8','KC150');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (885,855,846,24,22,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',2,1,'0619063A973FAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (889,855,849,25,0,'N','4',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',4,1,'0619063A9743AAAFE050007F01007FE8','KC141');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (891,855,850,26,25,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9745AAAFE050007F01007FE8','KC141');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (893,855,852,27,25,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',2,1,'0619063A9747AAAFE050007F01007FE8','KC141');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (892,855,851,28,0,'N','4',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',5,1,'0619063A9746AAAFE050007F01007FE8','KC141');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (894,855,853,29,0,'N','4',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',6,1,'0619063A9748AAAFE050007F01007FE8','KC145');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (895,855,854,30,29,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9749AAAFE050007F01007FE8','KC145');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (896,855,755,31,0,'N','4',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',7,1,'0619063A974AAAAFE050007F01007FE8','KC145');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (897,855,756,32,31,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A974BAAAFE050007F01007FE8','KC145');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (898,855,757,33,0,'N','4',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',8,1,'0619063A974CAAAFE050007F01007FE8','KC145');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (899,855,758,34,33,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A974DAAAFE050007F01007FE8','KC145');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (900,855,759,35,34,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A974EAAAFE050007F01007FE8','KC145');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (901,855,760,36,0,'N','4',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',9,1,'0619063A974FAAAFE050007F01007FE8','KC145');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (856,855,774,37,0,'N',null,null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',10,1,'0619063A9722AAAFE050007F01007FE8','KC146');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (857,855,775,38,37,'Y','3','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9723AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (858,855,777,39,0,'N','3',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',11,1,'0619063A9724AAAFE050007F01007FE8','KC146');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (859,855,778,40,39,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9725AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (860,855,779,41,40,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9726AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (902,855,761,43,0,'N','4',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',13,1,'0619063A9750AAAFE050007F01007FE8','KC149');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (883,855,846,45,44,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A973DAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (904,855,763,46,44,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',2,1,'0619063A9752AAAFE050007F01007FE8','KC149');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (884,855,846,47,46,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A973EAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (905,855,764,48,0,'N','4',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',15,1,'0619063A9753AAAFE050007F01007FE8','KC147');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (886,855,846,49,48,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9740AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (906,855,765,50,0,'N','4',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',16,1,'0619063A9754AAAFE050007F01007FE8','KC149');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (907,855,766,51,50,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9755AAAFE050007F01007FE8','KC149');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (882,855,846,52,50,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',2,1,'0619063A973CAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (908,855,767,53,0,'N','4',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',17,1,'0619063A9756AAAFE050007F01007FE8','KC144');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (890,855,850,54,53,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9744AAAFE050007F01007FE8','KC141');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (909,855,768,55,0,'N','4',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',18,1,'0619063A9757AAAFE050007F01007FE8','KC142');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (910,855,769,56,55,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619063A9758AAAFE050007F01007FE8','KC149');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (911,855,770,57,55,'Y','4','N',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',2,1,'0619063A9759AAAFE050007F01007FE8','KC142');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (913,855,771,58,0,'N','4',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',19,1,'0619063A975BAAAFE050007F01007FE8','KC148');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (914,855,772,59,0,'N','4',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',20,1,'0619063A975CAAAFE050007F01007FE8','KC143');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (916,855,768,279,0,'N','4',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',18,1,'0619067DB0769D98E050007F01007FEC','KC144');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (917,855,769,280,279,'Y','4','Y',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,1,'0619067DB0779D98E050007F01007FEC','KC149');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (918,855,770,281,279,'Y','4','N',to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',2,1,'0619067DB0789D98E050007F01007FEC','KC142');
Insert into BOOT_QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) values (922,855,920,291,0,'N','4',null,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',13,1,'061907AF7DC702D0E050007F0100015E','KC149');
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (846,107,1,'C','Briefly explain.','A',2,5,null,null,null,1,300,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A9718AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (774,2,1,'A','Is a Clinical Trial part of this project?','A',4,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96D1AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (764,125,1,'C','Is the research performance site designated, or eligible to be designated, as a historic place?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96C7AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (771,132,1,'C','Is the PI a New NIH Investigator?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96CEAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (920,123,2,'C','Does this project have an actual or potential impact - positive or negative - on the environment?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'061907AF7DC502D0E050007F0100015E',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (853,114,1,'C','Does this application reflect a change in principal investigator/program director from that indicated on a previous application?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A971FAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (760,121,1,'C','If this application does not result in an award, is the Government permitted to disclose the title of your proposed project, and the name, address, telephone number and e-mail address of the official signing for the applicant organization, to organizations that may be interested in contacting you for further information (e.g., possible collaborations, investment)?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96C3AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (767,128,1,'C','Is this application being submitted to other agencies?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96CAAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (845,106,1,'C','Does this project have the potential to affect historic, archeological, or traditional cultural sites (such as Native American burial or ceremonial grounds) or historic objects (such as an historic aircraft or spacecraft)?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A9717AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (850,111,1,'C','Select a U.S. Government Agency:','A',2,6,'org.kuali.kra.bo.ArgValueLookup','Agency_US GOV',null,1,3,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A971CAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (854,115,1,'C','Search and select the former PD/PI','A',2,6,'org.kuali.kra.bo.NonOrganizationalRolodex','rolodexId',null,1,6,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A9720AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (779,7,1,'A','List the registration number of the specific cell line(s) from the stem cell registry found at: http://stemcells.nih.gov/registry/','A',4,5,null,null,null,20,4,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96D6AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (770,131,1,'C','If No: Is the program not selected for review or not covered by  E.O. 12372? Select a response.','A',2,6,'org.kuali.kra.bo.ArgValueLookup','STATE_EO_12372',null,1,25,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96CDAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (847,108,1,'C','Does this proposed project involve any international participation, either non-U.S. employees or non-U.S. organizations, providing support for facilities, equipment, etc.? (see opportunity instructions for details)','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A9719AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (852,113,1,'C','Enter the total dollar amount requested ($)','A',2,3,null,null,null,1,6,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A971EAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (759,120,1,'C','If "Yes" (inventions were concieved or reduced to practice) indicate Yes or No as to whether this information has been reported previously to the PHS or to the applicant organization official responsible for patent matters.','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96C2AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (761,122,1,'C','Is proprietary/privileged information included in the application?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96C4AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (765,126,1,'C','Does this project involve activities outside of the United States or partnerships with international collaborators?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96C8AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (772,133,1,'C','Is assistance being requested under a program that gives special consideration to novice applicants? Yes, No, or Not Applicable?','A',2,2,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96CFAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (841,103,1,'C','Select a Government Fiscal Year from the list to report the FTE''s  (Form version 1-0 supports years 2006-2021)','A',2,6,'org.kuali.kra.bo.ArgValueLookup','Fiscal_Year',null,1,4,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A9713AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (848,109,1,'C','Please select all that are provided with support (PI, Co-I, Collaborator, Equipment, Facility)','A',2,6,'org.kuali.kra.bo.ArgValueLookup','PROPOSAL_SUPPORT_lIST',null,5,25,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A971AAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (849,110,1,'C','Is the principal investigator participating in this project as an employee of the U.S. Government?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A971BAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (756,117,1,'C','Search and select the former Institution from the Organization records','A',2,6,'org.kuali.kra.bo.Organization','organizationName',null,1,6,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96BFAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (757,118,1,'C','Is this a Renewal Application?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96C0AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (778,6,1,'A','Can a specific stem cell line be referenced at this time? A "N" answer affirms that an undefined registry cell line will be used. A "Y" answer requires entering the cell IDs in the next question.','A',4,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96D5AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (763,124,1,'C','If this project has an actual or potential impact on the environment, has an exemption been authorized or a environmental impact statement (EIS) been performed?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96C6AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (766,127,1,'C','Identify the countries','A',2,5,null,null,null,1,300,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96C9AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (840,102,1,'C','Please record the total number of civil service FTEs by Government fiscal year in the upcoming questions. Up to six (6) fiscal years can be detailed on this form.','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A9712AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (843,105,1,'C','Is there another year to report?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A9715AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (775,3,1,'A','Is this an NIH-defined Phase III clinical trial?','A',4,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96D2AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (769,130,1,'C','If Yes: Please provide the date the application was made available for review (submitted to the state). Enter in MM/DD/YYYY format.','A',2,4,null,null,null,1,0,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96CCAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (842,104,1,'C','Enter the Number of FTE''s for the selected Fiscal Year.','A',2,3,null,null,null,1,4,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A9714AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (851,112,1,'C','Is the principal investigator participating in this project as an employee of a foreign organization?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A971DAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (755,116,1,'C','Does this application reflect a change in grantee institution from that indicated on a previous application?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96BEAAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (777,5,1,'A','Does the proposed project involve human embryonic stem cells?','A',4,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96D4AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (839,101,1,'C','Will any civil service personnel work on this project?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A9711AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (758,119,1,'C','Check "No" if no inventions were conceived or reduced to practice during the course of work under this project.  Check "Yes" if any inventions were conceived or reduced to practice during the previous period of support.','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96C1AAAFE050007F01007FE8',null);
Insert into BOOT_QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) values (768,129,1,'C','Is the proposal subject to review by state executive order 12372 process?','A',2,1,null,null,null,1,1,to_timestamp('23-OCT-14','DD-MON-RR HH.MI.SSXFF AM'),'admin',1,'0619063A96CBAAAFE050007F01007FE8',null);
commit
/
DECLARE
	li_question_ref_id NUMBER(12);
	li_seq NUMBER(4);
	li_question NUMBER(12);
	li_sequence NUMBER(4);
	li_question_ref NUMBER(12);
	li_ques_ref NUMBER(12);
	li_num NUMBER;
	
	CURSOR c_questionnaire IS 
	SELECT QUESTIONNAIRE_REF_ID,QUESTIONNAIRE_ID,SEQUENCE_NUMBER,NAME,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_FINAL,FILE_NAME,TEMPLATE,DOCUMENT_NUMBER 
	FROM BOOT_QUESTIONNAIRE WHERE QUESTIONNAIRE_ID = 5;
	r_questionnaire c_questionnaire%ROWTYPE;

BEGIN
IF c_questionnaire%ISOPEN THEN
CLOSE c_questionnaire;
END IF;
OPEN c_questionnaire;
LOOP
FETCH c_questionnaire INTO r_questionnaire;
EXIT WHEN c_questionnaire%NOTFOUND;

	SELECT SEQ_QUESTIONNAIRE_REF_ID.NEXTVAL INTO li_question_ref_id FROM DUAL;

	SELECT max(SEQUENCE_NUMBER) into li_seq FROM QUESTIONNAIRE WHERE QUESTIONNAIRE_ID=r_questionnaire.QUESTIONNAIRE_ID;
	  if li_seq is null then
		li_seq := 1;
	  else
	   li_seq := li_seq + 1;
	  end if;
  
	INSERT INTO QUESTIONNAIRE(QUESTIONNAIRE_REF_ID,QUESTIONNAIRE_ID,SEQUENCE_NUMBER,NAME,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_FINAL,VER_NBR,OBJ_ID,FILE_NAME,TEMPLATE,DOCUMENT_NUMBER)
	VALUES(li_question_ref_id,r_questionnaire.QUESTIONNAIRE_ID,li_seq,r_questionnaire.NAME,r_questionnaire.DESCRIPTION,sysdate,user,r_questionnaire.IS_FINAL,1,SYS_GUID(),r_questionnaire.FILE_NAME,r_questionnaire.TEMPLATE,NULL);

END LOOP;
CLOSE c_questionnaire;
END;
/
commit
/
DECLARE
	li_question_ref_id NUMBER(12);
	li_seq NUMBER(4);
	li_question NUMBER(12);
	li_sequence NUMBER(4);
	li_question_ref NUMBER(12);
	li_ques_ref NUMBER(12);
	li_num NUMBER;
	li_count NUMBER;
	li_qnr_ref_id QUESTIONNAIRE.QUESTIONNAIRE_REF_ID%type;
	
	CURSOR c_quest_questions IS
	SELECT a.QUESTIONNAIRE_QUESTIONS_ID,b.QUESTIONNAIRE_ID,b.SEQUENCE_NUMBER,a.QUESTIONNAIRE_REF_ID_FK,a.QUESTION_REF_ID_FK,a.QUESTION_NUMBER,a.PARENT_QUESTION_NUMBER,a.CONDITION_FLAG,a.CONDITION_TYPE,a.CONDITION_VALUE,a.UPDATE_TIMESTAMP,a.UPDATE_USER,a.QUESTION_SEQ_NUMBER,a.RULE_ID
	FROM  BOOT_QUESTIONNAIRE_QUESTIONS a INNER JOIN BOOT_QUESTIONNAIRE b ON a.QUESTIONNAIRE_REF_ID_FK = b.QUESTIONNAIRE_REF_ID
	WHERE b.QUESTIONNAIRE_ID = 5;
	r_quest_questions c_quest_questions%ROWTYPE;

BEGIN
	IF c_quest_questions%ISOPEN THEN
	CLOSE c_quest_questions;
	END IF;
	OPEN c_quest_questions;
	LOOP
	FETCH c_quest_questions INTO r_quest_questions;
	EXIT WHEN c_quest_questions%NOTFOUND;


	BEGIN
		SELECT QUESTION_ID,SEQUENCE_NUMBER INTO li_question,li_sequence FROM BOOT_QUESTION WHERE QUESTION_REF_ID = r_quest_questions.QUESTION_REF_ID_FK;

		SELECT count(question_ref_id) INTO li_count FROM QUESTION WHERE QUESTION_ID = li_question AND SEQUENCE_NUMBER = li_sequence;

		if li_count = 0 then
			SELECT  SEQ_QUESTIONNAIRE_REF_ID.NEXTVAL INTO li_question_ref FROM DUAL; 
		
			INSERT INTO QUESTION(QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER)
			SELECT li_question_ref,a.QUESTION_ID,a.SEQUENCE_NUMBER,a.SEQUENCE_STATUS,a.QUESTION,a.STATUS,a.GROUP_TYPE_CODE,a.QUESTION_TYPE_ID,a.LOOKUP_CLASS,a.LOOKUP_RETURN,a.DISPLAYED_ANSWERS,a.MAX_ANSWERS,a.ANSWER_MAX_LENGTH,sysdate,user,1,sys_guid(),null
			FROM BOOT_QUESTION a WHERE a.QUESTION_REF_ID = r_quest_questions.QUESTION_REF_ID_FK;
		
		
		else
			SELECT QUESTION_REF_ID INTO li_question_ref FROM QUESTION WHERE QUESTION_ID = li_question AND SEQUENCE_NUMBER = li_sequence;
		
		end if;
	 
	EXCEPTION
	WHEN OTHERS THEN
	li_question_ref := r_quest_questions.QUESTION_REF_ID_FK;

	END;
		
	BEGIN
		SELECT t1.QUESTIONNAIRE_REF_ID into li_qnr_ref_id FROM QUESTIONNAIRE t1
		WHERE t1.QUESTIONNAIRE_ID = r_quest_questions.QUESTIONNAIRE_ID
		AND t1.SEQUENCE_NUMBER = ( SELECT max(t2.SEQUENCE_NUMBER)
                              FROM QUESTIONNAIRE t2
                              WHERE t2.QUESTIONNAIRE_ID = t1.QUESTIONNAIRE_ID
                          );
	
		INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID)
		VALUES(SEQ_QUESTIONNAIRE_REF_ID.NEXTVAL,li_qnr_ref_id,li_question_ref,r_quest_questions.QUESTION_NUMBER,r_quest_questions.PARENT_QUESTION_NUMBER,r_quest_questions.CONDITION_FLAG,r_quest_questions.CONDITION_TYPE,r_quest_questions.CONDITION_VALUE,sysdate,user,r_quest_questions.QUESTION_SEQ_NUMBER,1,SYS_GUID(),r_quest_questions.RULE_ID);
		
	EXCEPTION
	WHEN OTHERS THEN
	dbms_output.put_line('QUESTIONNAIRE_REF_ID_FK:'||r_quest_questions.QUESTIONNAIRE_REF_ID_FK||', Error is '||sqlerrm);
	END;


END LOOP;
CLOSE c_quest_questions;
END;
/
declare
	li_questionnaire_usg_id number;
	li_qnr_sequence questionnaire.sequence_number%type;
	li_qnr_ref_id  questionnaire.questionnaire_ref_id%type;
	ls_qnr_nm questionnaire.name%type;
	li_count NUMBER;
begin

  SELECT max(t2.SEQUENCE_NUMBER) into li_qnr_sequence FROM questionnaire t2 WHERE t2.questionnaire_id = 5;
   
  SELECT t1.questionnaire_ref_id,t1.name into li_qnr_ref_id,ls_qnr_nm FROM questionnaire t1
      WHERE t1.questionnaire_id = 5
      AND t1.sequence_number = ( SELECT max(t2.sequence_number)
                                FROM questionnaire t2
                                WHERE t2.questionnaire_id = t1.questionnaire_id
                            );
                            
  select count(questionnaire_usage_id) into li_count
  from questionnaire_usage
  where module_item_code = 3
  and   module_sub_item_code = 0
  and   questionnaire_ref_id_fk = li_qnr_ref_id
  and is_mandatory =  'N'
  and   rule_id is null;
 
  if li_count = 0 then
 
       INSERT INTO QUESTIONNAIRE_USAGE(
       QUESTIONNAIRE_USAGE_ID,
       MODULE_ITEM_CODE,
       MODULE_SUB_ITEM_CODE,
       QUESTIONNAIRE_REF_ID_FK,
       QUESTIONNAIRE_SEQUENCE_NUMBER,
       RULE_ID,
       QUESTIONNAIRE_LABEL,
       UPDATE_TIMESTAMP,
       UPDATE_USER,
       VER_NBR,
       OBJ_ID,
       IS_MANDATORY
       )
       VALUES(
       SEQ_QUESTIONNAIRE_REF_ID.NEXTVAL, 
       3,
       0,
       li_qnr_ref_id,
       li_qnr_sequence,
       null,
       ls_qnr_nm,
       sysdate,
       user,
       1,
       sys_guid(),
       'N' 
       );
   
 end if;
  
 end;
 /
