set serveroutput on;
begin
dbms_output.enable(6500000000);
end;
/
select 'insert award: '|| localtimestamp from dual;
@scripts/insert_award_temp.sql
@scripts/fn_document_nextval.sql
@scripts/insert_temp_krew_create.sql
@scripts/insert_award.sql
--@scripts/insert_krew_tables.sql
--@scripts/insert_award_table_create.sql
@scripts/insert_award_version_history.sql
@scripts/insert_kc_mig_conversion.sql
@scripts/insert_award_special_review.sql
@scripts/insert_award_special_review_update.sql
@scripts/insert_award_cost.sql
@scripts/insert_award_equipment.sql
@scripts/insert_award_foriegn.sql
@scripts/insert_award_payment.sql
@scripts/insert_award_science.sql
@scripts/insert_award_idc.sql
@scripts/insert_award_subcontract.sql
@scripts/insert_award_transferring_sponsor.sql
@scripts/insert_award_key_person.sql
@scripts/insert_award_persons.sql
@scripts/insert_award_sponsor_term.sql
@scripts/insert_award_attachment.sql
@scripts/insert_award_attachment_versioning.sql
@scripts/insert_award_custom.sql
@scripts/insert_award_comment.sql
@scripts/insert_award_comment_update.sql
@scripts/insert_award_closeout.sql
@scripts/insert_award_person_units.sql
--@scripts/insert_award_person_credit_split.sql
--@scripts/insert_award_pers_unit_credit_split.sql
@scripts/insert_award_notepad.sql
@scripts/insert_award_spons_contact.sql
@scripts/insert_award_report_terms.sql
@scripts/insert_award_report_tracking.sql
@scripts/insert_award_funding_proposal.sql
@scripts/insert_award_unit_contacts.sql
@scripts/insert_award_hierarchy.sql
@scripts/insert_award_amount_transaction.sql
@scripts/insert_award_amount_info.sql
@scripts/insert_award_number_updation.sql
select 'update award: '|| localtimestamp from dual;
@scripts/update_award.sql
@scripts/update_award_special_review.sql
@scripts/update_award_special_review_com.sql
@scripts/update_award_cost.sql
@scripts/update_award_equip.sql
@scripts/update_award_foriegn_travel.sql
@scripts/update_award_payment.sql
@scripts/update_award_science.sql
@scripts/update_award_idc.sql
@scripts/update_award_approved_subawards.sql
@scripts/update_award_transfering_spons.sql
@scripts/update_award_keyperson.sql
@scripts/update_award_person.sql
@scripts/update_award_attachment.sql
@scripts/update_award_custom.sql
@scripts/update_award_comments.sql
@scripts/update_award_closeout.sql
@scripts/update_award_person_units.sql
--@scripts/update_award_pers_credit_split.sql
--@scripts/update_award_pers_unit_credit.sql
@scripts/update_award_notepad.sql
@scripts/update_award_spons_con.sql
@scripts/update_award_report.sql
@scripts/update_award_sponsor_term.sql
@scripts/update_award_report_tracking.sql
@scripts/update_award_funding_proposal.sql
@scripts/update_award_unit_contacts.sql
@scripts/update_award_amount_info.sql
@scripts/update_award_trans.sql
@scripts/update_award_fna.sql
@scripts/update_award_sequence_status.sql
select 'Completed Award : '|| localtimestamp from dual;
/