INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','1',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','5',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','6',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
/                    
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','9',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','15',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','16',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=1 AND RATE_TYPE_CODE=1
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','25',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','26',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','28',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','31',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','27',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=2 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','10',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','17',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','24',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','13',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=1
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','10',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=2
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','17',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=2
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','24',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=2
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','13',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=2
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','10',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=3
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','17',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=3
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','24',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=3
/                     
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT COST_ELEMENT,'13','13',ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE RATE_CLASS_CODE=4 AND RATE_TYPE_CODE=3
/                     
commit
/     