Insert into KRCR_PARM_T (NMSPC_CD,CMPNT_CD,PARM_NM,OBJ_ID,VER_NBR,PARM_TYP_CD,VAL,PARM_DESC_TXT,EVAL_OPRTR_CD,APPL_ID) values ('KC-GEN','Document','KC_COI_DB_LINK',sys_guid(),1,'AUTH','KC_COI_DB_LINK','KC_COI_DB_LINK','A','KUALI')
/
