INSERT INTO KRCR_PARM_T (APPL_ID,NMSPC_CD,PARM_TYP_CD,CMPNT_CD,PARM_NM,PARM_DESC_TXT,VAL,EVAL_OPRTR_CD,OBJ_ID,VER_NBR) 
VALUES ('KC','KC-AB','CONFG','D','awardBudgetStatusRePosted','This system parameter maps the AwardBudget status Repost Post','15','A',SYS_GUID(),1)
/
INSERT INTO AWARD_BUDGET_STATUS (AWARD_BUDGET_STATUS_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
VALUES ('15','Re Post','admin',SYSDATE,SYS_GUID(),1)
/
