
INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL, 1001, 501, 	'N',	'Current space insufficient:', 	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL, 1001, 503, 	'N',	'Current space insufficient:', 	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1002,	501,	'Y',	'Use of space other than submitting unit:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1002,	503,	'Y',	'Use of space other than submitting unit:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1003,	501,	'Y',	'Will appoint individuals outside submitting unit:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1003,	503,	'Y',	'Will appoint individuals outside submitting unit:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1004,	501,	'Y',	'Will appoint visitors at MIT:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1004,	503,	'Y',	'Will appoint visitors at MIT:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1011,	501,	'Y',	'Use of animals:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1011,	503,	'Y',	'Use of animals:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1012,	501,	'Y',	'Use of human subjects:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1012,	503,	'Y',	'Use of human subjects:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1008,	501,	'Y',	'Restricted access or use for some researchers:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1008,	503,	'Y',	'Restricted access or use for some researchers:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1009,	501,	'Y',	'Part of project performed outside US:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1009,	503,	'Y',	'Part of project performed outside US:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1010,	501,	'Y',	'Will ship outside the US:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1010,	503,	'Y',	'Will ship outside the US:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1005,	501,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1005,	503,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1005,	502,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1006,	501,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1006,	503,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1006,	502,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1007,	501,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1007,	503,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1007,	502,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1014,	501,	'Y',	'Lobbying:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1014,	503,	'Y',	'Lobbying:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1015,	501,	'Y',	'Potential Debarment Issue:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1015,	503,	'Y',	'Potential Debarment Issue:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1013,	501,	'N',	'Will not certify proposal information:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1016,	503,	'N',	'Will not certify proposal information:',	'admin')
/
