--UPDATED NMSPC_CD FOR WL ROLE-PERMISSION SCRIPT
UPDATE KRIM_PERM_T SET NMSPC_CD='KC-PD' WHERE NMSPC_CD='KC-AWARD' AND NM='View_WL'
/
UPDATE KRIM_PERM_T SET NMSPC_CD='KC-PD' WHERE NMSPC_CD='KC-AWARD' AND NM='Edit_WL'
/
UPDATE KRIM_PERM_T SET NMSPC_CD='KC-PD' WHERE NMSPC_CD='KC-AWARD' AND NM='Run_WL_Simulation'
/
UPDATE KRIM_ROLE_T SET NMSPC_CD='KC-PD' WHERE NMSPC_CD='KC-AWARD' AND role_nm='WL Super User'
/
