INSERT INTO BUDGET_CATEGORY_TYPE(BUDGET_CATEGORY_TYPE_CODE,DESCRIPTION,SORT_ID,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
VALUES('N','Non specified personnel',(select max(SORT_ID)+ 1  from BUDGET_CATEGORY_TYPE),sysdate,'admin',1,sys_guid())
/
INSERT INTO BUDGET_CATEGORY(BUDGET_CATEGORY_CODE,DESCRIPTION,CATEGORY_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
VALUES('38','Award Budget Non Specified Personnel','N',sysdate,'admin',1,sys_guid())
/
INSERT INTO COST_ELEMENT(COST_ELEMENT,DESCRIPTION,BUDGET_CATEGORY_CODE,ON_OFF_CAMPUS_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,ACTIVE_FLAG)
VALUES('P00300','Senior Personnel (Calendar Months)','38','N',sysdate,'admin',1,sys_guid(),'Y')	
/
INSERT INTO COST_ELEMENT(COST_ELEMENT,DESCRIPTION,BUDGET_CATEGORY_CODE,ON_OFF_CAMPUS_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,ACTIVE_FLAG)
VALUES('P00025','Senior Personnel (Academic Months)','38','N',sysdate,'admin',1,sys_guid(),'Y')	
/
INSERT INTO COST_ELEMENT(COST_ELEMENT,DESCRIPTION,BUDGET_CATEGORY_CODE,ON_OFF_CAMPUS_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,ACTIVE_FLAG)
VALUES('P00005','Senior Personnel (Summer Months)','38','N',sysdate,'admin',1,sys_guid(),'Y')	
/
INSERT INTO COST_ELEMENT(COST_ELEMENT,DESCRIPTION,BUDGET_CATEGORY_CODE,ON_OFF_CAMPUS_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,ACTIVE_FLAG)
VALUES('P00390','Postdocs','38','N',sysdate,'admin',1,sys_guid(),'Y')	
/
INSERT INTO COST_ELEMENT(COST_ELEMENT,DESCRIPTION,BUDGET_CATEGORY_CODE,ON_OFF_CAMPUS_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,ACTIVE_FLAG)
VALUES('P00350','Other Professionals','38','N',sysdate,'admin',1,sys_guid(),'Y')	
/
INSERT INTO COST_ELEMENT(COST_ELEMENT,DESCRIPTION,BUDGET_CATEGORY_CODE,ON_OFF_CAMPUS_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,ACTIVE_FLAG)
VALUES('P00706','Graduate Students (Research Assistants)','38','N',sysdate,'admin',1,sys_guid(),'Y')	
/
INSERT INTO COST_ELEMENT(COST_ELEMENT,DESCRIPTION,BUDGET_CATEGORY_CODE,ON_OFF_CAMPUS_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,ACTIVE_FLAG)
VALUES('P00754','Undergraduate Students (UROPs, etc)','38','N',sysdate,'admin',1,sys_guid(),'Y')
/
INSERT INTO COST_ELEMENT(COST_ELEMENT,DESCRIPTION,BUDGET_CATEGORY_CODE,ON_OFF_CAMPUS_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,ACTIVE_FLAG)
VALUES('P00250','Secretarial-Clerical (if charged directly)','38','N',sysdate,'admin',1,sys_guid(),'Y')	
/
INSERT INTO COST_ELEMENT(COST_ELEMENT,DESCRIPTION,BUDGET_CATEGORY_CODE,ON_OFF_CAMPUS_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,ACTIVE_FLAG)
VALUES('P00001','Other Personnel Costs','38','N',sysdate,'admin',1,sys_guid(),'Y')
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00300',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400300'
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00025',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400025'
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00005',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400005'
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00390',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400390'
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00350',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400350'
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00706',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400706'
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00754',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400754'
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00250',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400250'
/
INSERT INTO VALID_CE_RATE_TYPES(COST_ELEMENT,RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT 'P00001',RATE_CLASS_CODE,RATE_TYPE_CODE,ACTIVE_FLAG,sysdate,'admin',1,sys_guid() FROM VALID_CE_RATE_TYPES WHERE COST_ELEMENT='400496'
/
commit
/
