INSERT INTO PERSON_EDITABLE_FIELDS(PERSON_EDITABLE_FIELD_ID, MODULE_CODE, FIELD_NAME, ACTIVE_FLAG, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID) VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL, '3', 'division', 'Y', SYSDATE,'admin', '1', sys_guid())
/
