UPDATE KRCR_PARM_T set VAL ='1' WHERE  PARM_NM='ENABLE_ANIMAL_REVIEW_VALID'
/
UPDATE KRCR_PARM_T set VAL ='1' WHERE  PARM_NM='ENABLE_AWARD_BIOHAZARD_REVIEW_VALID'
/
UPDATE KRCR_PARM_T set VAL ='1' WHERE  PARM_NM='ENABLE_AWARD_HUMAN_REVIEW_VALID'
/
UPDATE KRCR_PARM_T set VAL ='1' WHERE  PARM_NM='ENABLE_AWARD_DNA_REVIEW_VALID'
/
UPDATE KRCR_PARM_T set VAL ='1' WHERE  PARM_NM='ENABLE_AWARD_ISOTOPE_REVIEW_VALID'
/
UPDATE KRCR_PARM_T set VAL ='1' WHERE  PARM_NM='ENABLE_AWARD_INTER_REVIEW_VALID'
/
UPDATE KRCR_PARM_T set VAL ='Y' WHERE  PARM_NM='AWARD_ON_HOLD_BASED_ON_COI'
/
UPDATE KRCR_PARM_T set VAL ='Y' WHERE  PARM_NM='ENABLE_AWARD_NSF_RCR_REVIEW_VALID'
/
UPDATE KRCR_PARM_T set VAL ='Y' WHERE  PARM_NM='ENABLE_AWARD_REPORT_VALIDATION'
/
UPDATE KRCR_PARM_T set VAL ='Y' WHERE  PARM_NM='ENABLE_AWARD_VALIDATIONS'
/
UPDATE KRCR_PARM_T set VAL ='2' WHERE  PARM_NM='IACUC_SPL_REV_TYPE_CODE'
/
UPDATE KRCR_PARM_T set VAL ='1' WHERE  PARM_NM='SPL_REV_TYPE_CODE_HUMAN'
/