INSERT INTO KRIM_TYP_T (KIM_TYP_ID, OBJ_ID, VER_NBR, NM, SRVC_NM, ACTV_IND, NMSPC_CD) 
VALUES( KRIM_TYP_ID_S.NEXTVAL, SYS_GUID(), 1, 'Derived Role: Award Lead Unit OSP Administrator', 'awardLeadUnitOspAdministratorDerivedRoleTypeService', 'Y', 'KC-AWARD')
/
INSERT INTO KRIM_ROLE_T (ROLE_ID, OBJ_ID, VER_NBR, ROLE_NM, NMSPC_CD, DESC_TXT, KIM_TYP_ID, ACTV_IND, LAST_UPDT_DT) 
VALUES (KRIM_ROLE_PERM_ID_S.NEXTVAL, SYS_GUID(), 1, 'Award Lead Unit OSP Administrator', 'KC-AWARD', 'Award Lead Unit OSP Administrator', (SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NMSPC_CD = 'KC-AWARD' AND NM = 'Derived Role: Award Lead Unit OSP Administrator'), 'Y', SYSDATE)
/
INSERT INTO KRCR_PARM_T(NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES
('KC-GEN', 'All', 'OSP_ADMINISTRATOR_TYPE_CODE', SYS_GUID(), '1', 'CONFG', '2', 'OSP Administrator Type Code', 'A', 'KC')
/
