ALTER TABLE  EPS_PROP_SPECIAL_REVIEW  DISABLE CONSTRAINT  FK_EPS_PROP_SP_APPROV_TYPE_KRA;        
ALTER TABLE  VALID_SP_REV_APPROVAL  DISABLE CONSTRAINT  FK_VALID_SP_REV_APPROV_TP_KRA;           
ALTER TABLE  PROPOSAL_SPECIAL_REVIEW  DISABLE CONSTRAINT  FK_PROPOSAL_SP_APROVAL_TYPE; 

TRUNCATE TABLE SP_REV_APPROVAL_TYPE;

INSERT INTO SP_REV_APPROVAL_TYPE(APPROVAL_TYPE_CODE,
DESCRIPTION,
UPDATE_TIMESTAMP,
UPDATE_USER,
VER_NBR,
OBJ_ID)
SELECT APPROVAL_TYPE_CODE,
DESCRIPTION,
UPDATE_TIMESTAMP,
UPDATE_USER,
1, 
SYS_GUID() 
FROM
OSP$SP_REV_APPROVAL_TYPE@coeus.kuali;

ALTER TABLE  EPS_PROP_SPECIAL_REVIEW  ENABLE CONSTRAINT  FK_EPS_PROP_SP_APPROV_TYPE_KRA;        
ALTER TABLE  VALID_SP_REV_APPROVAL  ENABLE CONSTRAINT  FK_VALID_SP_REV_APPROV_TP_KRA;           
ALTER TABLE  PROPOSAL_SPECIAL_REVIEW  ENABLE CONSTRAINT  FK_PROPOSAL_SP_APROVAL_TYPE; 
commit;
/