ALTER TABLE PROTOCOL_VULNERABLE_SUB DISABLE CONSTRAINT FK_PROTOCOL_VULNERABLE_SUB2
/
TRUNCATE TABLE VULNERABLE_SUBJECT_TYPE
/
INSERT INTO VULNERABLE_SUBJECT_TYPE(VULNERABLE_SUBJECT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT VULNERABLE_SUBJECT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,1,SYS_GUID() FROM OSP$VULNERABLE_SUBJECT_TYPE@coeus.kuali
/
DROP TABLE TMP_VULNERABLE_SUBJECT_TYPE
/
CREATE TABLE TMP_VULNERABLE_SUBJECT_TYPE(
VULNERABLE_SUBJECT_TYPE_CODE VARCHAR2(3), 
DESCRIPTION VARCHAR2(200), 
UPDATE_TIMESTAMP TIMESTAMP(6), 
UPDATE_USER VARCHAR2(60), 
VER_NBR NUMBER(8,0), 
OBJ_ID VARCHAR2(36)
)
/
Insert into TMP_VULNERABLE_SUBJECT_TYPE (VULNERABLE_SUBJECT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values ('1','Children',to_timestamp('14-MAR-14 09.55.49.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'admin',1,'F4926C2B1D0D3D63E040DC0A1F8A3C9C');
Insert into TMP_VULNERABLE_SUBJECT_TYPE (VULNERABLE_SUBJECT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values ('10','Other',to_timestamp('14-MAR-14 09.55.49.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'admin',1,'F4926C2B1D163D63E040DC0A1F8A3C9C');
Insert into TMP_VULNERABLE_SUBJECT_TYPE (VULNERABLE_SUBJECT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values ('2','Decisionally impaired',to_timestamp('14-MAR-14 09.55.49.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'admin',1,'F4926C2B1D0E3D63E040DC0A1F8A3C9C');
Insert into TMP_VULNERABLE_SUBJECT_TYPE (VULNERABLE_SUBJECT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values ('3','Employees',to_timestamp('14-MAR-14 09.55.49.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'admin',1,'F4926C2B1D0F3D63E040DC0A1F8A3C9C');
Insert into TMP_VULNERABLE_SUBJECT_TYPE (VULNERABLE_SUBJECT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values ('4','Prisoners',to_timestamp('14-MAR-14 09.55.49.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'admin',1,'F4926C2B1D103D63E040DC0A1F8A3C9C');
Insert into TMP_VULNERABLE_SUBJECT_TYPE (VULNERABLE_SUBJECT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values ('5','Pregnant women',to_timestamp('14-MAR-14 09.55.49.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'admin',1,'F4926C2B1D113D63E040DC0A1F8A3C9C');
Insert into TMP_VULNERABLE_SUBJECT_TYPE (VULNERABLE_SUBJECT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values ('6','Fetuses',to_timestamp('14-MAR-14 09.55.49.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'admin',1,'F4926C2B1D123D63E040DC0A1F8A3C9C');
Insert into TMP_VULNERABLE_SUBJECT_TYPE (VULNERABLE_SUBJECT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values ('7','Students',to_timestamp('14-MAR-14 09.55.49.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'admin',1,'F4926C2B1D133D63E040DC0A1F8A3C9C');
Insert into TMP_VULNERABLE_SUBJECT_TYPE (VULNERABLE_SUBJECT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values ('8','Students - minors',to_timestamp('14-MAR-14 09.55.49.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'admin',1,'F4926C2B1D143D63E040DC0A1F8A3C9C');
Insert into TMP_VULNERABLE_SUBJECT_TYPE (VULNERABLE_SUBJECT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values ('9','Wards of the state',to_timestamp('14-MAR-14 09.55.49.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'admin',1,'F4926C2B1D153D63E040DC0A1F8A3C9C');
/
commit
/
INSERT INTO VULNERABLE_SUBJECT_TYPE(VULNERABLE_SUBJECT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
select 
(select ( max(to_number(vulnerable_subject_type_code))) from VULNERABLE_SUBJECT_TYPE) + rownum as vulnerable_subject_type_code ,
t1.description,t1.UPDATE_TIMESTAMP,t1.UPDATE_USER,1,SYS_GUID() 
from TMP_VULNERABLE_SUBJECT_TYPE t1
left outer join OSP$VULNERABLE_SUBJECT_TYPE@coeus.kuali t2 on
upper(trim(t1.description)) = upper(trim(t2.description))
where t2.description is null
/
commit
/
ALTER TABLE PROTOCOL_VULNERABLE_SUB ENABLE CONSTRAINT FK_PROTOCOL_VULNERABLE_SUB2
/
DROP TABLE TMP_VULNERABLE_SUBJECT_TYPE
/

delete from protocol_attachment_type where DESCRIPTION in ('Debriefing Statement','Parental Consent Form','Interview Consent Form',
'Standard Application','Exempt Application','Survey/Questionnaire');
commit
/
declare
	li_max_type_count number;
Begin
  select max(to_number(type_cd)) into li_max_type_count from protocol_attachment_type;
  
  INSERT INTO protocol_attachment_type (TYPE_CD,DESCRIPTION,VER_NBR,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID)
  SELECT li_max_type_count + rownum,
         t1.DESCRIPTION,
         1,
         t1.UPDATE_TIMESTAMP,
         t1.UPDATE_USER,
         SYS_GUID()
  FROM   OSP$PROTOCOL_DOCUMENT_TYPE@coeus.kuali t1  
  WHERE  t1.DESCRIPTION in ('Debriefing Statement','Parental Consent Form','Interview Consent Form',
'Standard Application','Exempt Application','Survey/Questionnaire');

commit;

end;
/


