DROP TABLE TEMP_PERSON_BIOSKETCH
/
truncate table person_biosketch
/
CREATE TABLE TEMP_PERSON_BIOSKETCH
( PERSON_ID NUMBER(22, 0) NOT NULL,
  BIO_NUMBER	NUMBER(3,0),
  DESCRIPTION VARCHAR2(4000 BYTE),
  DOCUMENT_TYPE_CODE	NUMBER(3,0),
  FILE_NAME VARCHAR2(300 BYTE),
  CONTENT_TYPE VARCHAR2(255 BYTE),
  ATTACHMENT_FILE BLOB,
  UPDATE_USER VARCHAR2(60 BYTE) NOT NULL,
  UPDATE_TIMESTAMP DATE NOT NULL
 )
/  
--drop table TEMP_PERSON_BIOSKETCH;
INSERT INTO TEMP_PERSON_BIOSKETCH(PERSON_ID,BIO_NUMBER,FILE_NAME,CONTENT_TYPE,ATTACHMENT_FILE,UPDATE_USER,UPDATE_TIMESTAMP) 
select T2.PERSON_ID,
T2.BIO_NUMBER,
T2.FILE_NAME,
T2.MIME_TYPE CONTENT_TYPE,
T2.BIO_PDF ATTACHMENT_FILE,
T2.UPDATE_USER,
T2.UPDATE_TIMESTAMP
from OSP$PERSON_BIO_PDF@coeus.kuali T2
/
update TEMP_PERSON_BIOSKETCH T1 set T1.description=(select T2.DESCRIPTION from OSP$PERSON_BIO@coeus.kuali T2 where t1.person_id = t2.person_id AND t1.bio_number = t2.bio_number)
/
DELETE FROM  TEMP_PERSON_BIOSKETCH T1 WHERE (t1.person_id,t1.bio_number)in
(select t2.person_id,t2.bio_number from OSP$PERSON_BIO@coeus.kuali T2  
inner join OSP$EPS_PROP_per_doc_type@coeus.kuali t3 on  t3.DOCUMENT_TYPE_CODE = t2.DOCUMENT_TYPE_CODE
where upper(trim(t3.DESCRIPTION)) <> upper('Biosketch')
)
/
insert into person_biosketch(PERSON_BIOSKETCH_ID,PERSON_ID,DESCRIPTION,FILE_NAME,CONTENT_TYPE,ATTACHMENT_FILE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
select SEQ_PERSON_BIOSKETCH_ID.nextval,t1.person_id,t1.DESCRIPTION,t1.file_name,t1.CONTENT_TYPE,t1.ATTACHMENT_FILE,t1.UPDATE_USER,t1.UPDATE_TIMESTAMP,sys_guid(),1
from TEMP_PERSON_BIOSKETCH T1
/