--Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Aggregator','Aggregator Document Level');
--Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Approver','approver Document Level');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Application Administrator','Application Administrator');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Award Budget Administrator','Award Budget Administrator');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Award Budget Aggregator','Award Budget Aggregator');
--Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Budget Creator','Budget Creator Document Level');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Create Temporary Proposal Log','Create Temporary Proposal Log');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('IACUC Administrator','IACUC Administrator');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('IACUC Protocol Aggregator','IACUC Protocol Aggregator');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('IACUC Protocol Creator','IACUC Protocol Creator');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('IACUC Protocol Viewer','IACUC Protocol Viewer');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('IACUC Reviewer','IACUC Reviewer');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('IP Review Maintainer','IP Review Maintainer');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('IRB Administrator','IRB Administrator');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('IRB Reviewer','IRB Reviewer');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Maintain Custom Reports','Maintain Custom Reports');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Maintain Questionnaire','Maintain Questionnaire');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Modify All Dev Proposals','Modify All Dev Proposals');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Modify Training','Modify Training');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Narrative Writer','Narrative Writer');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('OSP Administrator','OSP Administrator');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('OSP Administrator','Kuali Rules Management System Administrator');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Proposal Creator','Proposal Creator');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Proposal Submission','Proposal Submission');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Protocol Aggregator','Protocol Aggregator');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Protocol Creator','Protocol Creator');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Protocol Viewer','Protocol Viewer');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Role Maintenance','Role Maintenance');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Run Award Reports','Run Award Reports');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Run Committee Reports','Run Committee Reports');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Run Dev Proposal Reports','Run Dev Proposal Reports');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Run Global Reports','Run Global Reports');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Run Person Reports','Run Person Reports');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Run Protocol Reports','Run Protocol Reports');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Run Rolodex Reports','Run Rolodex Reports');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Run Sponsor Reports','Run Sponsor Reports');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Run Unit Reports','Run Unit Reports');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Run User Reports','Run User Reports');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Sponsor Maintainer','Sponsor Maintainer');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('View All Dev Proposals','View All Dev Proposals');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('View all IACUC Protocols','View all IACUC Protocols');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('View Proposal Log','View Proposal Log');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Viewer','Viewer Document Level');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Delete Any Protocol','Protocol Deleter');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('IACUC Protocol Approver','IACUC ProtocolApprover');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('IP Review Maintainer','Institutional Proposal Maintainer');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Maintain Award Budget','Award Budget Maintainer');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Access Institutionally Maintained Salaries','View Institutionally Maintained Salaries');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Access Proposal Person Institutional Salaries','Access_Proposal_Person_Institutional_Salaries');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Approve Award Budget','Award Budget Approver');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Modify Award','Award Modifier');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Modify Award','Time And Money Modifier');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Modify Award Budget','Award Budget Modifier');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Negotiation SuperUser','Negotiation Administrator');
--Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Protocol Approver','ProtocolApprover');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Run Budget Reports','Run Dev Budget Reports');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('View Awards','Award Budget Viewer');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('View Award Budget','Award Budget Viewer');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('View Institute Proposal Document','Institutional Proposal Viewer');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('View Subcontract','View Subaward');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('View Template','Template Viewer');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Modify Subcontract','Modify Subaward');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Maintain Conflict of Interest','COI Maintainer');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Rolodex Maintainer','Address Book Maintainer');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Modify Negotiations','Negotiation Creator');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('Maintain Workload Balancing','WL Super User');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('MAINTAIN USER ROLES','Manager');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('View Shared Award Documents','View Shared Award Attachments');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('View Shared Institute Proposal Documents' , 'View Shared Institute Proposal Attachments');
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES) values ('View All Shared Documents','View All Shared Attachments');
commit
/