CREATE TABLE OSP$S2S_USER_ATTACHED_FORM(
"PROPOSAL_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
"USER_ATTACHED_FORM_NUMBER" NUMBER(3,0) NOT NULL ENABLE, 
"NAMESPACE" VARCHAR2(200), 
"FORM_NAME" VARCHAR2(100), 
"FORM_FILE_NAME" VARCHAR2(100), 
"FORM_FILE" BLOB DEFAULT EMPTY_BLOB(), 
"XML_FILE" CLOB DEFAULT EMPTY_CLOB(), 
"DESCRIPTION" VARCHAR2(2000), 
"UPDATE_USER" VARCHAR2(8) NOT NULL ENABLE, 
"UPDATE_TIMESTAMP" DATE)
/
insert into OSP$S2S_USER_ATTACHED_FORM(PROPOSAL_NUMBER,USER_ATTACHED_FORM_NUMBER,NAMESPACE,FORM_NAME,FORM_FILE_NAME,FORM_FILE,
							XML_FILE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP)
SELECT PROPOSAL_NUMBER,USER_ATTACHED_FORM_NUMBER,NAMESPACE,FORM_NAME,FORM_FILE_NAME,FORM_FILE,XML_FILE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP
FROM OSP$S2S_USER_ATTACHED_FORM@coeus.kuali
/
commit
/
CREATE TABLE OSP$S2S_USER_ATTACHED_FORM_ATT(
"PROPOSAL_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
"USER_ATTACHED_FORM_NUMBER" NUMBER(3,0) NOT NULL ENABLE, 
"USER_ATTACHED_FORM_ATT_NUMBER" NUMBER(3,0) NOT NULL ENABLE, 
"CONTENT_TYPE" VARCHAR2(100), 
"FILE_NAME" VARCHAR2(100), 
"CONTENT_ID" VARCHAR2(350), 
"ATTACHMENT" BLOB DEFAULT EMPTY_BLOB(), 
"UPDATE_USER" VARCHAR2(8) NOT NULL ENABLE, 
"UPDATE_TIMESTAMP" DATE)
/
CREATE TABLE TMP_S2S_USER_ATT_FORM_MAPPING(
PROPOSAL_NUMBER VARCHAR2(8) , 
USER_ATTACHED_FORM_NUMBER NUMBER(3,0) , 
S2S_USER_ATTACHED_FORM_ID NUMBER(12,0)
)
/
insert into OSP$S2S_USER_ATTACHED_FORM_ATT(PROPOSAL_NUMBER,USER_ATTACHED_FORM_NUMBER,USER_ATTACHED_FORM_ATT_NUMBER,CONTENT_TYPE,
											FILE_NAME,CONTENT_ID,ATTACHMENT,UPDATE_USER,UPDATE_TIMESTAMP)
SELECT PROPOSAL_NUMBER,USER_ATTACHED_FORM_NUMBER,USER_ATTACHED_FORM_ATT_NUMBER,CONTENT_TYPE,FILE_NAME,CONTENT_ID,ATTACHMENT,UPDATE_USER,
UPDATE_TIMESTAMP FROM OSP$S2S_USER_ATTACHED_FORM_ATT@coeus.kuali
/
commit
/
set serveroutput on
/
DECLARE
	li_s2s_user_att NUMBER(12,0);
	li_s2s_user_att_form NUMBER(12,0);
	li_s2s_user_att_id NUMBER(12,0);
	li_s2s_user_form_id NUMBER(12,0);
CURSOR c_s2s_user IS
	SELECT s.PROPOSAL_NUMBER,s.NAMESPACE,s.USER_ATTACHED_FORM_NUMBER,s.FORM_NAME,s.FORM_FILE_NAME,s.FORM_FILE,s.XML_FILE,s.DESCRIPTION,s.UPDATE_USER, s.UPDATE_TIMESTAMP
	FROM OSP$S2S_USER_ATTACHED_FORM s;
r_s2s_user c_s2s_user %ROWTYPE;
li_count number;
BEGIN

	IF c_s2s_user%ISOPEN THEN
	CLOSE c_s2s_user;
	END IF;
	
	OPEN c_s2s_user;
	LOOP
	FETCH c_s2s_user INTO r_s2s_user;
	EXIT WHEN c_s2s_user%NOTFOUND;

	select count(PROPOSAL_NUMBER) into li_count FROM S2S_USER_ATTACHED_FORM
	WHERE PROPOSAL_NUMBER = to_NUMBER(r_s2s_user.PROPOSAL_NUMBER)
	AND trim(NAMESPACE) = trim(r_s2s_user.NAMESPACE);	
	
	if li_count = 0 then 
	
		begin
			SELECT SEQ_S2S_USER_ATTD_FORM_ID.NEXTVAL INTO li_s2s_user_att FROM DUAL;
			SELECT SEQ_S2S_USER_ATTD_FORM_FILE_ID.NEXTVAL INTO li_s2s_user_att_form FROM DUAL;
			
		
			INSERT INTO TMP_S2S_USER_ATT_FORM_MAPPING(PROPOSAL_NUMBER,USER_ATTACHED_FORM_NUMBER,S2S_USER_ATTACHED_FORM_ID)
			VALUES(r_s2s_user.PROPOSAL_NUMBER,r_s2s_user.USER_ATTACHED_FORM_NUMBER,li_s2s_user_att);			
			
			INSERT INTO S2S_USER_ATTACHED_FORM(S2S_USER_ATTACHED_FORM_ID,PROPOSAL_NUMBER,NAMESPACE,FORM_NAME,FORM_FILE_NAME,DESCRIPTION,UPDATE_USER,
			UPDATE_TIMESTAMP,VER_NBR,OBJ_ID)
			VALUES(li_s2s_user_att,to_NUMBER(r_s2s_user.PROPOSAL_NUMBER),r_s2s_user.NAMESPACE,r_s2s_user.FORM_NAME,r_s2s_user.FORM_FILE_NAME,
			r_s2s_user.DESCRIPTION,r_s2s_user.UPDATE_USER,r_s2s_user.UPDATE_TIMESTAMP,1,SYS_GUID());

			INSERT INTO S2S_USER_ATTACHED_FORM_FILE(S2S_USER_ATTACHED_FORM_FILE_ID,S2S_USER_ATTACHED_FORM_ID,FORM_FILE,XML_FILE,UPDATE_USER,
			UPDATE_TIMESTAMP,VER_NBR,OBJ_ID)
			VALUES(li_s2s_user_att_form,li_s2s_user_att,r_s2s_user.FORM_FILE,r_s2s_user.XML_FILE,r_s2s_user.UPDATE_USER,r_s2s_user.UPDATE_TIMESTAMP,
			1,SYS_GUID());
			
		exception
		when others then
			dbms_output.put_line('Error occoured in PD( block1 ), proposal number '||to_NUMBER(r_s2s_user.PROPOSAL_NUMBER)||'. '||sqlerrm);
		end;
		
	end if;	
  
	END LOOP;
	CLOSE c_s2s_user;
END;
/
DECLARE
	li_s2s_user_att NUMBER(12,0);
	li_s2s_user_att_form NUMBER(12,0);
	li_s2s_user_att_id NUMBER(12,0);
	li_s2s_user_form_id NUMBER(12,0);
CURSOR c_s2s_user IS
	SELECT u.PROPOSAL_NUMBER, u.USER_ATTACHED_FORM_NUMBER, u.UPDATE_USER, u.UPDATE_TIMESTAMP, u.CONTENT_TYPE, u.FILE_NAME, u.CONTENT_ID, u.ATTACHMENT
	FROM OSP$S2S_USER_ATTACHED_FORM_ATT u;
r_s2s_user c_s2s_user %ROWTYPE;

BEGIN

	IF c_s2s_user%ISOPEN THEN
	CLOSE c_s2s_user;
	END IF;
	
	OPEN c_s2s_user;
	LOOP
	FETCH c_s2s_user INTO r_s2s_user;
	EXIT WHEN c_s2s_user%NOTFOUND;

		begin
	
			SELECT SEQ_S2S_USER_ATTD_FORM_ATT_ID.NEXTVAL INTO li_s2s_user_att_id FROM DUAL;
			SELECT SEQ_S2S_USR_ATD_FRM_ATT_FLE_ID.NEXTVAL INTO li_s2s_user_form_id FROM DUAL;

			SELECT S2S_USER_ATTACHED_FORM_ID INTO li_s2s_user_att FROM TMP_S2S_USER_ATT_FORM_MAPPING
			WHERE PROPOSAL_NUMBER = r_s2s_user.PROPOSAL_NUMBER
			AND USER_ATTACHED_FORM_NUMBER = r_s2s_user.USER_ATTACHED_FORM_NUMBER;			
			
			INSERT INTO S2S_USER_ATTACHED_FORM_ATT(S2S_USER_ATTACHED_FORM_ATT_ID,S2S_USER_ATTACHED_FORM_ID,PROPOSAL_NUMBER,CONTENT_TYPE,FILE_NAME,
			CONTENT_ID,UPDATE_USER,UPDATE_TIMESTAMP,VER_NBR,OBJ_ID)
			VALUES(li_s2s_user_att_id,li_s2s_user_att,to_NUMBER(r_s2s_user.PROPOSAL_NUMBER),r_s2s_user.CONTENT_TYPE,r_s2s_user.FILE_NAME,
			r_s2s_user.CONTENT_ID,r_s2s_user.UPDATE_USER,r_s2s_user.UPDATE_TIMESTAMP,1,SYS_GUID());

			INSERT INTO S2S_USER_ATTD_FORM_ATT_FILE(S2S_USER_ATTD_FORM_ATT_FILE_ID,S2S_USER_ATTACHED_FORM_ATT_ID,ATTACHMENT,UPDATE_USER,
			UPDATE_TIMESTAMP,VER_NBR,OBJ_ID)
			VALUES(li_s2s_user_form_id,li_s2s_user_att_id,r_s2s_user.ATTACHMENT,r_s2s_user.UPDATE_USER,r_s2s_user.UPDATE_TIMESTAMP,1,SYS_GUID());
		
		exception
		when others then
			dbms_output.put_line('Error occoured in PD( block2 ), proposal number '||to_NUMBER(r_s2s_user.PROPOSAL_NUMBER)||'. '||sqlerrm);
		end;

	END LOOP;
	CLOSE c_s2s_user;
END;
/