select ' Start time of SUBAWARD_AMT_RELEASED is '|| localtimestamp from dual
/
DELETE FROM SUBAWARD_AMT_RELEASED WHERE subaward_code in ( SELECT to_number(SUBCONTRACT_CODE) FROM  OSP$SUBCONTRACT_AMT_RELEASED@coeus.kuali)
/
commit
/
CREATE TABLE OSP$SUBCONTRACT_AMT_RELEASED(
SUBCONTRACT_CODE VARCHAR2(20), 
SEQUENCE_NUMBER NUMBER(4,0), 
LINE_NUMBER NUMBER(4,0), 
AMOUNT_RELEASED NUMBER(12,2), 
EFFECTIVE_DATE DATE , 
COMMENTS VARCHAR2(300), 
UPDATE_TIMESTAMP DATE, 
UPDATE_USER VARCHAR2(8), 
INVOICE_NUMBER VARCHAR2(50), 
START_DATE DATE, 
END_DATE DATE, 
STATUS_CODE VARCHAR2(1), 
APPROVAL_COMMENTS VARCHAR2(2000), 
APPROVED_BY_USER VARCHAR2(8), 
APPROVAL_DATE DATE, 
DOCUMENT BLOB, 
FILE_NAME VARCHAR2(150), 
CREATED_BY VARCHAR2(8), 
CREATED_DATE DATE, 
MIME_TYPE VARCHAR2(100))
/
delete from OSP$SUBCONTRACT_AMT_RELEASED
/
commit
/
insert into OSP$SUBCONTRACT_AMT_RELEASED(SUBCONTRACT_CODE,LINE_NUMBER,SEQUENCE_NUMBER,AMOUNT_RELEASED,EFFECTIVE_DATE,COMMENTS,
UPDATE_TIMESTAMP,UPDATE_USER,INVOICE_NUMBER,START_DATE,END_DATE,STATUS_CODE,APPROVAL_COMMENTS,APPROVED_BY_USER,
APPROVAL_DATE,DOCUMENT,FILE_NAME,CREATED_BY,CREATED_DATE,MIME_TYPE)
SELECT SUBCONTRACT_CODE,LINE_NUMBER,SEQUENCE_NUMBER,AMOUNT_RELEASED,EFFECTIVE_DATE,COMMENTS,UPDATE_TIMESTAMP,UPDATE_USER,INVOICE_NUMBER,
START_DATE,END_DATE,STATUS_CODE,APPROVAL_COMMENTS,APPROVED_BY_USER,APPROVAL_DATE,DOCUMENT,FILE_NAME,CREATED_BY,CREATED_DATE,MIME_TYPE
FROM OSP$SUBCONTRACT_AMT_RELEASED@Coeus.Kuali
/
commit
/
DECLARE
li_ver_nbr NUMBER(8):=1;
li_amt_released NUMBER(12,0);
li_seq NUMBER(4);
li_subaward_id NUMBER(12,0);
ls_subaward_code VARCHAR2(20);
ls_app_id VARCHAR2(40);
ls_create_id VARCHAR2(40);
ls_app_comm VARCHAR2(2000);
ls_invoice VARCHAR2(50);
ls_sub_awd VARCHAR2(20);
li_mit_seq NUMBER(4);

CURSOR c_subaward IS
SELECT SUBAWARD_CODE,SEQUENCE_NUMBER FROM SUBAWARD ORDER BY SUBAWARD_CODE,SEQUENCE_NUMBER;
r_subaward c_subaward%ROWTYPE;

CURSOR c_amt(as_mit varchar2,as_seq number) IS
SELECT SUBCONTRACT_CODE,LINE_NUMBER,as_seq as SEQUENCE_NUMBER,AMOUNT_RELEASED,EFFECTIVE_DATE,COMMENTS,UPDATE_TIMESTAMP,UPDATE_USER,
INVOICE_NUMBER,START_DATE,END_DATE,STATUS_CODE,APPROVAL_COMMENTS,APPROVED_BY_USER,APPROVAL_DATE,DOCUMENT,FILE_NAME,CREATED_BY,CREATED_DATE,MIME_TYPE
FROM OSP$SUBCONTRACT_AMT_RELEASED
where SUBCONTRACT_CODE = as_mit
and SEQUENCE_NUMBER =	( select max(aw.sequence_number) from OSP$SUBCONTRACT_AMT_RELEASED aw 
						 where  aw.SUBCONTRACT_CODE = osp$subcontract_amt_released.subcontract_code 
						 AND aw.line_number = osp$subcontract_amt_released.line_number
						 and aw.sequence_number <= as_seq );
r_amt c_amt%ROWTYPE;

BEGIN

IF c_subaward%ISOPEN THEN
CLOSE c_subaward;
END IF;
OPEN c_subaward;
LOOP
FETCH c_subaward INTO r_subaward;
EXIT WHEN c_subaward%NOTFOUND;

	select LTRIM(TO_CHAR(r_subaward.SUBAWARD_CODE, '00000000')) into ls_sub_awd from dual;
--SELECT FN_GET_SEQ(r_subaward.SUBAWARD_CODE,r_subaward.SEQUENCE_NUMBER) INTO li_mit_seq FROM DUAL;
	li_mit_seq:=r_subaward.SEQUENCE_NUMBER;


			IF c_amt%ISOPEN THEN
			CLOSE c_amt;
			END IF;
			OPEN c_amt(ls_sub_awd,li_mit_seq);
			LOOP
			
			FETCH c_amt INTO r_amt;
			EXIT WHEN c_amt%NOTFOUND;
			
				li_seq:=r_subaward.SEQUENCE_NUMBER;
				--SELECT FN_GET_KUALI_SEQ(r_amt.SUBCONTRACT_CODE,r_amt.SEQUENCE_NUMBER) INTO li_seq FROM DUAL;
				SELECT SUBAWARD_AMT_REL_ID_S.NEXTVAL INTO li_amt_released FROM DUAL;
				
				BEGIN
					SELECT SUBAWARD_ID INTO li_subaward_id FROM SUBAWARD WHERE SUBAWARD_CODE=r_subaward.SUBAWARD_CODE AND SEQUENCE_NUMBER=li_seq;
					
				EXCEPTION 
				WHEN OTHERS THEN 
				dbms_output.put_line('MISSING SUBAWARD_ID,SUBAWARD_CODE:'||to_number(r_amt.SUBCONTRACT_CODE) ||'SEQUENCE_NUMBER:'||li_seq||'-'||sqlerrm);
				END;
				
				SELECT to_number(r_amt.SUBCONTRACT_CODE) INTO ls_subaward_code FROM dual;
				BEGIN
					SELECT PRNCPL_ID INTO ls_create_id  FROM KRIM_PRNCPL_T WHERE PRNCPL_NM=lower(r_amt.CREATED_BY);
					
				EXCEPTION
				WHEN OTHERS THEN
				ls_create_id:=Null;
				END;
				
				BEGIN
					INSERT INTO SUBAWARD_AMT_RELEASED(SUBAWARD_AMT_RELEASED_ID,SUBAWARD_ID,AMOUNT_RELEASED,EFFECTIVE_DATE,COMMENTS,UPDATE_TIMESTAMP,UPDATE_USER,INVOICE_NUMBER,START_DATE,END_DATE,STATUS_CODE,APPROVAL_COMMENTS,APPROVED_BY_USER,APPROVAL_DATE,DOCUMENT,FILE_NAME,CREATED_BY,CREATED_DATE,MIME_TYPE,VER_NBR,OBJ_ID,SEQUENCE_NUMBER,SUBAWARD_CODE,DOCUMENT_NUMBER,INVOICE_STATUS)
					VALUES(li_amt_released,li_subaward_id,r_amt.AMOUNT_RELEASED,r_amt.EFFECTIVE_DATE,r_amt.COMMENTS,r_amt.UPDATE_TIMESTAMP,r_amt.UPDATE_USER,r_amt.INVOICE_NUMBER,r_amt.START_DATE,r_amt.END_DATE,r_amt.STATUS_CODE,r_amt.APPROVAL_COMMENTS,r_amt.APPROVED_BY_USER,r_amt.APPROVAL_DATE,r_amt.DOCUMENT,r_amt.FILE_NAME,ls_create_id,r_amt.CREATED_DATE,null,li_ver_nbr, SYS_GUID(),li_seq,ls_subaward_code,null,null);

				EXCEPTION
				WHEN OTHERS THEN
					ls_app_id:=null;
					dbms_output.put_line('ERROR IN SUBAWARD_AMT_RELEASED,SUBAWARD_CODE:'||r_amt.SUBCONTRACT_CODE||'SEQUENCE_NUMBER:'||r_amt.SEQUENCE_NUMBER);
				END;

			END LOOP;
			CLOSE c_amt;
			
END LOOP;
CLOSE c_subaward;
			
END;
/
COMMIT
/
DROP TABLE OSP$SUBCONTRACT_AMT_RELEASED
/
select ' End time of SUBAWARD_AMT_RELEASED is '|| localtimestamp from dual
/