-- 48 in PERSON_CUSTOM_DATA is the duplicate data
DELETE FROM  PERSON_CUSTOM_DATA where CUSTOM_ATTRIBUTE_ID in ('48')
/
-- test sql
-- it is duplicate here and not using in SUBAWARD_CUSTOM_DATA
-- select * from  kcso.SUBAWARD_CUSTOM_DATA where  custom_attribute_id in (65)
DELETE FROM custom_attribute_document where  custom_attribute_id in (65)
/
commit
/
CREATE TABLE TMP_CUSTOM_ATTRIBUTE_050415
AS
SELECT * FROM CUSTOM_ATTRIBUTE WHERE ID IN ( select max(id) from custom_attribute t1 group by t1.name having max(id) <> min(id) )
AND ID not in (
    SELECT CUSTOM_ATTRIBUTE_ID FROM AWARD_CUSTOM_DATA
    union
    SELECT CUSTOM_ATTRIBUTE_ID FROM  PERSON_CUSTOM_DATA
    union 
    SELECT PROC_CUSTOM_ATTRIBUTE_ID FROM  IACUC_PROTO_STUDY_CUSTOM_DATA
    union 
    SELECT CUSTOM_ATTRIBUTE_ID FROM  IACUC_PROTOCOL_CUSTOM_DATA
    union
    SELECT CUSTOM_ATTRIBUTE_ID FROM  NEGOTIATION_CUSTOM_DATA
    union
    SELECT CUSTOM_ATTRIBUTE_ID FROM  PROPOSAL_CUSTOM_DATA
    union
    SELECT CUSTOM_ATTRIBUTE_ID FROM  CUSTOM_ATTRIBUTE_DOC_VALUE
    union
    SELECT CUSTOM_ATTRIBUTE_ID FROM  SUBAWARD_CUSTOM_DATA
)
/
DELETE FROM CUSTOM_ATTRIBUTE WHERE ID  IN ( select max(id) from custom_attribute t1 group by t1.name having max(id) <> min(id) )
AND ID not in (
    SELECT CUSTOM_ATTRIBUTE_ID FROM AWARD_CUSTOM_DATA
    union
    SELECT CUSTOM_ATTRIBUTE_ID FROM  PERSON_CUSTOM_DATA
    union 
    SELECT PROC_CUSTOM_ATTRIBUTE_ID FROM  IACUC_PROTO_STUDY_CUSTOM_DATA
    union 
    SELECT CUSTOM_ATTRIBUTE_ID FROM  IACUC_PROTOCOL_CUSTOM_DATA
    union
    SELECT CUSTOM_ATTRIBUTE_ID FROM  NEGOTIATION_CUSTOM_DATA
    union
    SELECT CUSTOM_ATTRIBUTE_ID FROM  PROPOSAL_CUSTOM_DATA
    union
    SELECT CUSTOM_ATTRIBUTE_ID FROM  CUSTOM_ATTRIBUTE_DOC_VALUE
    union
    SELECT CUSTOM_ATTRIBUTE_ID FROM  SUBAWARD_CUSTOM_DATA
)
/
commit
/
