
  CREATE OR REPLACE FORCE VIEW "OSPA"."PERSON_REFERENCES" ("PERSON_ID") AS 
  select CUSTOM_FIELD2 from CITI_TRAINING
 union 
select INST_PERSONID from CITI_USERS
 union 
select PERSON_ID from OSP$ANNUAL_PIS
 union 
select PERSON_ID from OSP$APPOINTMENTS
 union 
select PI_PERSON_ID from OSP$ARRA_REPORT_AWARDS
 union 
select PERSON_ID from OSP$ARRA_REPORT_JOBS
 union 
select PERSON_ID from OSP$AWARD_APPRVD_FOREIGN_TRIP
 union 
select PERSON_ID from OSP$AWARD_INVESTIGATORS where NON_MIT_PERSON_FLAG = 'N'
 union 
select PERSON_ID from OSP$AWARD_KEY_PERSONS where NON_MIT_PERSON_FLAG = 'N'
 union 
select SUBMITTED_BY from OSP$AWARD_PAYMENT_SCHEDULE
 union 
select PERSON_ID from OSP$AWARD_REPORTING
 union 
select ADMINISTRATOR from OSP$AWARD_UNIT_ADMINISTRATORS
 union 
select PERSON_ID from OSP$BUDGET_PERSONS where  NON_EMPLOYEE_FLAG = 'N'
 union 
select PERSON_ID from OSP$CITI_ERROR_LOG
 union 
select PERSON_ID from OSP$COI_FINANCIAL_ENTITIES
 union 
select PERSON_ID from OSP$COMM_MEMBERSHIPS
 union 
select PERSON_ID from OSP$COMM_SCHEDULE_ATTENDANCE
 union 
select ALTERNATE_FOR from OSP$COMM_SCHEDULE_ATTENDANCE
 union 
select PERSON_ID from OSP$EPS_PROP_HIER_ATT_LINKS
 union 
select PERSON_ID from OSP$EPS_PROP_PERSON
 union 
select PERSON_ID from OSP$FIN_INT_ENTITY_YNQ
 union 
select PERSON_ID from OSP$INV_COI_DISCLOSURE
 union 
select PERSON_ID from OSP$NDA
 union 
select NEGOTIATOR_ID from OSP$NEGOTIATIONS
 union 
select PERSON_ID from OSP$ORGANIZATION_CORRESPONDENT
 union 
select PERSON_ID from OSP$PERSON_FIN_INT_DISCLOSURE
 union 
select PERSON_ID from OSP$PERSON_PREFERENCES
 union 
select PERSON_ID from OSP$PERSON_TRAINING
 union 
select INITIAL_CONTRACT_ADMIN from OSP$PROPOSAL
 union 
select IP_REVIEWER from OSP$PROPOSAL
 union 
select PERSON_ID from OSP$PROPOSAL_INVESTIGATORS where NON_MIT_PERSON_FLAG = 'N'
 union 
select PERSON_ID from OSP$PROPOSAL_KEY_PERSONS where NON_MIT_PERSON_FLAG = 'N'
 union 
select PI_ID from OSP$PROPOSAL_LOG
 union 
select ADMINISTRATOR from OSP$PROP_UNIT_ADMINISTRATORS
 union 
select PERSON_ID from OSP$PROTOCOL_CORRESPONDENTS
 union 
select PERSON_ID from OSP$PROTOCOL_INVESTIGATORS
 union 
select PERSON_ID from OSP$PROTOCOL_KEY_PERSONS
 union 
select PERSON_ID from OSP$PROTOCOL_REVIEWERS
 union 
select PERSON_ID from OSP$PROTOCOL_VOTE_ABSTAINEES
 union 
select PERSON_ID from OSP$PROTO_CORRESP_RECIPIENTS
 union 
select PERSON_ID from OSP$RCR_APPOINTMENTS
 union 
select PERSON_ID from OSP$RCR_PAYROLL_DATES
 union 
select PERSON_ID from OSP$SPONSOR_CONTACT
 union 
select REQUISITIONER_ID from OSP$SUBCONTRACT
 union 
select ADMINISTRATIVE_OFFICER from OSP$UNIT
 union 
select OSP_ADMINISTRATOR from OSP$UNIT
 union 
select UNIT_HEAD from OSP$UNIT
 union 
select DEAN_VP from OSP$UNIT
 union 
select OTHER_INDIVIDUAL_TO_NOTIFY from OSP$UNIT
 union 
select ADMINISTRATOR from OSP$UNIT_ADMINISTRATORS
 union 
select PERSON_ID from OSP$USER 
 ;
