create user admin identified by devadminkc;
grant create session to admin ;
create user sdowdy identified by devsdowdykc;
grant create session to sdowdy;
create user geot identified by devgeotkc;
grant create session to geot;
create user snair identified by devsnairkc;
grant create session to snair;
create user ele identified by develekc;
grant create session to ele;
create user jenlu identified by devjenlukc;
grant create session to jenlu;
create user aeh identified by devaehkc;
grant create session to aeh;
create user cwood identified by devcwoodkc;
grant create session to cwood;
create user rhanlon identified by devrhanlonkc;
grant create session to rhanlon;
create user pviejo identified by devpviejokc;
grant create session to pviejo;
create user kcuser01 identified by kcuser01;
grant create session to kcuser01;
create user kcuser02 identified by kcuser02;
grant create session to kcuser02;
create user kcuser03 identified by kcuser03;
grant create session to kcuser03;
create user kwahl identified by devkwahlkc;
grant create session to kwahl;
create user laroche identified by devlarochekc;
grant create session to laroche;
create user bcicc identified by devbcicckc;
grant create session to bcicc;
create user kdawson identified by devkdawsonkc;
grant create session to kdawson;
create user mi23748 identified by devmi23748kc;
grant create session to mi23748;

create role KC_VIEW;
grant select any table to KC_VIEW;
create role KC_EDIT;
grant select any table,delete any table,update any table to KC_EDIT;
grant all privileges to KC_EDIT;
grant KC_EDIT to sdowdy;
grant KC_EDIT to geot;
grant KC_EDIT to snair;
grant KC_EDIT to ele;
grant KC_EDIT to jenlu;
grant KC_VIEW to aeh;
grant KC_VIEW to rhanlon;
grant KC_VIEW to pviejo;
grant KC_VIEW to kdawson;
grant KC_VIEW to bcicc;

create user klazzaro identified by devklazzarokc;
grant create session to klazzaro;
grant KC_VIEW to klazzaro;
create user mff identified by devmffkc;
grant create session to mff;
grant KC_VIEW to mff;
create user kdenutte identified by devkdenuttekc;
grant create session to kdenutte;
grant KC_VIEW to kdenutte;
create user acia identified by devaciakc;
grant create session to acia;
grant KC_VIEW to acia;
create user lpiazza identified by devlpiazzakc;
grant create session to lpiazza;
create user rmathews identified by devrmathewskc;
grant create session to rmathews;
grant KC_VIEW to rmathews;
create user hponnoju identified by devhponnojukc;
grant create session to hponnoju;
grant KC_VIEW to hponnoju;
create user rlay identified by devrlaykc;
grant create session to rlay;
grant KC_VIEW to rlay;
create user vineeth identified by devvineethkc;
grant create session to vineeth;
grant KC_EDIT to vineeth;
create user jenlu identified by devjenlukc;
grant create session to jenlu;
grant KC_EDIT to jenlu;

create user brown_ed identified by consbrown_edkc;
grant create session to brown_ed;

alter user jenflach identified by consjenflachkc;

create user ryetter identified by consryetterkc;
grant create session to ryetter;
