select * from OSP$AWARD_HOLD_MESSAGES

select * from OSP$AWARD_HOLD_MESSAGES_ALL

select * from OSP$EVERIFY_NOTIF_DETAILS

desc OSP$EVERIFY_NOTIF_DETAILS

desc OSPA.NOVI_LONG_SURVEY_RESP

desc OSP$LONG_SURVEY_NOTIF

select * from OSP$LONG_SURVEY_NOTIF

desc OSP$NDA

desc OSP$RCR_NOTIF_TYPE

desc OSP$RCR_NOTIFICATIONS

select * from OSP$RCR_NOTIFICATIONS

desc OSP$RCR_NOTIF_DETAILS

desc OSP$RCR_APPOINTMENTS

desc OSP$RCR_PAYROLL_DATES

desc OSP$RCR_APPOINT_WH

desc OSP$RCR_PAYROLL_WH

desc OSPA.unit_ad_load -- What is this being used for?

desc OSP$RCR_APPOINTMENTS_DROPPED

desc OSP$RCR_PAYROLL_DATES_DROPPED

desc OSP$AWARD_APPROVED_SUBCONTRACT