DROP TABLE Test_APPOINTMENT
/
DROP TABLE TEST_KRB_PERSON
/
DROP TABLE test_degree
/
DROP TABLE TEST_PERSON_FEED
/
CREATE TABLE Test_APPOINTMENT
   (	"MIT_ID" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"UNIT_NUMBER" VARCHAR2(8 BYTE), 
	"PRIMARY_SECONDARY_INDICATOR" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"APPOINTMENT_START_DATE" DATE, 
	"APPOINTMENT_END_DATE" DATE, 
	"APPOINTMENT_TYPE" VARCHAR2(30 BYTE), 
	"JOB_TITLE" VARCHAR2(50 BYTE), 
	"PREFERED_JOB_TITLE" VARCHAR2(51 BYTE), 
	"JOB_CODE" VARCHAR2(9 BYTE)
   ); 
 CREATE TABLE test_degree
   (	"PERSON_ID" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"DEGREE_CODE" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"GRADUATION_DATE" DATE NOT NULL ENABLE, 
	"DEGREE" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"FIELD_OF_STUDY" VARCHAR2(80 BYTE), 
	"SPECIALIZATION" VARCHAR2(80 BYTE), 
	"SCHOOL" VARCHAR2(50 BYTE), 
	"SCHOOL_ID" VARCHAR2(20 BYTE)
   );  
   CREATE TABLE TEST_KRB_PERSON 
   (	"MIT_ID" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"KRB_NAME" VARCHAR2(90 BYTE)
   ) ;
CREATE TABLE test_person_feed
   (	"MIT_ID" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"SSN" VARCHAR2(9 BYTE), 
	"LAST_NAME" VARCHAR2(30 BYTE), 
	"FIRST_NAME" VARCHAR2(30 BYTE), 
	"MIDDLE_NAME" VARCHAR2(30 BYTE), 
	"FULL_NAME" VARCHAR2(90 BYTE), 
	"PRIOR_NAME" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(60 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(60 BYTE), 
	"DATE_OF_BIRTH" DATE, 
	"AGE" NUMBER(3,0), 
	"AGE_BY_FISCAL_YEAR" NUMBER(3,0), 
	"GENDER" VARCHAR2(30 BYTE), 
	"RACE" VARCHAR2(30 BYTE), 
	"EDUCATION_LEVEL" VARCHAR2(30 BYTE), 
	"DEGREE" VARCHAR2(11 BYTE), 
	"MAJOR" VARCHAR2(30 BYTE), 
	"IS_HANDICAPPED" CHAR(1 BYTE), 
	"HANDICAP_TYPE" VARCHAR2(30 BYTE), 
	"IS_VETERAN" CHAR(1 BYTE), 
	"VETERAN_TYPE" VARCHAR2(30 BYTE), 
	"VISA_CODE" VARCHAR2(20 BYTE), 
	"VISA_TYPE" VARCHAR2(30 BYTE), 
	"VISA_RENEWAL_DATE" DATE, 
	"HAS_VISA" CHAR(1 BYTE), 
	"OFFICE_LOCATION" VARCHAR2(30 BYTE), 
	"OFFICE_PHONE" VARCHAR2(20 BYTE), 
	"SECONDRY_OFFICE_LOCATION" VARCHAR2(30 BYTE), 
	"SECONDRY_OFFICE_PHONE" VARCHAR2(20 BYTE), 
	"SCHOOL" VARCHAR2(50 BYTE), 
	"YEAR_GRADUATED" VARCHAR2(30 BYTE), 
	"DIRECTORY_DEPARTMENT" VARCHAR2(30 BYTE), 
	"SALUTATION" VARCHAR2(30 BYTE), 
	"COUNTRY_OF_CITIZENSHIP" VARCHAR2(30 BYTE), 
	"PRIMARY_TITLE" VARCHAR2(51 BYTE), 
	"DIRECTORY_TITLE" VARCHAR2(50 BYTE), 
	"HOME_UNIT" VARCHAR2(8 BYTE), 
	"IS_FACULTY" CHAR(1 BYTE), 
	"IS_GRADUATE_STUDENT_STAFF" CHAR(1 BYTE), 
	"IS_RESEARCH_STAFF" CHAR(1 BYTE), 
	"IS_SERVICE_STAFF" CHAR(1 BYTE), 
	"IS_SUPPORT_STAFF" CHAR(1 BYTE), 
	"IS_OTHER_ACCADEMIC_GROUP" CHAR(1 BYTE), 
	"IS_MEDICAL_STAFF" CHAR(1 BYTE), 
	"VACATION_ACCURAL" CHAR(1 BYTE), 
	"IS_ON_SABBATICAL" CHAR(1 BYTE), 
	"ID_PROVIDED" VARCHAR2(30 BYTE), 
	"ID_VERIFIED" VARCHAR2(30 BYTE), 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"ADDRESS_LINE_1" VARCHAR2(80 BYTE), 
	"ADDRESS_LINE_2" VARCHAR2(80 BYTE), 
	"ADDRESS_LINE_3" VARCHAR2(80 BYTE), 
	"CITY" VARCHAR2(30 BYTE), 
	"COUNTY" VARCHAR2(30 BYTE), 
	"STATE" VARCHAR2(30 BYTE), 
	"POSTAL_CODE" VARCHAR2(15 BYTE), 
	"COUNTRY_CODE" CHAR(3 BYTE), 
	"FAX_NUMBER" VARCHAR2(20 BYTE), 
	"PAGER_NUMBER" VARCHAR2(20 BYTE), 
	"MOBILE_PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"ERA_COMMONS_USER_NAME" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"SALARY_ANNIVERSARY_DATE" DATE
   ); 
Insert into test_person_feed (MIT_ID,SSN,LAST_NAME,FIRST_NAME,MIDDLE_NAME,FULL_NAME,PRIOR_NAME,USER_NAME,EMAIL_ADDRESS,DATE_OF_BIRTH,AGE,AGE_BY_FISCAL_YEAR,GENDER,RACE,EDUCATION_LEVEL,DEGREE,MAJOR,IS_HANDICAPPED,HANDICAP_TYPE,IS_VETERAN,VETERAN_TYPE,VISA_CODE,VISA_TYPE,VISA_RENEWAL_DATE,HAS_VISA,OFFICE_LOCATION,OFFICE_PHONE,SECONDRY_OFFICE_LOCATION,SECONDRY_OFFICE_PHONE,SCHOOL,YEAR_GRADUATED,DIRECTORY_DEPARTMENT,SALUTATION,COUNTRY_OF_CITIZENSHIP,PRIMARY_TITLE,DIRECTORY_TITLE,HOME_UNIT,IS_FACULTY,IS_GRADUATE_STUDENT_STAFF,IS_RESEARCH_STAFF,IS_SERVICE_STAFF,IS_SUPPORT_STAFF,IS_OTHER_ACCADEMIC_GROUP,IS_MEDICAL_STAFF,VACATION_ACCURAL,IS_ON_SABBATICAL,ID_PROVIDED,ID_VERIFIED,UPDATE_TIMESTAMP,UPDATE_USER,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,CITY,COUNTY,STATE,POSTAL_CODE,COUNTRY_CODE,FAX_NUMBER,PAGER_NUMBER,MOBILE_PHONE_NUMBER,ERA_COMMONS_USER_NAME,STATUS,SALARY_ANNIVERSARY_DATE) 
values ('10023',null,null,null,null,'Sun, Junsuo',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'66    246                     ','36545      ',null,null,null,null,null,null,null,null,'Postdoctoral Associate      ','062000','N',null,null,null,null,null,null,null,null,null,null,to_timestamp('27-FEB-99','DD-MON-RR HH.MI.SSXFF AM'),'OSPA','77 Massachusetts Ave.',null,null,'Cambridge','Middlesex','MA','02139','USA',null,null,null,null,'A',null);
INSERT INTO TEST_KRB_PERSON(MIT_ID,KRB_NAME)
VALUES('10023','Sun, Junsuo');