-- Create db link to connect to Nuvi database
-- Create views for NUVI_LONG_SURVEY,NUVI_LONG_SURVEY_RESP,NUVI_NDA_SURVEY,NUVI_NDA_SURVEY_RESP
CREATE TABLE LONG_SURVEY_NOTIF
(
  LONG_SURVEY_NOTIF_ID         NUMBER(22,0),
  NEGOTIATION_ID	NUMBER(22,0),
  PI_ID                        VARCHAR2(9 BYTE) NOT NULL,
  NEGOTIATION_CLOSE_DATE       DATE,
  NOTIFIED_FLAG                VARCHAR2(1),
  NOTIFICATION_DATE            DATE,
  SURVEY_COMPLETION_DATE       DATE,
  SURVEY_ID                    VARCHAR2(50),
  UPDATE_TIMESTAMP	DATE,
  UPDATE_USER	VARCHAR2(60),
  VER_NBR	NUMBER(8,0),
  OBJ_ID	VARCHAR2(36),
  CONSTRAINT PK_LONG_SURVEY_NOTIF PRIMARY KEY (LONG_SURVEY_NOTIF_ID ),
   CONSTRAINT UK_LONG_SURVEY_NOTIF UNIQUE  (NEGOTIATION_ID, PI_ID )
  )
/
CREATE SEQUENCE SEQ_LONG_SURVEY_NOTIF_ID
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER; 
CREATE TABLE LONG_SURVEY_OPT_OUT
(
  PI_ID                        VARCHAR2(9 BYTE) NOT NULL,
  SURVEY_OPTOUT_DATE           DATE, 
  UPDATE_TIMESTAMP	DATE,
  UPDATE_USER	VARCHAR2(60),
  VER_NBR	NUMBER(8,0),
  OBJ_ID	VARCHAR2(36),
  CONSTRAINT PK_LONG_SURVEY_OUT_OUT PRIMARY KEY (PI_ID )
)
/