ALTER TABLE NEGOTIATION_ACTIVITY_TYPE MODIFY DESCRIPTION VARCHAR2(50 BYTE)
/
UPDATE NEGOTIATION_ACTIVITY_TYPE SET DESCRIPTION = 'Agreements/Documents Signed/Executed' 
WHERE NEGOTIATION_ACTIVITY_TYPE_ID = 19
/
