CREATE TABLE AWARD_PERSON_REMOVE 
   (AWARD_PERSON_REMOVE_ID  NUMBER(22,0) NOT NULL ENABLE, 
	 AWARD_PERSON_ID  NUMBER(22,0), 
	 AWARD_ID  NUMBER(22,0), 
	 AWARD_NUMBER  VARCHAR2(40), 
	 SEQUENCE_NUMBER  NUMBER(4,0), 
	 PERSON_ID  VARCHAR2(40), 
	 CONFIRM_FLAG  CHAR(1), 
	 UPDATE_TIMESTAMP  DATE NOT NULL ENABLE, 
	 UPDATE_USER  VARCHAR2(60), 
	 VER_NBR  NUMBER(8,0) NOT NULL ENABLE, 
	 OBJ_ID  VARCHAR2(36), 
	 REMOVE_FLAG  CHAR(1), 
	 UPDATE_TIMESTAMP_CONFIRM  DATE, 
	 UPDATE_USER_CONFIRM  VARCHAR2(60)
)
/
ALTER TABLE AWARD_PERSON_REMOVE ADD CONSTRAINT AWARD_PERSON_REMOVE_PK PRIMARY KEY (AWARD_PERSON_REMOVE_ID)
/
CREATE TABLE AWARD_PERSON_CONFIRM(
  AWARD_PERSON_CONFIRM_ID 	NUMBER(22,0),
  AWARD_PERSON_ID	NUMBER(22,0),
  AWARD_ID	NUMBER(22,0),
  AWARD_NUMBER	VARCHAR2(12),
  SEQUENCE_NUMBER	NUMBER(4,0),
  PERSON_ID	VARCHAR2(40),
  CONFIRM_FLAG	CHAR(1),
  UPDATE_TIMESTAMP	DATE,
  UPDATE_USER	VARCHAR2(60),
  VER_NBR	NUMBER(8,0),
  OBJ_ID	VARCHAR2(36)
)
/
ALTER TABLE AWARD_PERSON_CONFIRM ADD CONSTRAINT AWARD_PERSON_CONFIRM_PK PRIMARY KEY (AWARD_PERSON_CONFIRM_ID)
/
