INSERT INTO KRCR_PARM_T (APPL_ID, NMSPC_CD, CMPNT_CD, PARM_NM, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, OBJ_ID, VER_NBR)
VALUES('KC', 'KC-GEN', 'All', 'PREAWARD_SPONSOR_AUTHORIZATION_COMMENT_TYPE_CODE', 'CONFG', '20', 'PREAWARD SPONSOR AUTHORIZATION COMMENT TYPE CODE', 'A', sys_guid(), 1)
/
INSERT INTO KRCR_PARM_T (APPL_ID, NMSPC_CD, CMPNT_CD, PARM_NM, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, OBJ_ID, VER_NBR)
VALUES('KC', 'KC-GEN', 'All', 'PREAWARD_INSTITUTIONAL_AUTHORIZATION_COMMENT_TYPE_CODE', 'CONFG', '21', 'PREAWARD INSTITUTIONAL AUTHORIZATION COMMENT TYPE CODE', 'A', sys_guid(), 1)
/
